### ISSUE TITLE
Ensure untruncated text in buttons

### ISSUE THREAD

**Issue by milotype** [flathub/website#1041]
**Ensure untruncated text in buttons independetly of display size.**

Don't use truncated text in buttons in wide screen display.
In smaller screen display, the string displays completely.

Used CSS:
```
.text-ellipsis, .truncate {
    text-overflow: ellipsis !important;
```

Example: https://beta.flathub.org/hr/apps/org.gnome.Cheese

**Screenshots**
_Wide display_
![screenshot 1](https://user-images.githubusercontent.com/43657314/218278109-1eea0fee-4318-4e57-9cd5-4c4e4ae6ee67.png)

_Small display_
![screenshot 2](https://user-images.githubusercontent.com/43657314/218277939-3eca6f7d-a2a5-4487-8ed3-83598d657b65.png)

**Comment by razzeee** [comment]
We can probably make them a bit bigger, but we will need to truncate at some point. Otherwise they would overflow or go multiline, which is problematic too.

**Comment by milotype** [comment]
@razzeee I see the problem about truncating when the buttons "Install" and "Donate" are used in some apps. Apps which don't have the button "Donate", the button "Install" doesn't get truncated.

My thoughts/suggestion:
When the buttons "Install" and "Donate" are used together, maybe they could be placed one bellow the other without truncating the strings …

**Comment by razzeee** [comment]
We had that Design before e.g. in https://github.com/flathub/website/issues/21 I don't think we want that back

**Comment by milotype** [comment]
@razzeee OK.
In order not to truncate the strings in buttons at wide screens, maybe an alternative could be to use the same layout as in the narrow screens – placing those buttons as a separate row. Something like this:

![alternative](https://user-images.githubusercontent.com/43657314/218343331-0f4f2cd2-096a-43d1-98a6-0d04f493c335.png)
