### ISSUE TITLE
Better 404 Page

### ISSUE THREAD

**Issue by JakobDev** [flathub/website#1050]
The current 404 Page is a bit problematic:
![grafik](https://user-images.githubusercontent.com/15185051/218395012-9542c909-eeaf-4518-9422-9ae0cf75ebb7.png)
The text sounds like that a Bug happened. Maybe caused by a Bug in the Browser or Website or a Extension makes Problems. But it does not sound like, that you Page the User tries to open just do not exists. If we serve a 404 error, we should say that IMHO instead f this confusing text.

**Comment by razzeee** [comment]
Good catch, thanks
