### ISSUE TITLE
Flathub website is still showing the old version of the app icon

### ISSUE THREAD

**Issue by mijorus** [flathub/website#1051]
Hi, 

I have updated my app:
https://flathub.org/apps/details/it.mijorus.smile

with this new icon:
https://github.com/mijorus/smile/blob/master/docs/it.mijorus.smile.svg

But on Flathub I still see the old one.

Is it just just caching? If so, how long does it last?

Thank you

**Comment by razzeee** [comment]
@barthalion this might be a question for you, it seems like the mirror hasn't yet received the new icon

**Comment by mijorus** [comment]
Seems to work now, but I guess this is an issue nonetheless

**Comment by razzeee** [comment]
This seemed to be faster on some tests in the last days, so I'll close this.
