### ISSUE TITLE
Change cookies to expire

### ISSUE THREAD

**Issue by barthalion** [flathub/website#1063]
Currently, session seems to expire after over a year? We should make it much shorter.

**Comment by razzeee** [comment]
I'm at a loss, how this actually works right now.

The cookies that we looked at and are next to the only thing that seems to get saved in the browser, seem to be matomo related. https://matomo.org/faq/general/faq_146/

Session storage only has nextjs scroll restore items.

Localstorage has `returnTo`, which is used by us to redirect.

I can even clear cookies and local storage and will not be logged out after refreshing.

**Comment by razzeee** [comment]
https://www.starlette.io/middleware/#sessionmiddleware is used to implement the server side session and we don't set the max_age, so it should be 2 weeks.

So if I use chromium, I can see a cookie with the name `session`. If I delete that cookie and refresh, I'm logged out. And it would expire 2023-03-02T00:51:39.002Z

**Comment by razzeee** [comment]
Asked around in the firefox element room. It might be cause those cookies have the `flathub.org` domain and not `beta.flathub.org`  and thus get hidden from firefox dev tools.
