### ISSUE TITLE
Production deployment

### ISSUE THREAD

**Issue by barthalion** [flathub/website#1069]
- [x] Deploy flathub-hooks
- [x] Populate subsets with verified/free software apps
- [x] Test subsets with runtimes
- [x] upload sitemap on some search engines
- [x] change to production apps on gitlab/github etc
- [x] change link in repo, should probably link to both pages? https://github.com/flathub/website

**Comment by razzeee** [comment]
- [ ] upload sitemap on some search engines

**Comment by razzeee** [comment]
https://developers.google.com/search/docs/crawling-indexing/sitemaps/build-sitemap

**Comment by razzeee** [comment]
Link has not been updated 
![image](https://user-images.githubusercontent.com/5943908/234851616-1808dbb9-3793-4d3d-8626-f7074ea625e9.png)
