### ISSUE TITLE
Should we be using flathub staff / maintainers

### ISSUE THREAD

**Issue by razzeee** [flathub/website#1078]
We currently use both wordings:

`Flathub staff`

`Flathub maintainer`

Is that correct or should we change to one?

@ramcq

**Comment by ramcq** [comment]
I think Flathub team is best!

**Comment by razzeee** [comment]
So both wordings should be -> `Flathub team`?

Staff:
https://github.com/flathub/website/blob/8edadf1efbeeff4df7845bfe93039adac46014f7/frontend/public/locales/en/common.json#LL251C116-L251C129
https://github.com/flathub/website/blob/8edadf1efbeeff4df7845bfe93039adac46014f7/frontend/public/locales/en/common.json#L278

Maintainer:
https://github.com/flathub/website/blob/8edadf1efbeeff4df7845bfe93039adac46014f7/frontend/public/locales/en/common.json#LL89C83-L89C96
