### ISSUE TITLE
discussion about verification badge

### ISSUE THREAD

**Issue by gigglylo** [flathub/website#1082]
What I understand about verification badge on verified apps on flathub beta, is that the badge is a mark for apps that is packed by the actual developer.

Let's us imagine a bit. In the ideal world, all apps provided by flathub, are maintained directly by their developer. So, there's no need for the badge. It's not like Twitter, where people can easily make an account and name it whatever they want. I imagine there's a bit of moderation of what apps can be seen on public by flathub maintainer/community.

"But we are not in the ideal world" you might ask, that's right. Many apps are packed by community. So, what I have in mind, instead of giving verification badge for "official" apps, we just mark all community packed apps with "community maintained" badge. That way, we know every apps are official, except when it's not. Reduce confusion of what "verified" even means. 

This also, gives urgency for real developers to maintain their own apps directly on flathub. Especially when people calling them out on social media about the community badge.

That leaves some case where an app is maintained by official developer, but still not verified by whoever responsible. In that case, maybe put "waiting for verification" badge or something. Well, we can always have discussion. So feel free to discuss this matter further, I would love to hear it. Or maybe just close this issue if it's not in the right place or inappropriate.

**Comment by razzeee** [comment]
I think positive reinforcement is more valuable then shaming devs.

**Comment by razzeee** [comment]
I'm going to close this, as there doesn't seem to be a task, we can discuss in a closed issue.
