### ISSUE TITLE
Request to Enable GitHub Discussions in the Website Repository

### ISSUE THREAD

**Issue by Wladefant** [flathub/website#1092]
Hello Flathub maintainers,

As someone who is interested in becoming an active contributor to the Flathub project, I would like to suggest enabling GitHub discussions in the repository where the source code of the Flathub website is hosted.

Currently, the forum for Flathub discussions is not very active, and it may be beneficial to consolidate all discussions related to the Flathub project in one repository, i.e., the website repository. Since GitHub is a widely used platform in the open-source community, it is likely that more developers and contributors would engage in discussions if they were hosted on GitHub.

Enabling GitHub discussions in the repository would allow for threaded conversations, which can make it easier to follow and respond to specific topics or questions. It can also help to prevent discussions from becoming cluttered and hard to navigate, which is a common problem with traditional forums.

Furthermore, by enabling discussions in the repository, it can help to promote transparency and collaboration within the Flathub community. It allows contributors to have an open platform to discuss and share ideas, which can help to build a stronger and more engaged community.

Using GitHub discussions can also help to reduce the amount of time and resources needed to manage and maintain a separate forum or discussion platform. By consolidating all discussions within the repository, it can help to reduce the workload for Flathub maintainers and make it easier for them to respond to user feedback and bug reports.

Additionally, everyone in the open-source community already has GitHub and is using it extensively. Enabling GitHub discussions can help to ensure that the Flathub community can easily find and engage in discussions related to the project.

Finally, GitHub discussions can be integrated with other GitHub features such as pull requests, issues, and milestones. This can help to streamline the development process and make it easier to track progress and collaborate on specific tasks or features. It is also possible to create issue and discussion templates to help streamline the process of reporting issues and submitting feature requests.

As someone who is interested in becoming an active contributor to the Flathub project, I believe that enabling GitHub discussions in the Flathub website repository would greatly benefit the project and the community. I would be willing to help create issue and discussion templates that would facilitate communication and improve the overall efficiency of the project.

Thank you for your consideration.

Sincerely,
Wladimir Kirianov

**Comment by razzeee** [comment]
I think we want to stick to issues for now, but feel free to open up issues for things your thinking should be discussions.

If there are enough issues like that eventually, it might start making sense.
