### ISSUE TITLE
Font weight not respected in webkit

### ISSUE THREAD

**Issue by jimmac** [flathub/website#1107]
![Screenshot from 2023-02-22 10-17-04](https://user-images.githubusercontent.com/14821/220576109-da24a0e1-9d5a-43a7-b62f-5d5c0c9d62cf.png)

I believe I ran into this with variable fonts. The workaround I've used is to provide `font-variation-settings: "wght"` apart from `font-weight` property. 

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Fonts/Variable_Fonts_Guide#weight

**Comment by razzeee** [comment]
I think this might be a next/font issue :/

**Comment by bertob** [comment]
FWIW we've had the same problem on other websites (e.g. my personal website https://tobiasbernard.com), and it seems to be specific to WebkitGTK, rather than all of Webkit.

**Comment by razzeee** [comment]
It seems to be fine in gnome web now?

**Comment by bertob** [comment]
Seems fixed indeed!
