### ISSUE TITLE
Slash shortcut key icon in search bar unclear

### ISSUE THREAD

**Issue by flipflop97** [flathub/website#1118]
The slash shortcut key icon on the right of the search bar is confusing to me, which lead to me not being able to figure out what it was for. There are 3 main problems/improvements I see with respect to this:

- [x] The slash inside the icon is too slanted to be easily recognized as a slash. It would be clearer is this slash would look like as it would normally.
- [x] The icon is still there when the action is performed or when the search bar is selected otherwise. This made me believe it would do something when the bar was already selected. It should probably disappear once the entry is selected.
- [ ] Some extra form of explanation like a tooltip can be made to explain the shortcut in text. GitLab does this, but GitHub doesn't. It could make the situation clearer, but if above points are addressed this might be unnecessary.

![afbeelding](https://user-images.githubusercontent.com/13943260/221011218-aa279c32-e1f9-474b-b680-509b5ab9fe38.png)

### Original comment

It is completely unclear to me what the icon on the right of the search bar represents, and what it is communicating to me. It is there when not in use, and randomly disappears then starting to type. It is there on my laptop, but not on my phone. What does it represent, and why is it there?

**Comment by flipflop97** [comment]
> That you can press / and end up in that textbox, as you can on github for e.g.

Ah, I see now that you say that. I'd personally make the slash less slanted though, so that it actually represents a slash on a keyboard. Maybe a tooltip or something similar on that icon explaining the keyboard shortcut would also help.

**Comment by razzeee** [comment]
Yeah, it's a bootstrap icon, we usually try to exclusively stick to https://heroicons.com/ but there's no such icon in there last time I checked.

Tooltip would be a good idea.

**Comment by AlessandroBono** [comment]
For inspiration, Gitlab has the following tooltip:
![Screenshot from 2023-02-24 12-36-58](https://user-images.githubusercontent.com/32013401/221170425-262a4eaf-38d7-48e1-9647-9e659f75a5d8.png)

**Comment by razzeee** [comment]
Github doesn't seem to be adding a tooltip at all btw

**Comment by flipflop97** [comment]
I think having a better, less slanted slash icon, would make this a lot clearer already. Does Hero Icons accept icon requests? That might be a good place to start.

**Comment by razzeee** [comment]
I actually don't know, we can try.

**Comment by razzeee** [comment]
Then again, gitlabs might just be a normal slash with some styling

**Comment by flipflop97** [comment]
Made a request on Hero Icons: https://github.com/tailwindlabs/heroicons/discussions/943

I checked and GitLab indeed uses a styled slash character, but GitHub uses a dedicated icon for it.

Another note / point of improvement: The icon in the search box stays visible when the search box is focused, indicating that it might still do something. It would be better in my opinion if the icon disappeared as soon as the input is selected and it has no use anymore. Both GitLab and GitHub do the same.

**Comment by razzeee** [comment]
We hide whenever you enter the first letter, but would make sense to hide it earlier.

**Comment by flipflop97** [comment]
Thanks! I think that should probably be clear enough. Do you intend to also create a tooltip? Otherwise we can just close this.

**Comment by razzeee** [comment]
I've tried some days ago, but it wasn't as trivial as I would have liked.

For now I think there are more important things to work on.

**Comment by flipflop97** [comment]
That sounds fair, I'll close this then. Thanks!
