### ISSUE TITLE
Top links in about section have low contrast

### ISSUE THREAD

**Issue by flipflop97** [flathub/website#1119]
The links to Flatpak and setup instructions at the top of the [about page](https://beta.flathub.org/en/about) have very low contrast and are very hard to read. All other links are a lot darker, these links should probably be too.

![afbeelding](https://user-images.githubusercontent.com/13943260/221013399-da234135-6653-4a92-bae8-42ff59e063aa.png)

**Comment by razzeee** [comment]
Yes, sorry, I've removed the background there due to the header changes we made in the last days.
