### ISSUE TITLE
Alternative Websites (Flathub as a base)

### ISSUE THREAD

**Issue by RMcNeely** [flathub/website#1122]
Hey team, I'm pretty sure this has been discussed before but I can't find a similar issue, maybe it was in the old repo? If there's a better place for this discussion to happen I'll go elsewhere. 

Is there any plan to have a "base" flatpak front end that can be set up to work with different backends? I'm looking to see if there's any way that elementary can leverage your work and contribute back if possible rather than developing a separate front end for a hypothetical new version of [appcenter.elementary.io](https://appcenter.elementary.io)? Currently our setup is a bare Jekyll template running over appstream data but providing a new front end would be a nice upgrade.

**Comment by razzeee** [comment]
Did you try to set the env vars https://github.com/flathub/website/blob/main/backend/.env.ci to wherever your elementary data lives? And then calling the update api endpoint (the stats one probably won't work, as that's not configurable right now, then again, I'm not sure if that would even work for you)

I'm certain it wouldn't completely work, but it also shouldn't break instantly™

**Comment by barthalion** [comment]
I think only download stats are specific to our infrastructure, but keep in mind some places have flathub.org hardcoded. I don't mind a PR to change it.

**Comment by barthalion** [comment]
Going to close it, as I don't think it's a goal for us to be a generic project, but we won't block external contributions to help achieve that.
