### ISSUE TITLE
Broken images on the website?

### ISSUE THREAD

**Issue by Jacalz** [flathub/website#1129]
I am seeing the first image being entirely black on https://beta.flathub.org/en-GB/apps/io.github.jacalz.rymdport but the other image seems fine. On https://flathub.org/apps/details/io.github.jacalz.rymdport the same thing happens but both image previews are black as well.

![image](https://user-images.githubusercontent.com/25466657/221285753-c45e6ffd-c373-462d-9ec1-625185c370f5.png)
![image](https://user-images.githubusercontent.com/25466657/221285813-e2a8c325-551d-4c5a-9d1d-7ab0325f537b.png)

The images worked fine when I added them in January (see https://github.com/Jacalz/rymdport/blob/main/internal/assets/screenshot1.png and https://github.com/Jacalz/rymdport/blob/main/internal/assets/screenshot2.png) and the links in https://github.com/Jacalz/rymdport/blob/main/internal/assets/unix/io.github.jacalz.rymdport.appdata.xml have not changed since then. Everything looks fine on my end so I don't entirely get why they appear broken on your site.

The only thing I can think of is that the images are compressed with https://tinypng.com/ but they worked a month ago so I don't quite know if that is the reason.

I had something similar (but I think the images were white instead) a while back and opened https://github.com/Jacalz/rymdport/issues/61 but now it seems to be on desktop as well and not only on mobile.

**Comment by Newbytee** [comment]
There are similar corruptions here: https://flathub.org/apps/xyz.mx_moment.moment

**Comment by Jacalz** [comment]
Indeed. They seem even worse. I checked the network inspector in Firefox and it seems like it doesn't actually fetch the images from the links that are in the appdata but instead to some local copy on the flathub website. My guess is that something is wrong with how the images are copied to the flathub storage.

**Comment by razzeee** [comment]
Afaik something happened and images needed to be recopied recently, I suspect, that this was introduced by that.

**Comment by Jacalz** [comment]
Rymdport seems fine on my end now but the moment app linked above still seems broken for me.

**Comment by razzeee** [comment]
https://beta.flathub.org/apps/com.github.yucefsourani.albasheer-electronic-quran-browser might also suffer from this?

**Comment by Jacalz** [comment]
Rymdport still seems broken on mobile. Was definitely work on desktop a few days ago but it might just have been a temporary thing

**Comment by razzeee** [comment]
I checked, when you wrote this and wasn't able to confirm, that it was fixed

**Comment by hfiguiere** [comment]
This app screenshots are 404 on the CDN

https://beta.flathub.org/apps/com.gitlab.coringao.cavestory-nx

**Comment by razzeee** [comment]
All listed here seem to be fixed now
