### ISSUE TITLE
Name next to avatar unreadable

### ISSUE THREAD

**Issue by flipflop97** [flathub/website#1130]
The name next to the users avatar in the menu is very low contrast. The text is white while the background is light gray.

![Screenshot_2023-02-25-10-21-29-53_40deb401b9ffe8e1df2f1cc5ba480b12~2](https://user-images.githubusercontent.com/13943260/221349466-d133901d-df6d-4be8-a6a2-7ae5382d080b.jpg)

**Comment by razzeee** [comment]
Thank you, it's easy to miss stuff like this, with the big refactors we are doing right now (and me not using light mode as much)

It's really valuable help.

**Comment by flipflop97** [comment]
Thanks, glad to help! If you ever feel like I'm being too nitpicky, let me know.
