### ISSUE TITLE
New inverted badges have incorrect logos

### ISSUE THREAD

**Issue by HappiePlant** [flathub/website#1134]
The triangle from the new logo isn't rounded in the inverted badges found on https://beta.flathub.org/badges

![](https://raw.githubusercontent.com/flathub/website/9bf00aab49fd7ccc35223d7c87fe1646b8fc6bd3/frontend/public/assets/badges/flathub-badge-i-en.svg)
[Path](https://github.com/flathub/website/blob/9bf00aab49fd7ccc35223d7c87fe1646b8fc6bd3/frontend/public/assets/badges/flathub-badge-i-en.svg)
![https://github.com/flathub/website/blob/9bf00aab49fd7ccc35223d7c87fe1646b8fc6bd3/frontend/public/assets/badges/flathub-badge-i-en.svg](https://github.com/flathub/website/blob/main/frontend/public/assets/badges/flathub-badge-i-en.png?raw=true)
[Path](https://github.com/flathub/website/blob/9bf00aab49fd7ccc35223d7c87fe1646b8fc6bd3/frontend/public/assets/badges/flathub-badge-i-en.png)

**Comment by razzeee** [comment]
See https://github.com/flathub/website/pull/1125#issuecomment-1442708594
