### ISSUE TITLE
Badge code copy icon scrolls with content

### ISSUE THREAD

**Issue by flipflop97** [flathub/website#1136]
The copy icon of the badges code also scrolls when scrolling the content, and always overlaps the text in the bottom case. The copy icon should probably stay fixed in the top right corner.

![Screenshot_2023-02-26-13-41-50-18_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/13943260/221411121-0501a092-3747-4408-a88c-97798702f071.jpg)

**Comment by razzeee** [comment]
Seems to only affect non firefox browsers
