### ISSUE TITLE
Glitchy border on search bar

### ISSUE THREAD

**Issue by bertob** [flathub/website#1143]
There's a glitchy double border on the search bar, I think this could just be dropped when the entry doesn't have focus, maybe in addition to making the search background more distinct from the header background.

![image](https://user-images.githubusercontent.com/1908896/221697487-c7a68255-fd88-4202-9c4b-fbce1044de2a.png)

**Comment by razzeee** [comment]
That border get's hidden, when it get's focus right now.

The light one only has this border, as the background color is the same as the header background color. I didn't want to use the lightest gray of our picked colors, as that already is too gray IMO

**Comment by razzeee** [comment]
It seems like Gnome Web doesn't realize that the outline should be rounded, so I guess we need to find another design without that.
