### ISSUE TITLE
Card styling: weird hover/active states

### ISSUE THREAD

**Issue by bertob** [flathub/website#1167]
In light, the hover state is too subtle (background doesn't change, only the shadow), while in dark it's too heavy (very drastic change to background color). Active states are too drastic in both cases, and the dark one gets darker instead of lighter.

Hover:

![image](https://user-images.githubusercontent.com/1908896/222190749-3ee1ca7a-77fa-4de6-9c4e-10f511b48f72.png)

Click:

![image](https://user-images.githubusercontent.com/1908896/222190881-6e0ae059-1e84-4636-a925-2f989aa4365b.png)

Hover:

![image](https://user-images.githubusercontent.com/1908896/222191202-b1b6cddb-4ed1-4eb9-a23b-b8063d738e4b.png)

Click:

![image](https://user-images.githubusercontent.com/1908896/222191173-9a2e480f-e6fd-4fab-85fd-9ff15a064ddd.png)

For an example of how to do this in a nice, subtle way look at libadwaita's .card class.

Hover: 

![image](https://user-images.githubusercontent.com/1908896/222191980-7eb8697a-c973-4e35-a30b-8b156a3ac4a7.png)
![image](https://user-images.githubusercontent.com/1908896/222192063-5d085eb8-1457-481d-b91e-0e77d411cb70.png)

Click:

![image](https://user-images.githubusercontent.com/1908896/222192200-c38ee583-1feb-4dc2-a8a3-9cb37ddd367c.png)
![image](https://user-images.githubusercontent.com/1908896/222192140-6130e167-0f97-42a2-87f5-00a2ed5bb2e3.png)

**Comment by razzeee** [comment]
> (background doesn't change, only the shadow),

The background is changing, but it's just a 5% transparency right now

**Comment by razzeee** [comment]
Let me know, if the new ones are in an acceptable range

**Comment by bertob** [comment]
Hover looks good to me now, but in dark the active state looks the same as hover now. I'd make that a little bit stronger, same as in light. I'm also not sure about reducing the shadow to 0 in the light active state.

**Comment by razzeee** [comment]
I can definatly see the dark active stlye being different to the hover for me, but I guess you just mean it should be stronger?

The shadow just was an experiment, we can remove it. But I do like, the touch it adds, as it helps the card to pulse after you click it. And if you actually hold it down (in active) you don't get shadows that almost match the content background. Not sure why we should optimize for people holding this down, but that was the thought process.

Btw shadow shouldn't be zero, it might be on the top at that level.
