### ISSUE TITLE
User page papercuts

### ISSUE THREAD

**Issue by flipflop97** [flathub/website#1170]
There are a few things that look weird to me on the user page:

- [x] The users name is not horizontally aligned with the rest of the first cards content, I'd personally reduce the horizontal spacing of the lower part with account items.
- [x] The shadow of the different account cards blends in with the account cards color, I'd personally drop the card style here as it also is a double stacked card.
- [x] The title and content of the account items are more towards the top of the card, I'd center them vertically (and maybe reduce the padding a little).
- [x] The title of the "Authored apps" section is vertically misaligned with the Refresh button.
- [x] The card at the bottom only contains one button for account deletion. I'd personally remove the card here, unless more buttons are added.

<img src="https://user-images.githubusercontent.com/13943260/222236605-2c82236c-5ddf-448c-8080-c9236166ce56.png" width="400px" alt="Account page screenshot">

**Comment by razzeee** [comment]
Userpage has been redone, there will probably be other papercuts now

**Comment by flipflop97** [comment]
Thanks, that looks a whole lot better! Only one of my original points remains. If I find any other, I'll create separate issues for them.

**Comment by razzeee** [comment]
https://github.com/flathub/website/pull/1236 should help, unless somebody with a ridiculous long name appears

**Comment by flipflop97** [comment]
That checks of that one too, thanks a lot :)
