### ISSUE TITLE
Font isn't loading on deployment

### ISSUE THREAD

**Issue by razzeee** [flathub/website#119]
The `Inter` font seems to work in local testing. But on https://beta.fluthub.com it seems to not load.

**Comment by razzeee** [comment]
@barthalion I guess it's due to the font being on another domain? can we move it into this repo and just use it from here?

https://stackoverflow.com/questions/19817459/firefox-font-face-with-local-file-downloadable-font-download-failed

**Comment by barthalion** [comment]
It definitely works for me.

![image](https://user-images.githubusercontent.com/380403/162903749-63055ec0-5ff2-4f23-94bd-91b9bc253e69.png)

We also set `access-control-allow-origin *` to make sure any domain can fetch it.

**Comment by razzeee** [comment]
Works for me now, not sure why. Previously I got this on every load.

**Comment by razzeee** [comment]
Your right, you can force it with Control + F5

**Comment by bilelmoussaoui** [comment]
For whatever reason i am still getting `downloadable font: font-display timeout, webfont not used (font-family: "Inter" style:normal weight:400 stretch:100 src index:0) source: https://dl.flathub.org/repo/assets/Inter-3.19/Inter-Regular.woff2` from time to time. Can't we just ship the font as part of the assets?

**Comment by barthalion** [comment]
This is not going to change anything, as loading the font will still not finish within 100ms which browser use as the time limit. It will be even slower as it will served from UK instead from your closest CDN host.

**Comment by bilelmoussaoui** [comment]
actually never mind, the error is not about not being able to download the font at all...
