### ISSUE TITLE
Install button too small on mobile layout

### ISSUE THREAD

**Issue by flipflop97** [flathub/website#1195]
The install button can become too small when shrinking the app page and a donate button is visible, the donate button doesn't shrink at all. The screenshot below is made using a width of 300px.

<img src="https://user-images.githubusercontent.com/13943260/223067971-af78bf86-8575-440a-a724-4213235f3fa8.png" width="300px" alt="Screenshot app-page with width 300px">

**Comment by razzeee** [comment]
Should be fixed as we reverted to the old behavior
