### ISSUE TITLE
Cards: Scale effect doesn't work

### ISSUE THREAD

**Issue by bertob** [flathub/website#1202]
The new scale animation on hover is janky (at least in Firefox and Epiphany) and makes the text look blurry. It's also unexpected/disorienting, as elements this large don't usually use this kind of effect, and unnecessary -- I think a subtle background color change is fine as a hover state here, no need for more :)

Edit: I just realized that buttons have a scale effect now too, I think it works better there but the blurry text is still a bummer. I'd use the box shadow trick there instead, i.e. grow the box shadow with an animation, without transforming the rest of the button. I've been meaning to get rid of the scale effect on buttons on our other websites, I thought browsers would eventually fix this but at this rate it doesn't seem so :(

**Comment by razzeee** [comment]
I'm only testitng in firefox usually and I don't think it gets blurry, but I might just not be sensitive to that kind of thing.

**Comment by bertob** [comment]
Depends on your hardware to some degree maybe, but it definitely is on my desktop monitor. I also tried it on an older low res laptop the other day, and it was super blurry (in addition to just dropping frames and glitching out during the animation).
