### ISSUE TITLE
Card styling: Verified badge position

### ISSUE THREAD

**Issue by bertob** [flathub/website#1215]
The badge in the corner looks off to me, I'd move it inline next to the app name.

![image](https://user-images.githubusercontent.com/1908896/223830001-6af750da-5cb4-4922-aec4-a9b113832af7.png)

**Comment by razzeee** [comment]
We specifically tried to not have the checkmark next to the name on the detail page, so this might cause confusion / wrong assumtions

**Comment by razzeee** [comment]
It's a stop gap, I basically wanted something simple to get the backend/data flow in and not spend much time on the display.

I'll want to explore an additional line below the summary with verified and maybe later FLOSS state and see how that works with longer summaries etc

**Comment by razzeee** [comment]
Closing as there's a follow up issue
