### ISSUE TITLE
Verified badge and long app name can overlap

### ISSUE THREAD

**Issue by flipflop97** [flathub/website#1217]
When an app name is really long, for example GIMP, it overlaps with the verified badge in the app lists on narrow widths. The app name should probably be ellipsised or faded out here.

![Screenshot_2023-03-09-10-07-58-57_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/13943260/223974149-83a25e61-925a-42a6-8274-a03c0c17225c.jpg)

**Comment by razzeee** [comment]
This can't happen anymore with the new design
