### ISSUE TITLE
App card spacing improvements

### ISSUE THREAD

**Issue by flipflop97** [flathub/website#1254]
There are a few things regarding spacing of the new app card layout that seem a little off to me:

- [ ] App cards can have completely different heights, this makes the view a bit cluttered in my opinion. I'd personally fix the height to be the same for all apps, and ellipsize the description if necessary. (Only applies to mobile layout AFAIK)
- [ ] There's a lot of spacing between the app title and the description, but not between the description and the verified badge. I'd reduce the spacing above the description by half, to match both spacings.
- [ ] There's very little spacing between the verified check and the verified check, I'd increase the spacing a little between those two.

Left: layout right now  
Right: proposed layout

<img src="https://user-images.githubusercontent.com/13943260/225007527-48434c96-5e66-4924-a3b7-975a06492dfd.png" width="300px"><img src="https://user-images.githubusercontent.com/13943260/225009740-6dff67c8-dc32-4d40-a735-88c3312e926d.png" width="300px">

**Comment by razzeee** [comment]
I don't think that's an improvement
