### ISSUE TITLE
Low resolution icons are displayed small and misaligned

### ISSUE THREAD

**Issue by flipflop97** [flathub/website#1261]
Icons that have no high resolution set (like Skype at the moment), are displayed small and misaligned to the top. This problem exists on both the app card in an app list (see screenshot) and the app page itself. They should probably be displayed at the same size as other icons.

![image](https://user-images.githubusercontent.com/13943260/225713143-826baa89-e950-4669-ad75-38ce1296cfe9.png)

**Comment by razzeee** [comment]
It might be nicer to show the small icon, upscaling them does look bad

![image](https://user-images.githubusercontent.com/5943908/225936844-d4edfa23-a16f-495d-9dff-e105eda7cfba.png)

**Comment by razzeee** [comment]
Closed by https://github.com/flathub/website/pull/1268
