### ISSUE TITLE
Architectures tile glitch

### ISSUE THREAD

**Issue by bertob** [flathub/website#1262]
The architecture tile can break if there's no subtitle:

![image](https://user-images.githubusercontent.com/1908896/225778935-6bb6f97d-7530-4d61-b6ae-8a2403f3b8cf.png)

**Comment by razzeee** [comment]
This seems to affect all apps right now. Something seems to have changed with the summary files creating arches, as the data seems empty.

**Comment by bertob** [comment]
Maybe it'd be good to have some kind of fallback though, either a default string or a min height?

**Comment by razzeee** [comment]
There's no value in showing it at all in that case IMO

**Comment by bertob** [comment]
Ah right, just hiding the architecture tile in that case is an even better fallback :D
