### ISSUE TITLE
App tiles: verification is too prominent

### ISSUE THREAD

**Issue by bertob** [flathub/website#1270]
App tiles now show not only a check for verification, but also spell out what is verified. I get that we want to incentivize people to verify their apps, but since this ends up being a very long string in some cases it makes the feature too prominent visually. I'd show just a check, and expose the exact detail on what's being verified in a tooltip.

![image](https://user-images.githubusercontent.com/1908896/226068324-b968f90e-1d26-4648-ad8d-12c338bc2347.png)

![image](https://user-images.githubusercontent.com/1908896/226068364-6fac569b-ae2c-4535-864c-e88ad3f6ac7d.png)

**Comment by razzeee** [comment]
I don't think adding the hover box is a great idea on a listing page.

In general I agree that this design should change, but for different reasons.

Initially it only was:

Ckeckmark + Static verified text

When I would have liked it to be that + | FLOSS (when it is that)

Anyway, I think we need a way of communicating donation / payment apps in listings at some point.

So I'm worried about not having space for that / the design not aligning.
