### ISSUE TITLE
Language not set when starting on subpage

### ISSUE THREAD

**Issue by flipflop97** [flathub/website#1272]
When navigating to the home page of Flathub, it detects my language and sets it automatically and switches to that language. When navigating to a subpage of Flathub, it doesn't do that, and the rest of the session is also in English. Clicking a link to a subpage without a language code in the URL should probably have the same behavior as going to the homepage.

[Homepage](https://beta.flathub.org) - Switches to native language
[App list page](https://beta.flathub.org/apps) or [app details page](https://beta.flathub.org/apps/org.gnome.Crosswords) - Stays English, even after navigating somewhere else

**Comment by razzeee** [comment]
This seems to be default nextjs behavior https://nextjs.org/docs/pages/building-your-application/routing/internationalization#automatic-locale-detection

I'm unsure, if we want to touch it

**Comment by razzeee** [comment]
Closing, as we probably won't be able to change this
