### ISSUE TITLE
Apps I have commit access to via a team do not show on My Flathub developer dashboard

### ISSUE THREAD

**Issue by cassidyjames** [flathub/website#1292]
I'm a member of the @flathub/endless team on GitHub, which has commit access to the manifests for Endless apps (e.g. [Aqueducts](https://github.com/flathub/com.endlessnetwork.aqueducts/)) on GitHub. However, when logging into the My Flathub dashboard at [beta.flathub.org](http://beta.flathub.org/), I don't see the Endless apps there. I've tried hitting the refresh button, as well.

@wjt has direct commit access to the same manifests—i.e. not just via a team membership—and sees the apps on his My Flathub dashboard.

Is it possible Flathub is only looking at direct user access and not accounting for team membership?

**Comment by wjt** [comment]
FWIW I worked around this by just doing the verification for those apps myself, but it think it would be nice to fix anyway!

**Comment by cassidyjames** [comment]
@barthalion this appears to have been fixed by 64733939910f08aa7b7953c5b2485367755e1f83
