### ISSUE TITLE
Footer entries aren't centered for some translations in mobile

### ISSUE THREAD

**Issue by kbdharun** [flathub/website#1311]
Currently the footer entries seem to be centred properly in mobile on English and some languages with smaller character typefaces but it is centred incorrectly for some languages like Tamil, etc which has a larger characters. This issue isn't present in the desktop version.

## Reference image 

![Flathub footer - Tamil](https://user-images.githubusercontent.com/26346867/229285591-7a6d9a5c-6684-4634-bfd5-8e5e89d3ebea.jpg)

**Comment by flipflop97** [comment]
I can also reproduce this in English with a width of 300:

<img src="https://user-images.githubusercontent.com/13943260/229342412-a2d4447a-e070-4c18-9ca1-1db674c780b2.png" width=300>

**Comment by kbdharun** [comment]
> I can also reproduce this in English with a width of 300:
> 

Oh, So the text seems to be not adaptive for the mobile form factor with different scaling

**Comment by kbdharun** [comment]
Thanks
