### ISSUE TITLE
Reaper doesn't show changelog

### ISSUE THREAD

**Issue by razzeee** [flathub/website#1336]
https://beta.flathub.org/apps/fm.reaper.Reaper should show a changelog

https://github.com/flathub/fm.reaper.Reaper/blob/master/fm.reaper.Reaper.metainfo.xml#L27

**Comment by JakobDev** [comment]
It should not. This is the current release tag:
```xml
<release version="v6.78" date="2023-03-13">
    <ul>
        <p>The following components were updated:</p>
        <li>- FX</li>
        <li>- MIDI editor</li>
        <li>- Render</li>
        <li>- Actions</li>
        <li>- MIDI</li>
        <li>- Project tabs</li>
        <li>- Snap</li>
        <li>- Track panels</li>
        <li>- Vertical zoom</li>
        <li>- VST</li>
        <li>- Windows</li>
    </ul>
</release>
```
[According the the Documentation](https://www.freedesktop.org/software/appstream/docs/sect-Metadata-Releases.html#tag-release-description), the Changelog must be put inside a `<description/>`. Reaper does this not, so it is not found.

**Comment by razzeee** [comment]
Right, I theoretically know that, I just starred at it and did not see it. (and would have hoped for the linter to catch it)

**Comment by JakobDev** [comment]
> (and would have hoped for the linter to catch it)

I had opened a PR to AppStream to add a check for this, so when Flathub switches from `appstream-util` to `appstreamcli`, this Problem is fixed.
