### ISSUE TITLE
Move login into header

### ISSUE THREAD

**Issue by razzeee** [flathub/website#135]
I think we would be fine to move the login/user button from the footer into the header now.

**Comment by oyajun** [comment]
If account name is long, UI is broken.
![image](https://user-images.githubusercontent.com/81346541/167232580-7054a8bd-88fb-464f-baf4-0b9440d659cb.png)

I want to move the seach bar to left.
![image](https://user-images.githubusercontent.com/81346541/167232716-a8c6cebc-ee59-4b1e-a72a-9af02cefb020.png)
