### ISSUE TITLE
Filter proprietary software

### ISSUE THREAD

**Issue by vanillajonathan** [flathub/website#1365]
Maybe there could be a way to filter out proprietary software to only show free, open source software?

In order to help users from accidentally installing proprietary software, on the app info page, if a software is proprietary software maybe it could show "Proprietary" in red color and/or with a warning icon?

**Comment by Danielgomesp** [comment]
I believe we can close this issue now.

**Comment by vanillajonathan** [comment]
Yeah, unless we keep it open until both PRs are merged.
