### ISSUE TITLE
Avatar placeholder

### ISSUE THREAD

**Issue by razzeee** [flathub/website#1366]
We're currently accessing ` auth.avatar` but there might be providers, that don't give us an avatar.

So we will need a fallback image or some kind of library to generate an avatar based on something.

**Comment by CharlExMachina** [comment]
Could something like [boring avatars](https://github.com/boringdesigners/boring-avatars) work as a fallback avatar generator? It generates random avatars based on the username, it also has different types of avatars like these:

**Beam**
![image](https://user-images.githubusercontent.com/23466083/233818145-1125135f-d8b6-4b64-a109-9262494d23cd.png)

**Pixel**
![image](https://user-images.githubusercontent.com/23466083/233818166-85f8e3ce-206f-4436-b84d-08e864759115.png)

**Marble**
![image](https://user-images.githubusercontent.com/23466083/233818174-0468da97-18a6-4be6-8bed-a9cde8af30f4.png)

And others

**Comment by razzeee** [comment]
yes, that's exactly what we need to do. important is, that they get generated locally and it doesn't ask another server/website for avatars.

we have logs, showing this problem, but it might be nice if someone could check in the database to see if this case actually happens (needs to be @barthalion )

**Comment by CharlExMachina** [comment]
> yes, that's exactly what we need to do. important is, that they get generated locally and it doesn't ask another server/website for avatars.
> 
> we have logs, showing this problem, but it might be nice if someone could check in the database to see if this case actually happens (needs to be @barthalion )

Yes, the library generated them fully locally, so it'll work cool to solve this problem, if it actually happens.

**Comment by barthalion** [comment]
Yeah, I think the avatar attribute can be null if someone hasn't set up an avatar in the login provider. Had this with KDE GitLab.
