### ISSUE TITLE
Verified Checkmark and Text only in Search Results for Evolution

### ISSUE THREAD

**Issue by julianschacher** [flathub/website#1371]
For Evolution the verified checkmark and text only show in the search results, but not on its actual page.

Search results:
![image](https://user-images.githubusercontent.com/26492670/233821470-b5264a03-77c6-4fa9-8804-a3e54cddfeaf.png)
Evolutions page:
![image](https://user-images.githubusercontent.com/26492670/233821524-5b959b94-4d4f-4c7f-95cc-c0c3059e6846.png)

This issue seems to be somewhat Evolution-specific as for other apps the page shows the verified checkmark and text.

**Comment by razzeee** [comment]
Should be fine now, but some other apps still have this and will need a rebuild before showing correctly.

**Comment by julianschacher** [comment]
Nice! Now Evolutions page shows the badge.

Now I'm wondering about another kinda-related thing however: The badge in the search results is different from the badge on the page, while for other applications this isn't the case. Is this intended?

**Comment by razzeee** [comment]
It's not intended, but we'll probably live with that until somebody has time to sort it out.

They hit different parts of the backend, but that's needed in some cases.

**Comment by razzeee** [comment]
Anyway they should mostly match, unless an app needs a rebuild, if you have App ids we can check

**Comment by julianschacher** [comment]
I don't know of any more apps with missing checkmarks.
So yeah, I guess the main issue I opened this issue for is fixed, so feel free to close this issue or leave it open for tracking the other small thing I asked about.
