### ISSUE TITLE
Gitlab login broken

### ISSUE THREAD

**Issue by Doomsdayrs** [flathub/website#1379]
## Description

`Login with GitLab` leads to the following error message.
```
The requested scope is invalid, unknown, or malformed.
```

![image](https://user-images.githubusercontent.com/38189170/233867676-288dc66f-3c3c-4fd4-b0d3-c7aca000a55b.png)

A possible repeat of #817 ?

**Comment by razzeee** [comment]
I kind of think the app we're using over at gitlab still points to the beta page. Probably was forgotten when we switched to live.

**Comment by barthalion** [comment]
This should be fixed now. Can you try again?

**Comment by dtsudo** [comment]
It wasn't working for me over the weekend but it does work now, so at least for me, this is fixed now. Thanks!
