### ISSUE TITLE
Incorrect app groups

### ISSUE THREAD

**Issue by TobiasFella** [flathub/website#1382]
E.g. https://flathub.org/apps/com.adobe.Reader mentions "other apps in the KDE group, implying that the adobe reader is made by KDE. 

Looking at https://flathub.org/apps/collection/project-group/KDE/1 it is also listed there, alongside some other apps that are also not related to KDE

**Comment by razzeee** [comment]
Closing as duplicate of https://github.com/flathub/website/issues/1356
