### ISSUE TITLE
Open hamburger menu messes up large website view

### ISSUE THREAD

**Issue by ThomasFrans** [flathub/website#1413]
When leaving the hamburger menu open and going from the small mobile view into the larger view (through the developer mobile tools on Firefox), the website's content is gone. It could be that this really doesn't matter as few people will ever encounter this, but just thought I'd create an issue for it which can be closed in case this isn't worth fixing. The only real life scenario where I could see this happen is on a mobile device with a significant difference between its landscape and portrait layout.

## How to reproduce
1. Open the mobile developer tool in the browser (ctrl+shift+m on Firefox)
2. Make the screen small enough to trigger the smallest version of the website
3. Open the hamburger menu
4. With the hamburger menu open, drag the site to the largest version again

The content of the site is now gone.

**Comment by razzeee** [comment]
I know of that problem, but it's good, that it's tracked now
