### ISSUE TITLE
Site goes blank after login with GitHub (Firefox)

### ISSUE THREAD

**Issue by Flatbread1** [flathub/website#1415]
After logging into the Flathub webiste (via the homepage) and using GitHub Authentication, the site goes completely blank after a half a second, only showing the background color. This not only applies to the home page, but also application pages (like HandBrake, which was used to apply the below GIF)

System Information:
Fedora 38
KDE Plasma 5.27 (X11, also applies to Wayland sessions)
Firefox Browser v112.0.1 (64-bit)
Extensions - Plasma Integration, Dark Reader, uBlock Origin (neither of these affect the site)

Site was working as expected before an attempt to login.

EXPECTED RESULT:  Site loads normally, allowing the user to select and install apps from Flathub.

ACTUAL RESULT: Site shows content as normal, but for only a half-second, rendering it unusable, forcing the user to install flatpaks via terminal or through KDE Discover instead.

Example (Home Page): 
![2023-04-29 Flathub-Login-Blank-Site](https://user-images.githubusercontent.com/119143145/235328534-aaa823b7-4e4b-401b-9a9d-52e739cc1030.gif)

**Comment by razzeee** [comment]
Unfortunatly your gif seems broken

**Comment by Bha-Gu** [comment]
`Content Security Policy: Couldn’t process unknown directive ‘prefetch-src’ --------- flathub.org`

`Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).-------- index.js:6054:26`

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://o467221.ingest.sentry.io/api/6610580/envelope/?sentry_key=b512f563700847e787e978ae1c15133c&sentry_version=7&sentry_client=sentry.javascript.nextjs%2F7.49.0. (Reason: CORS request did not succeed). Status code: (null).`

`Loading failed for the <script> with source “https://webstats.gnome.org/matomo.js”.-------- flathub.org:1:1`

`TypeError: e is null
    NextJS 30
    NextJS 30
-------------------- _app-ebb7693c959b9324.js:11:2315`

`A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred ----------------------------- _app-ebb7693c959b9324.js:11:2315`

`Error rendering page:  TypeError: NetworkError when attempting to fetch resource. ---------------------------- _app-ebb7693c959b9324.js:11:2315`

Then the next message on repeat

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://o467221.ingest.sentry.io/api/6610580/envelope/?sentry_key=b512f563700847e787e978ae1c15133c&sentry_version=7&sentry_client=sentry.javascript.nextjs%2F7.49.0. (Reason: CORS request did not succeed). Status code: (null).`

These are the console log i got

System Information:-
OS:- Pop!_OS 22.04 LTS
DE:- GNOME 42.5
Firefox:- 112.0.2 (64-bit) [Flatpak]
Extensions:- Bitwarden, Ublock Origin, Dark Reader

turning extentions on or off has no significant effect

With ublock on site does not  tell me to look at the console log

EXPECTED RESULT: Site loads normally, allowing the user to select and install apps from Flathub.

ACTUAL RESULT: Site shows content as normal, but for only a half-second, rendering it unusable, forcing the user to install flatpaks via terminal or through KDE Discover instead.

![image](https://user-images.githubusercontent.com/67630917/235333130-212b62d7-4c96-4791-a6a1-cc8e134783d7.png)

**Comment by Bha-Gu** [comment]
> `Content Security Policy: Couldn’t process unknown directive ‘prefetch-src’ --------- flathub.org`
> 
> `Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).-------- index.js:6054:26`
> 
> `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://o467221.ingest.sentry.io/api/6610580/envelope/?sentry_key=b512f563700847e787e978ae1c15133c&sentry_version=7&sentry_client=sentry.javascript.nextjs%2F7.49.0. (Reason: CORS request did not succeed). Status code: (null).`
> 
> `Loading failed for the <script> with source “https://webstats.gnome.org/matomo.js”.-------- flathub.org:1:1`
> 
> `TypeError: e is null NextJS 30 NextJS 30 -------------------- _app-ebb7693c959b9324.js:11:2315`
> 
> `A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred ----------------------------- _app-ebb7693c959b9324.js:11:2315`
> 
> `Error rendering page: TypeError: NetworkError when attempting to fetch resource. ---------------------------- _app-ebb7693c959b9324.js:11:2315`
> 
> Then the next message on repeat
> 
> `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://o467221.ingest.sentry.io/api/6610580/envelope/?sentry_key=b512f563700847e787e978ae1c15133c&sentry_version=7&sentry_client=sentry.javascript.nextjs%2F7.49.0. (Reason: CORS request did not succeed). Status code: (null).`
> 
> These are the console log i got
> 

Console log seem to be in a semi random order but they are still the same

**Comment by razzeee** [comment]
That's happening on page entry not on trying to login?

**Comment by Flatbread1** [comment]
> That's happening on page entry not on trying to login?
> 
> What language is your browser/system set to?

Just US English. And it works only if I'm not logged in. When I log in, it breaks.

**Comment by DeedleFake** [comment]
I'm having the exact same issue here in both Firefox _and_ Chromium. It worked perfectly fine as `beta.flathub.org`, which makes me think that it's probably a config error of some kind.

**Comment by razzeee** [comment]
What are you logging in with?

**Comment by DeedleFake** [comment]
Whatever this problem was, it seems to have been resolved for me. Everything seems to be working fine now in both Firefox and Chromium.

**Comment by Flatbread1** [comment]
> What are you logging in with?

GitHub

**Comment by razzeee** [comment]
Can you try again?

**Comment by Flatbread1** [comment]
> 

Testing in Firefox (latest) on Windows works just fine. About to test on Linux (RebornOS/Arch)

**Comment by Flatbread1** [comment]
> Can you try again?

Yep, works just fine in Linux, it got fixed. Closing this Issue.
