### ISSUE TITLE
(BACKEND) Swagger and Redoc not able to find openapi.json

### ISSUE THREAD

**Issue by ananyo141** [flathub/website#1417]
## URL Mismatch
The OpenAPI documentation for the backend can't be viewed using the following urls:
**ReDoc**: `https://flathub.org/api/v2/redoc`
**Swagger**: `https://flathub.org/api/v2/docs`

Both of them complain about _404 resource not found_ error, trying to load url `https://flathub.org/openapi.json`, whereas actual schema file is at `https://flathub.org/api/v2/openapi.json`.

**Comment by razzeee** [comment]
Should be working now
