### ISSUE TITLE
Looking for help with translations

### ISSUE THREAD

**Issue by razzeee** [flathub/website#1419]
There are currently two people with weblate rights. @ramcq and me. Usually there is not much to do, but we could probably be better.

E.g. provide translators with Screenshots etc.

So some people helping out would be nice.

**Comment by razzeee** [comment]
I'm wrong it's not robert, it's neil also beeing admin. I need to add more people like @barthalion and maybe @ramcq if they can confirm that they have an account, just in case I get hit by a bus.

**Comment by razzeee** [comment]
Added more people and started adding screenshots. People that actually want to work on this would still be nice, but I will close this issue for now.

**Comment by kbdharun** [comment]
Hi, just now stumbled on this issue. I am interested in helping out with managing translations (and adding screenshots) if you are looking for more people. (Id. https://hosted.weblate.org/user/kbdharunkrishna/)

**Comment by razzeee** [comment]
@kbdharun you should have rights to add screenshots now, let me know if you need more

**Comment by Ikkevoid** [comment]
Hello @razzeee  if the projects needs any additional assistance, please don't hesitate to reach out.
https://hosted.weblate.org/user/Ikkevoid/

**Comment by razzeee** [comment]
Thanks @Ikkevoid I've added you to the screenshot team now
