### ISSUE TITLE
New siteś Dark Mode not enabling on Chromium based browsers

### ISSUE THREAD

**Issue by msmafra** [flathub/website#1421]
I tested with Firefox, Librewolf, Chromium and Brave
![Captura de tela de 2023-04-30 10-03-43](https://user-images.githubusercontent.com/1005457/235354388-78b779a4-2ff2-4543-987b-57bb1811ed90.png)

**Comment by razzeee** [comment]
That's probably your distro not correctly setting the theme. Firefox on gnome switches to it fine. Chromium seems to still lack behind https://www.omgubuntu.co.uk/2023/04/google-chrome-114-will-respect-dark-mode-on-linux

**Comment by razzeee** [comment]
I will close this, as we can't do much - other then wait.

**Comment by Francewhoa** [comment]
For those facing a challenge with your browser or other browser not automatically detecting your OS theme for flathub.org or other websites. I suggest this free and open source add-on. Which is both free and Libre Source (Open Source) at https://darkreader.org

**Comment by msmafra** [comment]
I already use it for years. Most of the time is much better than the dark modes provided, mainly because of them using white instead of a grey when "inverting" the colours. At least for me to not have text burned on my eyes for an hour, Grey on Darker Grey/Color works better than white on black.
