### ISSUE TITLE
[Fix] The boxes in the ListBox component may have different heights

### ISSUE THREAD

**Issue by Danielgomesp** [flathub/website#1423]
If the box has no content, it shows only the title and the box doesn't take all the available height.

**Steps to reproduce**
- Access an app detail (in this example, I'm using [Google Chrome page](https://flathub.org/apps/com.google.Chrome))
- View the ListBox component
- If any of the boxes has no content, it will not take the full height (usually the "Available Architectures" box)

![image](https://user-images.githubusercontent.com/12714730/235355010-4ee9267a-b8c1-4d93-bf8d-e1a91ead3b72.png)
![image](https://user-images.githubusercontent.com/12714730/235355032-86e1c8b9-65b1-4077-8fa7-f49ab733d0eb.png)

I've been thinking about two possible solutions:

1. If there is no content to show, don't show the box. i.e. the "Available Architectures" would not appear unless there is content to show.
2. Show the box taking all the available heights in order to maintain the layout consistency.

The second approach would look like this:
![image](https://user-images.githubusercontent.com/12714730/235355800-b06601ae-fdf8-4760-b717-76a2cd708565.png)

**Comment by razzeee** [comment]
There is no value in having that tile, when it's bugging like that, as it shows no information. I'm not sure why the backend thinks there are no architectures, but when I just checked, they are still there.

**Comment by razzeee** [comment]
Looking back at https://github.com/flathub/website/issues/1262 it should be hiding itself, when it's empty. So maybe it's not exactly empty?

**Comment by Danielgomesp** [comment]
Yea, it seems to solve the problem in a good way, but I don't see this code in the main branch. Is this merged?

**Comment by razzeee** [comment]
It has been, if it's not, it has been reverted by mistake IMO

**Comment by razzeee** [comment]
Yeah, I seem to have resolved wrong here https://github.com/flathub/website/commit/788be987bf02947ccc1efeffe0f8fa1158b4a72e

**Comment by Danielgomesp** [comment]
Great! So we found the solution. :)

**Comment by razzeee** [comment]
I still would like to hunt down the root cause

**Comment by razzeee** [comment]
https://github.com/flathub/website/pull/1433 might help to not break the ui site, but we need to keep an eye on it. I will create an issue for the backend I think.
