### ISSUE TITLE
Application in list taking too much space

### ISSUE THREAD

**Issue by matbme** [flathub/website#1474]
When an application description is too big it increases the height of its container, breaking the application grid.

![image](https://github.com/flathub/website/assets/48367298/abc5474c-effe-459b-aaf8-90525da0a488)

Can reproduce in Firefox 113 and GNOME Web 44.2.

**Comment by razzeee** [comment]
Seems like the line clamping here isn't working anymore https://github.com/flathub/website/blob/main/frontend/src/components/application/ApplicationCard.tsx#L64-L65
