### ISSUE TITLE
"Tags" should not be displayed as per the Desktop Entry specification

### ISSUE THREAD

**Issue by kra-mo** [flathub/website#1476]
The [Desktop Entry spec](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html) for the "Keywords" entry states the following:
> The values are not meant for display

For many applications, these values are inconsistently capitalized, and as such they should probably not be displayed on the website.

At the very least, they should be displayed in all-caps, so we avoid having `gnome`, `Gnome` and `GNOME`.

**Comment by razzeee** [comment]
Uppercasing should be something we can do.

Not displaying them is not really an option as far as I know. As if you want them to enable searching, we have no other way to expose them to search engines (outside of our own search)
