### ISSUE TITLE
Some UX issues related with new website

### ISSUE THREAD

**Issue by n3storm** [flathub/website#1515]
Huge distance between screenshot image and arrows to change: do not help discover features (Desktop)

Clicking on image do not zoom: Unexpected. zoom button is a far away.  (Desktop and Mobile)

Buttons do not behave as buttons. No consistency. (Desktop and Mobile)
![imagen](https://github.com/flathub/website/assets/220748/f64d0d11-4d7d-4f6d-9feb-f803a2124bac) 

Above, only green areas are clickable but all buttons/panes look the same.

**Comment by razzeee** [comment]
Closing, as this is too much of a meta issue and very unlikely to ever get solved like this.

Please split these up, as it's also very hard to reason about these with three topics at once.
