### ISSUE TITLE
Clicking on image do not zoom: Unexpected. zoom button is a far away. (Desktop and Mobile)

### ISSUE THREAD

**Issue by n3storm** [flathub/website#1525]
Each image should be clickable to zoom in, is expecte behaviour at any application screenshots gallery.

![imagen](https://github.com/flathub/website/assets/220748/5cb5716c-cc1c-42da-b4be-f5c2a30df1fd)

Zoom button is small and far away from image (breaks Fitts law)

Google Play example
![Uploading imagen.png…]()

Same with Snaps
https://snapcraft.io/libreoffice

https://www.softpedia.com

**Comment by razzeee** [comment]
I still think we should have the button, if for accessibility only

**Comment by n3storm** [comment]
For visually impaired users they don't need a zoom button at all

**Comment by razzeee** [comment]
You can now zoom by clicking on images. Also seems to work fine with scrolling through.
