### ISSUE TITLE
Titlebar shows `{{query}}`; should it show `MMEX`? 

### ISSUE THREAD

**Issue by ovari** [flathub/website#1540]
1. Enter https://flathub.org/apps/search?q=mmex into the web-browser addressbar
2. Titlebar shows `{{query}}`; should it show `MMEX`? 

![image](https://github.com/flathub/website/assets/17465872/cdff7cf2-f5e6-4422-91e4-9fa7963b17a7)

Thank you

**Comment by TheKrafter** [comment]
+1
The page title on the search page shows the placeholder `{{query}}` instead of the actual query.
