### ISSUE TITLE
Screenshots are not shown

### ISSUE THREAD

**Issue by gameonlnx** [flathub/website#1570]
Screenshots and images of some applications are not shown if app. stores are used for Flatpak applications.

Examples:
https://flathub.org/tr/apps/io.bassi.Amberol
https://flathub.org/tr/apps/io.github.hakandundar34coding.system-monitoring-center
https://flathub.org/tr/apps/org.upscayl.Upscayl

**Comment by razzeee** [comment]
Those all show fine for me, did you maybe run into old caches?
