### ISSUE TITLE
[Feature Request]: Make install button show flatpak install command

### ISSUE THREAD

**Issue by SISheogorath** [flathub/website#1571]
I would love it, when the "Manual install"-section from the bottom of the page, would become a drop-down for the Install button, like the `Clone` button works on GitHub or GitLab.

<details>
<summary>Story time!</summary>
<p>It might be just a me-problem, so feel free to drop this, but I find myself clicking the install button and downloading the <code>.flatpakref</code>-file more often than I like. For some reason I keep being under the illusion the install button would work like the clone button here on GitHub, opening a drop down with a handy snippet to copy.</p>

<p>Yet, I always end up with an unintended download, before scrolling down, copying the command from the manual install section and installing the application I want, while GNOME software is still counting something… maybe the stars in the galaxy.  I don't know, it takes ages and it just makes the current install button behaviour useless for me.</p>
</details>

**Comment by razzeee** [comment]
Did you report that to gnome software?

**Comment by SISheogorath** [comment]
I mean, not myself, but it seems that a sufficient amount of people have tried, with limited success:

https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1894
https://gitlab.gnome.org/GNOME/gnome-software/-/issues/1962

And to be completely honest, I don't know any other behaviour of GNOME Software. (Therefore I accepted it as it is. I can work around it quite well.)

**Comment by razzeee** [comment]
Made this to play with it, not sure if we will land this.

![image](https://github.com/flathub/website/assets/5943908/1a9f8d97-7ed5-4773-ad61-f2e6be2adc63)

**Comment by SISheogorath** [comment]
That looks pretty much like what I imagined. Would get full approval from me, but maybe more people have an opinion on it :)

**Comment by barthalion** [comment]
LGTM
