### ISSUE TITLE
Search is case sensitive

### ISSUE THREAD

**Issue by mjourdan** [flathub/website#1581]
Looking for "freecad" returns no result:

![image](https://github.com/flathub/website/assets/5346620/3bee3582-f998-416d-98a0-68ed43a03dfd)

On the contrary, looking for "FreeCAD" with the official app name casing returns (too many) results:

![image](https://github.com/flathub/website/assets/5346620/1f46e0cf-12cc-4929-9d3b-a73ed73810f0)

Searching for just "cad" does return a reasonable amount of results, including FreeCAD, but seems to do so based on metadata rather than app names:

![image](https://github.com/flathub/website/assets/5346620/63216a0b-3880-43f0-9f96-143572864444)

I would expect the search to ignore case sensitivity, and to show matching app names before matching metadata.

Cheers!

**Comment by razzeee** [comment]
This seems to be caused by meilisearch regressing with version 1.2.0

I can reproduce this locally in docker and it's not happening with 1.1.1

**Comment by razzeee** [comment]
Upstream said to wait for the next major release...
https://github.com/meilisearch/meilisearch/discussions/3831#discussioncomment-6163539

**Comment by razzeee** [comment]
We've updated to the latest version and it's back working.
