### ISSUE TITLE
Badges are scaled by default

### ISSUE THREAD

**Issue by cassidyjames** [flathub/website#1595]
Right now the PNGs and SVGs for the badges are provided at 300px (or 299px in some cases?) wide, but we recommend (in the code samples) scaling them to 240px wide.

We should provide the assets at a more appropriate size by default:

- 240px for PNG
  - Possibly 480px for 2x/HiDPI scaling
- 240px wide for SVG to not need to explicitly scale client-side

**Comment by cassidyjames** [comment]
I guess I should confirm with @jimmac what the intended display size is, so we can be sure to provide the right scaling ootb.

**Comment by jimmac** [comment]
I've kept the previous sizing, but don't really recall the initial requirements :/.

**Comment by razzeee** [comment]
Well they seem to have been 600x200 before, which is even worse?

https://github.com/flathub/website/commit/dd1b29ef9587f15b18c57503adcf72709ed6811b

**Comment by jimmac** [comment]
So what's the recommendation? I'm seeing the ios app store buttons at 160x54px, while Google play buttons seem to be 153x45px nominal. 

I wouldn't be too hung up on the size. While it's a single button on a page in most cases, the moment an app author needs to present a number of buttons side by side, there needs to be explicit unifying sizing put in place by them.

**Comment by razzeee** [comment]
I guess we have two options:

1. Old sizes - align the new graphics
2. New sizes - align the website code snippet (won't update for people already using the old snippet)

**Comment by jimmac** [comment]
Right now the buttons' nominal size is 300x100px, which only seems appropriate for HiDPI screens. But it's what you refer to as "old sizes" as far as I can tell. I'll happily scale them down to 240x80px.
