### ISSUE TITLE
backend: Rethink "newly added" list

### ISSUE THREAD

**Issue by barthalion** [flathub/website#1636]
The current logic for detecting which apps are new is not working great and in the past few weeks I've had to manually add IDs to new_apps_zset.

https://github.com/flathub/website/blob/main/backend/app/worker.py#L59

One idea is to record "first seen" value in redis for each ID, then update the new_apps_zset key on every `POST /update`.

**Comment by razzeee** [comment]
I guess we could also just default to `date.now` or whatever it is in python, instead of falling back to `0`
