### ISSUE TITLE
Broken link on Steam page

### ISSUE THREAD

**Issue by chrisawi** [flathub/website#1648]
On https://flathub.org/apps/com.valvesoftware.Steam, the link to Steam Link in the "Other apps by Valve Corporation" section leads to a 404 error page.

The URL appears correct, and it opens after reloading the page.

**Comment by razzeee** [comment]
Opening Gnome Network Display from here seems to trigger this too

https://flathub.org/apps/search?q=gnome

**Comment by JakobDev** [comment]
The Page for com.valvesoftware.SteamLink don't exists for some reason. No matter how you open it.

**Comment by razzeee** [comment]
If you just refresh on that page it works.

Seems to somehow not have been build server side? If you inspect the prearation calls on the site your coming from, you can see, that the json request 404s for that app.

**Comment by razzeee** [comment]
Phew, seems to be gone again, after the latest changes. At least I can't find a case anymore.
