### ISSUE TITLE
Allow following publishers.

### ISSUE THREAD

**Issue by rokejulianlockhart** [flathub/website#1655]
https://forum.snapcraft.io/t/allow-following-publishers/35875?u=beedellrokejulianloc

<blockquote>

One of the things that annoys me about the Google Play Store, F-Droid, and the Microsoft Store is how I can't be notified when a publisher that I use the apps of publishes a new package. I'd like [[https://flathub.org](https://flathub.org)] to be the first to allow this, so that, for instance, I can follow https://snapcraft.io/publisher/mycroft-devs to know if they happen to publish `mycroft-core` as a snap package.

Although this could be done via a web interface (badly) or e-mail, I believe that ActivityPub would be best, since it would remove the need for an e-mail server and allow the user to get either e-mail notifications via whatever ActivityPub client they use, or view them in a more current manner. RSS would even work if that's all too much effort, although I think ActivityPub would be great.

https://codeberg.org/libre-menu-editor demonstrates a brilliant GUI for this:

![image](https://github.com/flathub/website/assets/42837531/e0cbdc8f-ad56-4c51-a6e2-ad8d68a1db19)

</blockquote>

My request here is twofold, because as https://github.com/flathub/website/issues/1656#issue-1790291097 demonstrates, https://Flathub.org currently doesn't support viewing the apps that a publisher has published in a unified manner, so that appears rather to be a prerequisite to this, although not fundamentally so.

**Comment by razzeee** [comment]
I'm sorry, but I don't think this would be a sane use of our time. It's not happening frequently enough and it probably won't happen significantly more frequently. There are also other problems.

**Comment by rokejulianlockhart** [comment]
@razzeee, then close as not planned rather than completed.
