### ISSUE TITLE
Always show publisher, regardless of how many apps have been published by them.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [flathub/website#1656]
At https://snapcraft.io/blender, I can click the publisher's name and see its published apps

![image](https://github.com/flathub/website/assets/42837531/5f0dc939-7804-4042-81ea-fc70a8302b00)

https://snapcraft.io/publisher/blenderfoundation

![image](https://github.com/flathub/website/assets/42837531/83c8c4b9-acda-4826-9589-b2790ab3bbb2)

whereas https://flathub.org/apps/page.codeberg.libre_menu_editor.LibreMenuEditor doesn't despite stating who/what the publisher is

![image](https://github.com/flathub/website/assets/42837531/28fa637f-7ef8-465c-bb4c-154c453b94d6)

and Blender in https://flathub.org/apps/org.blender.Blender doesn't even show a publisher!

![image](https://github.com/flathub/website/assets/42837531/bb752d18-1ce0-488c-bd56-cd6cf8bc6fc0)

**Comment by JakobDev** [comment]
> At https://snapcraft.io/blender, I can click the publisher's name and see its published apps

You can do this on Flathub as well. If the same Publisher has more Apps you can see all others. Take for [Gedit](https://flathub.org/apps/org.gnome.gedit), which is a Gnome App.

> whereas https://flathub.org/apps/page.codeberg.libre_menu_editor.LibreMenuEditor doesn't despite stating who/what the publisher is

The Publisher is [libre-menu-editor](https://codeberg.org/libre-menu-editor). I don't know why he uses his App Name as Username.

> and Blender in https://flathub.org/apps/org.blender.Blender doesn't even show a publisher!

This is an Issue with the Blender Flatpak

**Comment by razzeee** [comment]
We actually create the pages for these for e.g. https://flathub.org/apps/collection/developer/libre-menu-editor/1

But as approximatly 98% of devs only have one app right now, it's really not that useful at all and would only waste space/confuse users. IMO.

**Comment by rokejulianlockhart** [comment]
@razzeee, how would exposing this confuse them? Every other app store does it and I've never even heard it mentioned.

**Comment by razzeee** [comment]
You want to guide people and don't show them useless stuff as it might lead them to exit the page.

Looking at how the playstore does it, it's pretty clear to me, that they have designed themselves into a corner at some point. There seems to be a new way that developers that have some kind of account are listed in, which is nice, with description and all. And there is the other (presumably) legacy way, where they have just a list with no explanation and a confusing search term.

We don't have the means to do the good version of it, we don't have descriptions for developers. This might improve over time, but right now we almost only have what's in appstream, which is just a string, where anybody can set anything.

**Comment by razzeee** [comment]
I'll close this, as we can't do anything meaningful here

**Comment by aiqc** [comment]
I was delighted when I stumbled upon boxes by gnome.

It made me wonder, what other apps might gnome have available on flathub? However, clicking on their name brought me to an independent homepage unrelated to flathub.

It would be nice if clicking on their name went to a page for the author. The link to their independent homepage could be within that page.

![Screen Shot 2024-01-15 at 10 46 51 AM](https://github.com/flathub-infra/website/assets/74990642/23f56e50-f011-4b84-89e8-c0917fe59a97)

**Comment by razzeee** [comment]
you would want to click the `by The GNOME Project` as that's the author information. The latter is verification specific and doesn't exist for most apps.

**Comment by razzeee** [comment]
It's not really the name, there are some custom rules for KDE and Gnome to prettify it for them, but otherwise it's an url.

![image](https://github.com/flathub-infra/website/assets/5943908/d31b8096-9435-47c7-b1f0-2b9d615b9ead)

Or a text hinting at a source code provider 

![image](https://github.com/flathub-infra/website/assets/5943908/0eba059b-d8d3-4ac6-ab6b-afb2f3071c15)

**Comment by RokeJulianLockhart** [comment]
Doesn't https://github.com/flathub-infra/website/issues/1656#issuecomment-1892425862 seem like a separate issue, @razzeee and @aiqc?

**Comment by razzeee** [comment]
I think it's 50/50

1. this asks for the same link the comment asks for
2. the comment also wants to cleanup confusion with the verification display, that's a different issue
