### ISSUE TITLE
May I add Chinese for Flathub Badge？

### ISSUE THREAD

**Issue by Songyon** [flathub/website#1660]
Your Badge is only available in English. Can you share the source files so that everyone can create versions in other languages and PR them? I want to modify the source file to generate a Chinese version of Badge.

**Comment by Songyon** [comment]
I think I need to @jimmac .

**Comment by razzeee** [comment]
The other problem is, that we host the badges on the CDN, which I/this repo has no access to. So we will need an infra person later :)

See https://github.com/flathub/website/issues/284 in addition

**Comment by Songyon** [comment]
> The other problem is, that we host the badges on the CDN, which I/this repo has no access to. So we will need an infra person later :)
> 
> See https://github.com/flathub/website/issues/284 in addition
> 
> 

This is too bad. Does this mean that outsiders cannot make localized contributions to your badge? It's really a pity that Flathub has various languages but no badges.

**Comment by razzeee** [comment]
I believe we can figure it out.

These are the svgs @jimmac created. I'm however not sure if they are the latest.

@jimmac @barthalion can we create a repo for this? `flathub/assets` to keep the latest versions in one easy to find place?

![download](https://github.com/flathub/website/assets/5943908/8a8c67fc-9fe6-4a4f-817f-926ffe5ce3c1)
![download-i](https://github.com/flathub/website/assets/5943908/b81dc627-677c-48a3-ae90-8bdf5275af2d)

**Comment by Songyon** [comment]
> I believe we can figure it out.
> 
> These are the svgs @jimmac created. I'm however not sure if they are the latest.
> 
> @jimmac @barthalion can we create a repo for this? `flathub/assets` to keep the latest versions in one easy to find place?
> 
> ![download](https://github.com/flathub/website/assets/5943908/8a8c67fc-9fe6-4a4f-817f-926ffe5ce3c1)
> ![download-i](https://github.com/flathub/website/assets/5943908/b81dc627-677c-48a3-ae90-8bdf5275af2d)
> 

Thank you very much!

**Comment by razzeee** [comment]
I'll close this, as I would like to track this in https://github.com/flathub/website/issues/284 instead
