### ISSUE TITLE
Vary order of sections on the homepage

### ISSUE THREAD

**Issue by nedrichards** [flathub/website#17]
I'm open minded about the new order for sections on the homepage (where 'editors choice' goes at the top now). 

It was previously considered important that getting Firefox or an app tile that users *knew* on their first view was a good social proof that flathub was safe to use and relevant for the user. I'd be keen to vary this order and see what kinds of influence it may or may not have on the number of apps downloaded. It may be that flathub is now famous enough that highlighting 'hidden gems' works - although as previously mentioned in flathub/frontend#171 we may also need simultaneous improvements in our curatorial workflow.

**Comment by razzeee** [comment]
We significantly shuffled things around. I think we should just start out with this or have very specific issues, what we want to change.
