### ISSUE TITLE
Styling issues on GNOME Web

### ISSUE THREAD

**Issue by aadilayub** [flathub/website#1712]
There are a couple of issues on app pages on GNOME Web (I'm using GNOME Web 44.4):

1. App screenshots are overflowing the container
2. The gradient meant to truncate the app description is dark

----
URL: https://flathub.org/apps/com.github.cfcurtis.pdfstitcher

![PDF Stitcher | Flathub](https://github.com/flathub/website/assets/31581044/3d7aadc2-ed26-402d-b102-6a3a6299bd59)

**Comment by razzeee** [comment]
Images being off should be fixed by https://github.com/flathub/website/pull/1715

**Comment by razzeee** [comment]
Gradient bug should also be fixed by that.

There is still a bug in dark mode, where the logo is not in the correct color, but that's due to safari/web not imprementing that svg spec. Not sure how to fix that.

**Comment by aadilayub** [comment]
> There is still a bug in dark mode, where the logo is not in the correct color, but that's due to safari/web not imprementing that svg spec. Not sure how to fix that.

This is a hacky solution, but you could add `filter:invert` to the logo in dark mode 🤔. This would work in all browsers provided you remove the `prefers-color-scheme` media query that's already on the svg.

![image](https://github.com/flathub/website/assets/31581044/ac50c8d9-5454-4c33-904c-4386194970ce)

**Comment by razzeee** [comment]
Yeah, probably the best we can do right now. Let's hope that doesn't break other pages, showing our logo, like google search etc.

**Comment by aadilayub** [comment]
Technically it shouldn't, since those pages will be pulling in the image and not the css?

**Comment by razzeee** [comment]
Yes, but they might have gotten an image before, which would react on dark mode - which they now don't do anymore.
