### ISSUE TITLE
Screenshot zoom button shows a smaller screenshot

### ISSUE THREAD

**Issue by EmmanuelP** [flathub/website#1723]
On an application page, if you click on the zoom button (magnifier icon with a plus), the view switches to a fullscreen image viewer only to show a smaller screenshot:

![image](https://github.com/flathub/website/assets/136864/6bf5da85-3602-45f2-a16b-850cf900c44e)

![image](https://github.com/flathub/website/assets/136864/1c31c15f-1b8e-4a63-bec0-e0fe96a26c10)

I expect a native resolution image in the fullscreen viewer.

**Comment by razzeee** [comment]
This is unfortunatly not possible, until flathub uses libappstream as a backend. https://github.com/flathub/website/issues/37

**Comment by EmmanuelP** [comment]
It will be probably better to remove the zoom buttons until then.

**Comment by razzeee** [comment]
Closing in favor of #37
