### ISSUE TITLE
Alpine installation guide update 

### ISSUE THREAD

**Issue by JustPassingBy06** [flathub/website#1736]
The most recent version of alpine (3.18) and maybe versions before that, are able to install flatpaks using gnome-software as well as KDE-discover, using the following command:
apk add gnome-software-plugin-flatpak
or
apk add discover-backend-flatpak
also, sudo should probably be exchanged for doas as that is the elevation software included in the base installation.

**Comment by razzeee** [comment]
Please raise this issue over at https://github.com/flatpak/flatpak.github.io

Or send a PR changing https://github.com/flatpak/flatpak.github.io/blob/source/data/distro.yml#L368

**Comment by RyuKurisu** [comment]
@razzeee I'd like to make a pull request for all the issues mentioned by @JustPassingBy06.  So if this issue gets opened again, I don't need to file a new bug.

Thanks in advance.

**Comment by razzeee** [comment]
This does not need an action here, it needs to be changed in the other repo and then we can run the automatic import.
