### ISSUE TITLE
Logo is darkened on hover in dark mode

### ISSUE THREAD

**Issue by bertob** [flathub/website#1767]
The logo in the top bar has a darkened hover state, which is hard to see:

![image](https://github.com/flathub/website/assets/1908896/d9b4af8f-9cfe-44f8-8ac1-32c7b0b9d6e3)

Other top bar items have a light hover state, which is much more visible:

![image](https://github.com/flathub/website/assets/1908896/5b7f6069-3522-443b-9b5f-6ec744ead285)

**Comment by razzeee** [comment]
Yikes, that's caused by us inverting the logo color for browsers, that don't support svg color changes. Gnome Web/Safari.
