### ISSUE TITLE
Please make better responsiveness on mobile devices at homepage and account profile

### ISSUE THREAD

**Issue by vikdevelop** [flathub/website#179]
I attach screenshots below:

![Screenshot_2022-04-29-21-38-49-07_e4424258c8b8649f6e67d283a50a2cbc.jpg](https://user-images.githubusercontent.com/83600218/166058808-fe0d2676-12d2-470e-8a80-1e4b48cf2a25.jpg)
![Screenshot_2022-04-29-21-37-50-53_e4424258c8b8649f6e67d283a50a2cbc.jpg](https://user-images.githubusercontent.com/83600218/166058840-15090528-8209-4403-b209-187b60eb406f.jpg)

**Comment by razzeee** [comment]
Which resolution is that? Could also be a brave problem.

Here's Firefox on my device :
![Screenshot_20220429-233008_Firefox Nightly.png](https://user-images.githubusercontent.com/5943908/166071920-33e64706-8afd-45d5-85e5-8c0d15b9f3a4.png)
![Screenshot_20220429-233104_Firefox Nightly.png](https://user-images.githubusercontent.com/5943908/166071930-a9b96ab3-e3e9-48b2-a5ed-3670bd55c915.png)

The logged in pages haven't really seen design work, its more about functionality at the moment.

**Comment by razzeee** [comment]
Please check again, it should hopefully work better now due to https://github.com/flathub/website/pull/182 and https://github.com/flathub/website/pull/181

**Comment by vikdevelop** [comment]
> Please check again, it should hopefully work better now due to #182 and #181
It's already working well :+1:
