### ISSUE TITLE
Tighten and even up padding on the homepage

### ISSUE THREAD

**Issue by nedrichards** [flathub/website#18]
We need to tighten up and even out the padding and margins on the homepage between the top section, quick setup and the first app section. In particular to balance the needs of the user who doesn't yet know about flathub with the user looking for their first app.
![Screenshot from 2022-01-31 21-04-23](https://user-images.githubusercontent.com/302677/151872924-bd61b189-8b43-4c59-9bdb-dc3711ac3593.png)

**Comment by jimmac** [comment]
I'd add all caps and lack of vertical whitespace to the list of issues. I'll ponder an illustration to fill up the space on the right

**Comment by razzeee** [comment]
Do you mean the header or the button caps too?

I fully agree on the header, not sure about the buttons. But those would be the only place left, where we use uppercase, so probably time to get rid of it.

**Comment by jimmac** [comment]
>Do you mean the header or the button caps too?

Yes, let's leave all caps for the reddit comment section.

Perhaps something like this?

![flatphub-mockup](https://user-images.githubusercontent.com/14821/160427825-318e7fd3-3ee9-4ac6-8c43-26394a955b9f.png)

**Comment by jimmac** [comment]
Here's the illustration asset itself. Will probably need to be tweaked to work for the dark variant (or will need another variant and use <picture>).

![landing-page](https://user-images.githubusercontent.com/14821/162224608-b318e823-84ee-4d70-8c09-97e90407814a.svg)

**Comment by razzeee** [comment]
I'll close this, as I think it's addressed, but feel free to reopen.
