### ISSUE TITLE
Flatpak cannot run any GUI software

### ISSUE THREAD

**Issue by kenryuS** [flathub/website#1804]
For a while, I can't run any GUI software since three weeks ago.

I'm using Arch with Linux 6.4.10 and it complains about bubblewrap:

```
~ $ flatpak run com.github.tchx84.Flatseal
bwrap: Unexpected capabilities but not setuid, old file caps config?
error: Failed to sync with dbus proxy
```

I found out that this happens when I try to run any GUI applications like Discord or Unity Hub, but ***not in tty/pts mode without x11*** such as GNU Octave command line mode.

Here are some version info:

- flatpak: 1.15.4
- bwrap: 0.8.0
- dbus: 1.14.8

**Comment by razzeee** [comment]
You need to report this here https://github.com/flatpak/flatpak/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc there's nothing the website can do about this.
