### ISSUE TITLE
Translation of `Add-ons` and its popup

### ISSUE THREAD

**Issue by ovari** [flathub/website#1834]
Please allow translation of `Add-ons` and its popup.

![image](https://github.com/flathub/website/assets/17465872/5a9a1d30-1748-4936-bd0c-bac8a219b6fa)

https://flathub.org/hu/apps/com.github.unrud.djpdf

Thank you

**Comment by razzeee** [comment]
It's translatable probably, but weblate doesn't synced with the latest changes yet. Should happen automatically soon.
