### ISSUE TITLE
Safety rating inconsistent with GNOME Software 45

### ISSUE THREAD

**Issue by kra-mo** [flathub/website#1854]
Since [Software !1712](https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/1712), free software apps with huge sandbox holes are only classified as "Potentially Unsafe" and only proprietary apps are "Unsafe".

**Comment by kra-mo** [comment]
For reference

![image](https://github.com/flathub/website/assets/93832451/214519c0-fad7-4088-b48c-7de722e05280)

![image](https://github.com/flathub/website/assets/93832451/d80f8862-05ab-4c6b-861d-fca15d6bd108)

**Comment by razzeee** [comment]
First of all, it's not meant to be consistent.

But yes, seems like I missed https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/1712/diffs#4f70eda751616a96a3d0521c28a7cc39acaff30f_306_320 when updating it to that version.

**Comment by kra-mo** [comment]
Okay, I just assumed it was given how similar they are.

Regardless, potentially unsafe is probably better wording anyway.

**Comment by razzeee** [comment]
That wording is already in place, just not used in this case. `Unsafe` still exists, same as in gnome software.
