### ISSUE TITLE
App Links goes outside panel on Mobile

### ISSUE THREAD

**Issue by kbdharun** [flathub/website#1873]
![Screenshot_2023-08-30-19-21-51-772_com android chrome](https://github.com/flathub/website/assets/26346867/5e8f0671-26be-4a44-b451-ba5ee9cb1627)

**Comment by razzeee** [comment]
![image](https://github.com/flathub/website/assets/5943908/980c2ed9-56f8-482e-9430-a4bec4345b13)

Still seems fine, I guess it's an even smaller pixel width?

**Comment by kbdharun** [comment]
> ![image](https://github.com/flathub/website/assets/5943908/980c2ed9-56f8-482e-9430-a4bec4345b13)
> 
> Still seems fine, I guess it's an even smaller pixel width?

Just now checked again, can confirm it looks fine on Firefox but this issue does occur on Chrome (in mobile), was able to replicate this issue on multiple devices.

**Comment by RacerBG** [comment]
@razzeee I can confirm that all the issues which @kbdharun reported are reproducible with Redmi Note 12 Pro which have a resolution of 1080 x 2400 pixels, 20:9 ratio (~395 ppi density) with the latest version of Google Chrome.
