### ISSUE TITLE
Because the promise is made to "Get the latest versions of all your favorite apps" apps that are old wrt to the developer releases should be marked as so

### ISSUE THREAD

**Issue by callegar** [flathub/website#1878]
E.g. In the field where the version is provided (e.g. 9.0.0, also indicate the version autodiscovered from the developer github, e.g. 9.1.1, or the developer pr). Currently there are apps that are more than 1 year behind the current release. There may be reasons for this, but the user should be aware of installing an old version for which bug reports cannot be taken into account.

**Comment by razzeee** [comment]
There is no sane way to automate this, or it would have been used as the base of flatpak external data checker.

I will close this, as we will never be able to solve it.

**Comment by razzeee** [comment]
No, we can't assume, that there is a github repo for an app.
