### ISSUE TITLE
Better display of file permissions

### ISSUE THREAD

**Issue by JakobDev** [flathub/website#1884]
The currently display of the filesystem permission is kinda useless. It just tell you that a App can access some files, but not which. This doesn't help anyone. This don't tell e.g. if a App that can backup your Steam games has just access to your Steam directory or has also access to your .bashrc. It also doesn't differ between home and host permission. It shows in both cases that a App can access all your data.

**Comment by JakobDev** [comment]
> There's close to no difference between these two. 

The difference is, that `host` can access your drives while `home `can't. This is a big difference, when you get a malware that encrypt all of your files.

**Comment by razzeee** [comment]
This should be better now, if I understand your example correctly
