### ISSUE TITLE
Update Setup Flathub Distro Pages

### ISSUE THREAD

**Issue by RacerBG** [flathub/website#1887]
I looked through all the available distributions in the Flathub setup page and noticed the following issues:

For the Debian page:

1. Delete "_For Debian Jessie and Stretch, a flatpak package is available in the [official backports repository](https://backports.debian.org/Instructions/)._" because both Jessie and Stretch are no longer supported (they are in ELTS which is not official support).

2. Add information about the plasma-discover-backend-flatpak. For example:

"_If you are running KDE, it is also a good idea to install the Flatpak plugin for Discover. To do this, run:_"

      # apt install plasma-discover-backend-flatpak

For the Pisi GNU/Linux page:

The page just gives a 404 error.

Thanks in advance!

**Comment by razzeee** [comment]
Please report the content changes over at https://github.com/flatpak/flatpak.github.io
