### ISSUE TITLE
Website don't show Filesystem Permissions for jdMinecraftLauncher

### ISSUE THREAD

**Issue by JakobDev** [flathub/website#1899]
When viewing the Permissions of [jdMinecraftLauncher](https://flathub.org/apps/page.codeberg.JakobDev.jdMinecraftLauncher), you see this:
![grafik](https://github.com/flathub/website/assets/15185051/bd8629a2-60da-4956-bd51-2bf659a951bc)
So the Website says it has now Filesystem Permission. But when you look at [the Manifest](https://github.com/flathub/page.codeberg.JakobDev.jdMinecraftLauncher/blob/f32893bd657f6eeea75c0278667077fb2c96b350/page.codeberg.JakobDev.jdMinecraftLauncher.yaml) you'll see it has some:
```yaml
  - --filesystem=~/.minecraft:create
  - --filesystem=xdg-data/applications:create
  - --filesystem=xdg-desktop:create
```

**Comment by razzeee** [comment]
Probably the same cause as https://github.com/flathub/website/issues/1885#issuecomment-1703842938

**Comment by guihkx** [comment]
Maybe fixed now?

![image](https://github.com/flathub/website/assets/626206/66eca76d-e6fe-411f-a896-8d02c1584fe6)
