### ISSUE TITLE
Padding in manual install section feels inconsistent

### ISSUE THREAD

**Issue by nedrichards** [flathub/website#19]
![Screenshot from 2022-01-31 21-01-52](https://user-images.githubusercontent.com/302677/151872551-8c930bc0-3c63-4b64-8dbb-d7d676e36d4d.png)

The padding and margins in the manual install section seem perceptually inconsistent with different spacing between all the items and edges. More consistency would tighten things up (this may also be to do with the copy icon, so could be partially addressed in flathub/frontend#181 )

**Comment by razzeee** [comment]
Feel free to reopen this, I think I improved this at some point

**Comment by nedrichards** [comment]
Yes - this is improved. The copy icon itself seems a bit visually heavy towards the top but that's a separate issue.
