### ISSUE TITLE
Switching to second page in Authored apps does not work anymore

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/website#1907]
Switching to [second page](https://flathub.org/my-flathub?page=2) in the Authored apps list does not seem to do anything anymore - the list still stays on the first page.

**Comment by vrun1208** [comment]
Hi @AsciiWolf , can you provide screenshots or give more insights to the issue?

**Comment by AsciiWolf** [comment]
Sure, here's recording of the issue:

[recording.webm](https://github.com/flathub/website/assets/2339930/4dd152af-3b37-429b-a988-1a16322a1eca)
