### ISSUE TITLE
Permission dialog papercuts

### ISSUE THREAD

**Issue by bertob** [flathub/website#1913]
A few minor issues with this dialog:

- The title above the icon looks a bit odd, I'd move it below
- The icon at the top could be a bit larger
- I'd add a bit more vertical spacing above the list
- The close button styling could be nicer, I'd make it circular and use the default button style (light gray background and text-color X)

![image](https://github.com/flathub/website/assets/1908896/1fbcdf0b-4dae-42f4-8a19-032690b5b555)

**Comment by razzeee** [comment]
> * The title above the icon looks a bit odd, I'd move it below

I first implemented it like that, but as I made the modal to be a generic one, it seemed a bit weird to allow elements before the title. So I dropped that.

**Comment by RacerBG** [comment]
I would like to add that the dialog box should be wider because right now the close button obscures the text if it's longer:

![Screenshot 2023-09-07 at 16-28-35 DuckStation Flathub](https://github.com/flathub/website/assets/68707872/2ceccda3-7221-4a24-96e8-31026d522e17)

**Comment by razzeee** [comment]
wider isn't the correct approach, it needs to handle cases, when there is not enought space and just use multiple lines

**Comment by bertob** [comment]
> I first implemented it like that, but as I made the modal to be a generic one, it seemed a bit weird to allow elements before the title.

I mean, this is a special kind of dialog which always has an icon/pill thing at the top (it's the same for age ratings and device support, once we add those). Maybe just leave the dialog title to be empty, and add a different label below?

**Comment by razzeee** [comment]
> > I first implemented it like that, but as I made the modal to be a generic one, it seemed a bit weird to allow elements before the title.
> 
> I mean, this is a special kind of dialog which always has an icon/pill thing at the top (it's the same for age ratings and device support, once we add those). Maybe just leave the dialog title to be empty, and add a different label below?

Leaving title empty would break accessibility. I'll might be able to hack around it somehow, but trying to be transparent in case anyone wants to work on it before me.

**Comment by razzeee** [comment]
Should be better now

**Comment by bertob** [comment]
Looks better, but the spacing between title and list is a bit too large now. I'd reduce it by about half.

![image](https://github.com/flathub/website/assets/1908896/9360f0bb-3671-4eb2-ac93-3329645b84f9)

**Comment by razzeee** [comment]
Should be better soonish
