### ISSUE TITLE
License classification bug

### ISSUE THREAD

**Issue by hokonch** [flathub/website#1918]
I hate the Gnome Software-style safety rating and license info tiles.
One reason for this is that it associates open source with completely unrelated concepts such as software safety and community driven.
Aside from that, there is a bug on `flathub.org` that is not in Gnome Software, so I report it at first.
## Bug
https://github.com/flathub/website/blob/13b345dea9caa0c309dd5d0ce1ceceb0e8f235f5/frontend/src/components/application/LicenseInfo.tsx#L84-L85

https://docs.flathub.org/docs/for-app-authors/appdata-guidelines/#license
> All appdata must contain a valid [SPDX license](https://spdx.org/licenses/). However there isn't an SPDX license for proprietary software. By convention you should use LicenseRef-proprietary in this case.

The code and documentation is wrong.
The SPDX license primarily covers open source licenses, but also includes some commonly used non-free licenses, especially source-available licenses. 
See below for a list of software where this bug causes problems.  The funniest result can be found at https://flathub.org/ja/apps/io.itch.keyikedalube_ndang.Type-Off.
![Screenshot](https://github.com/flathub/website/assets/113707818/6958defa-979e-460d-8a52-b13c0145554d)

---
https://github.com/flathub/website/blob/13b345dea9caa0c309dd5d0ce1ceceb0e8f235f5/backend/app/apps.py#L42
There's no foolproof way to classify licenses as free or proprietary, but for now it's best to check `is_free_license`. (As will become clear below, there are several false positives due to upstream code issues.)

## (TODO)
~~~
// pseudo code
is_free_license == false
&&
app.project_license?.startsWith("LicenseRef-proprietary") == false
~~~

I don't have time to check for now, but probably worth investigating manually.

| app_id | project_license | Proprietary?|Auditable code? |Community built? |Error cause|
| ---- | ---- | ---- | ---- | ---- | ---- |
org.unknown_horizons.UnknownHorizons | APL-1.0 AND CC-BY-SA-3.0 AND GPL-2.0-with-font-exception AND MIT AND OFL-1.1||||
com.github.varnholt.dynablaster_revenge | CC-BY-NC-4.0||||
com.katawa_shoujo.KatawaShoujo | CC-BY-NC-ND-3.0||||
net.kubux.Muehle | CC-BY-NC-ND-3.0||||
com.github.scrivanolabs.scrivano | CC-BY-NC-ND-4.0||||
uk.co.electronstudio.ComicReaderUltimate | CC-BY-NC-ND-4.0||||
com.moddb.TotalChaos | CC-BY-NC-SA-3.0||||
com.moddb.TotalChaosRetro | CC-BY-NC-SA-3.0||||
com.realm667.Wolfenstein_Blade_of_Agony | CC-BY-NC-SA-3.0||||
com.scoutshonour.Digital | CC-BY-NC-SA-3.0||||
com.scoutshonour.dtipbijays | CC-BY-NC-SA-3.0||||
org.dupot.littleadventure | CC-BY-NC-SA-3.0||||
com.steamgriddb.SGDBoop | CC-BY-NC-SA-4.0||||
dev.stewlab.PortaWar | CC-BY-NC-SA-4.0||||
io.jor.bugdom | CC-BY-NC-SA-4.0||||
io.jor.mightymike | CC-BY-NC-SA-4.0||||
io.jor.nanosaur2 | CC-BY-NC-SA-4.0||||
io.jor.nanosaur | CC-BY-NC-SA-4.0||||
io.jor.ottomatic | CC-BY-NC-SA-4.0||||
org.standardnotes.standardnotes | CC-BY-NC-SA-4.0||||
com.serveftp.officefactoring | DOC||||
net.warsow.Warsow | GPL-2.0+ AND CC-BY-SA-4.0 AND CC-BY-ND-4.0||||
info.urbanterror.UrbanTerror | GPL-2.0+ AND LicenseRef-proprietary=https://www.urbanterror.info/support/202-quake-3-sdk/||||
org.bluej.BlueJ | GPL-2.0-with-classpath-exception||||
org.greenfoot.Greenfoot | GPL-2.0-with-classpath-exception||||
org.supertuxproject.SuperTux | GPL-3.0+ AND CC-BY-SA-2.0||||
io.github.endless_sky.endless_sky | GPL-3.0 AND GPL-2.0 AND CC-BY-SA-4.0 AND CC-BY-SA-3.0 AND CC-BY-4.0 AND CC-BY-3.0 AND CC-BY-2.0 AND CC0-1.0||||
jp.yvt.OpenSpades | GPL-3.0+ and LicenseRef-Proprietary=https://github.com/yvt/openspades-paks/blob/master/Nonfree/LICENSE.md||||
io.github.santiagocezar.maniatic-launcher | GPL-3.0 AND LicenseRef-RDSCLv2=https://github.com/Rubberduckycooly/RSDKv5-Decompilation/blob/master/LICENSE.md||||
org.hikounomizu.HikouNoMizu | GPL-3.0-only AND LAL-1.3 AND CC-BY-3.0 AND CC-BY-4.0 AND OFL-1.1||||
org.kde.kgeotag | GPL-3.0-only OR LicenseRef-KDE-Accepted-GPL||||
net.epson.epsonscan2 | LGPL-2.1 AND LicenseRef-proprietary=https://download.ebz.epson.net/dsc/du/02/eula/global/LINUX_EN.html||||
org.hdfgroup.HDFView | LicenseRef-1=https://github.com/HDFGroup/hdfview/blob/master/COPYING||||
com.inform7.IDE | LicenseRef-Compiler-InformLicense-EverthingElseGPL-3.0||||
io.itch.keyikedalube_ndang.Type-Off | LicenseRef-Proprietary||||
io.github.hurricangame.hurrican | MIT AND CC-BY-NC-4.0||||
com.mongodb.Compass | SSPL-1.0||||
com.redis.RedisInsight | SSPL-1.0||||
com.wings3d.WINGS | TCL||||
org.virtualxt.VirtualXT | zlib-acknowledgement||||
com.frogatto.Frogatto | Zlib AND CC-BY-3.0 AND LicenseRef-proprietary||||
net.cubers.assault.AssaultCube | Zlib AND LicenseRef-proprietary=https://assault.cubers.net/docs/license.html||||

**Comment by razzeee** [comment]
Thanks for bringing this to my attention

**Comment by hokonch** [comment]
My apologies, perhaps my report was inappropriate. I did not report a case incentive issue.

**Comment by hokonch** [comment]
@razzeee 
Could you please reopen the issue?
I may not be a good bug reporter, but I think it is at least clear that there are issues with the current implementation, for example, if you look into `net.epson.epsonscan2`.

**Comment by razzeee** [comment]
`net.epson.epsonscan2` does look good to me now
