### ISSUE TITLE
404 Error on Corese-Command Application Page in French Language Setting

### ISSUE THREAD

**Issue by remiceres** [flathub/website#1923]
Hello,

While browsing the Flathub website with the French language setting, I encountered a 404 error when trying to access the "Corese-Command" application page via the search functionality. Below are the detailed steps to reproduce the issue:

1. Set the Flathub website language to French.
2. Use the search function to find "Corese-Command." You can use this [link](https://flathub.org/fr/apps/search?q=Corese-Command) to get to the French search results directly.
3. Click on the "Corese-Command" application from the search results.

Following these steps leads to a 404 error page. Interestingly, this issue doesn't occur when accessing the application page directly through this [specific URL](https://flathub.org/fr/apps/fr.inria.corese.CoreseCommand), suggesting the problem might be with the internal linking on the Flathub website.

**Browser/OS**: I tested this issue on Fedora 38 and Windows 11 using browsers: Firefox, Chrome, and GNOME Web. The result was the same across all platforms and browsers.

Further observations:
- This issue seems to be isolated to the "Corese-Command" application when using the French language setting, as I have tested other applications and language settings without encountering this problem.
- Directly accessing the page through its specific URL is a current workaround.

I hope this information helps resolve the issue. Thank you for your attention to this matter.

Best regards

**Comment by hokonch** [comment]
I can reproduce it too.

Further observation: Disabling brotili compression makes the bug go away.

1. Open Firefox about:config
2. Change the value of `network.http.accept-encoding.secure` from `gzip, deflate, br` to `gzip, deflate`
3. Follow the steps reported by @remiceres

**Comment by razzeee** [comment]
Seems to be back working for now

**Comment by razzeee** [comment]
#1931 tracks a permanent fix
