### ISSUE TITLE
Rework of the App screen Permissions clickable header and its pop-up

### ISSUE THREAD

**Issue by mihnea-radulescu** [flathub/website#1933]
### Issue
The App screen Permissions clickable header and its pop-up project the content of the permissions section within the app repository file into human-readable text and graphical cues.

This projection provides information, but also imposes a value judgment of the app's required permissions upon its potential users. Moreover, the value judgment is misleading, since it implies to the user that an audit / assessment was performed by Flathub against the app, which is not the case.

### Rationale
The implementation of this feature hurts both the application developers, who find it unpleasant for their app to be marked as unsafe, and the users, who are inclined to disregard a significant section of the Flathub applications offering, including highly valued apps (see screenshots below), because of it.

![VLC](https://user-images.githubusercontent.com/13825437/266720176-8c6a44cd-f78f-40a9-8f0a-aaadd78ff665.png "VLC")

![Firefox](https://user-images.githubusercontent.com/13825437/266720259-20d2a7ff-5167-4655-a1a8-e9325d130a9b.png "Firefox")

### Suggested fix
Provide the potential users of the app with neutral and objective information, without imposing a value judgment of the app's required permissions, thus leaving it up to the users to make their own assessment.

**In the app screen**:
- replace the Permissions custom text header with the fixed text "Permissions"
- remove the colored icon above the Permissions custom text header

**In the Permissions pop-up**:
- replace the Permissions custom text header with the fixed text header "Permissions"
- remove the colored icon below the Permissions custom text header
- replace the individual permissions icon color coding from a selection of orange, yellow, and green to a single neutral white color coding

**Comment by razzeee** [comment]
This is too complicated for non technical users. I'll close this, as it's unlikely to happen.

**Comment by metal3d** [comment]
Excuse me @razzeee but "too complicated for non-technical users"?

The non technical users see that the majority of application in flathub are "unsafe"... This is the actual topic. IMHO this is an important issue.

**Comment by droidmonkey** [comment]
I opened a new issue because I just realized this was now on the store site. The wording and analysis for this is incredibly harmful in my opinion. #2247
