### ISSUE TITLE
Add exception for verification of net.sourceforge and io.sourceforge app IDs

### ISSUE THREAD

**Issue by pedrolcl** [flathub/website#1939]
There are currently exceptions for the hosting domain when the ID of the application starts with "io.github", "io.gitlab", and "page.codeberg" in the ` _get_domain_name()` function of the backend:

https://github.com/flathub/website/blob/c8045665f3db81fe38307d716318cdf6c3654826/backend/app/verification.py#L116-L129

The exception allows to verify applications using subdomains of that hosting providers. But for sourceforge.net / sourceforge.io subdomains there is not an exception. This is a problem already for several apps published in Flathub:

#1177
flathub/net.sourceforge.VMPK/issues/18

The proposed Sourceforge exception may take into account that the "*.sourceforge.net" subdomains are [deprecated since 2016](https://sourceforge.net/p/forge/documentation/Project%20Web%20Services/#changes-as-of-november-2016) and all newer projects have a web site under the sourceforge.io domain.

**Comment by pedrolcl** [comment]
I've reported this issue and offered a patch a month ago, but has been ignored. I have the strong suspicion that this issue against Sourceforge hosted projects is deliberate discrimination.

CC: @hfiguiere

**Comment by hfiguiere** [comment]
So in the end you deleted the PR so it can't be applied and CC me to complain.

I have absolutely no expertise, nor access to that part, so there is nothing I can do to help. But given you closed the PR I don't think there is anything actionable on my side.

Remember this is run with razor thin resources mostly volunteer. Not by a trillion-dollar corporation.

**Comment by pedrolcl** [comment]
@hfiguiere : I've put you in copy of this bug report, just to inform you why I've lost interest in maintaining my projects in Flathub. 

This may be a modest project run by volunteers, but there is some policy here that is harming some projects (and not others) based on the name of the hosting provider. Probably with the intention of damaging that provider. There may be  some economic interests involved in this issue.

**Comment by hfiguiere** [comment]
> Probably with the intention of damaging that provider.

This is as egregious as the discrimination claims.

**Comment by pedrolcl** [comment]
> > Probably with the intention of damaging that provider.
> 
> This is as egregious as the discrimination claims.

I keep this issue open, just in case someone from the project wants to offer another explanation.

About the discrimination claim: it is a fact. The projects having a Sourceforge ID can't be verified. Other projects with IDs from Github, Gitlab and Codeberg can be verified if they want. That is called [discrimination](https://www.wordreference.comdefinition/discrimination) in English.

**Comment by razzeee** [comment]
It's not wanting to take the risk due to not knowing that part of the codebase and the correct people working hard on other stuff.

**Comment by joeraz** [comment]
Speaking as someone who maintains a SourceForge project, and has a vested interest in getting this sorted (I originally reported issue #1177 and have been keeping an eye on this), this seems like an extreme overreaction.  I see no evidence of "deliberate discrimination".  Whomever originally wrote the exceptions code probably just didn't think of SourceForge - there are probably a few other obscure hosting platforms in a similar situation.

Open source projects are often volunteer projects.  I'm personally maintaining PySol in my spare time between a full-time day job, and a couple other hobbies.  Though I make an effort to, I cannot personally resolve every single issue or pull request.  Tickets linger, some far longer than this, and I can think of multiple reasons why that don't involve bad faith.  That's just the nature of open source development.

But deleting the code and closing the PR means the code will not get merged, period.  If you'd just left it open, it would have gotten looked at eventually.  I'd have just pinged the reviewers and asked for an update before, well, this.  This just hurts SourceForge users more in the long run.

To the Flathub developers, I apologize for the rant - seeing this just upset me.  I think I can re-create the PR if it will help move things along.

**Comment by razzeee** [comment]
> I think I can re-create the PR if it will help move things along.

That would indeed be helpful. Funnily enough, I even pinged others on matrix about this patch a day before the PR was closed.

**Comment by pedrolcl** [comment]
First of all, answering to the unconditional advocates Joe and Hubert: I appreciate your candor and innocence. I am not making formal accusations here. I've only expressed my **strong suspicions** of foul game, based on circumstantial evidences. In case it escalates to strong evidences, I would not post that information here on this simple bug report.

Looks like nobody disputes the legitimacy of the complaint. Anyway, I've been doing a small research trying to understand the scope of the problem. The number of applications using  Sourceforge IDs:

    $ flatpak search sourceforge | wc -l
    61

In a similar way, I've compiled a table of some providers and tribes with their number of apps in Flathub:

| ID         | # (apps) |
|------------|----------|
| codeberg   | 25       |
| sourceforge| 61       |
| gitlab     | 66       |
| kde        | 252 (157)|
| gnome      | 302 (174)|
| github     | 767      |
| sum:       | 1473     |

KDE and Gnome have also many runtimes in addition to the number of apps (app numbers are inside the round brackets).

Impact of verification at this time in Flathub:

|type        |#   |
|------------|----|
|verified    |753 |
|non-verified|1570|
|sum:        |2323|

Compare the above table with the number of open source vs. privative apps:

|type       |#   |
|-----------|----|
|open source|2093|
|privative  |230 |
|sum:       |2323|

There are some [more code hosting providers](https://en.wikipedia.org/wiki/Comparison_of_source-code-hosting_facilities#Features) that may be impacted by this problem,  for instance: Bitbucket. Anyway, the number of Sourceforge IDs right now is bigger than Codeberg's, but the latter is allowed to verify its subdomains and Sourceforge IDs are not. I want to add that Sourceforge [claims over 500,000 hosted projects](https://sourceforge.net/). Even if that number is an exaggeration, the potential impacted apps is a lot bigger than 61.

Answering to Joe's comment: go ahead and open your own pull request. Your ticket has been already open for more than seven months with only a single comment (from me). I've deleted the forked repository because I don't want to keep it forever, and because the changes are trivial enough: only five lines added to a single source file. Four lines, if you discount one comment. You may still [see the changes in the closed PR](https://github.com/flathub/website/pull/1941/files) if you want:

![image](https://github.com/flathub/website/assets/15184708/e325157f-5502-445e-aadb-1c5310ddcab5)

Answering to Hubert: You say that this is a modest project run mostly by a couple of volunteers. But in this case, the development of the feature in question has an interesting history...


> GNOME is seeking a contractor to work on FlatpakApps' Flathub. Experience with Flatpak and Rust (for flat-manager) needed, Node (frontend) and Python (API backend) desirable. Diverse applications welcomed from individuals or FOSS-friendly companies.
> Sources: [1](https://discourse.flathub.org/t/seeking-contractors-for-work-on-flathub-project/1889), [2](https://twitter.com/ramcq/status/1462837235166990341).


> KDE and GNOME seek $100k to turn Flathub into a store for the Linux desktop. Source: [Reddit](https://www.reddit.com/r/linux/comments/11ae461/kde_and_gnome_seek_100k_to_turn_flathub_into_a/)


> Flathub is getting a number of important enhancements. They are being made due to the GNOME Foundation funding the efforts with Codethink doing the implementation work...
Add a process to verify first-party apps on Flathub (uploaded by the developer or  authorized representative). 
Source: [Reddit](https://www.reddit.com/r/gnome/comments/wsl39s/huge_changes_coming_to_flathub/).


> [Codethink - Flathub collaboration](https://www.codethink.co.uk/articles/2022/flathub-codethink-collaboration/): 
The plan, which was outlined in the linked forum post, was to allow first-party developers and maintainers of applications distributed through Flathub a way to earn revenue for their work.

**Comment by razzeee** [comment]
> Answering to Hubert: You say that this is a modest project run mostly by a couple of volunteers. But in this case, the development of the feature in question has an interesting history...

Hub is still correct, that project is over and they got their code merged, nobody thought of codeberg or sourceforge at the time. I guess bigger fish to fry, you can still iterate on details. As it was way more important to get verification to work as a whole.

Right now, it's volunteers and one very thinly streched (paid) admin, that's also running all of gnomes infra at the same time.

That codeberg got dealt with was luck/misfortune in my book.

**Comment by joeraz** [comment]
I recreated the PR.  Let me know if you need anything else from me.

**Comment by razzeee** [comment]
Should start working, as soon as the backend is redeployed
