### ISSUE TITLE
[BUG] Website install command is broken

### ISSUE THREAD

**Issue by cassiofb-dev** [flathub/website#1961]
Recently the install command on the website broke. There's a ``flathub`` in the middle of the command.

> [!WARNING]  
> flatpak install **flathub** com.github.tchx84.Flatseal

Website Image:

![image](https://github.com/flathub/website/assets/61878987/75dcc9cc-63e8-46f2-8982-49db9551660c)

**Comment by razzeee** [comment]
That's a correct behaviour, as we assume, that you have setup the flathub remote as `flathub`. Without specifying this, flatpak might install the package from a different remote.

**Comment by SethFalco** [comment]
Reference to the man pages:

```
NAME
       flatpak‐install - Install an application or runtime

SYNOPSIS

       flatpak install [OPTION...] [REMOTE] REF...
```

Which `[REMOTE]` refers to the remote repository to fetch the resource from, which for Flathub.org it would sensibly specify `flathub`.

> Recently the install command on the website broke.

If the command didn't work, you should press the [**setup guide for your Linux distribution**](https://flathub.org/setup) link and follow the instructions!

**Comment by cassiofb-dev** [comment]
Yeah, my bad. Maybe that was some temporary problem like my internet.
Have a great programmer's day and happy coding!
