### ISSUE TITLE
Previews are too small

### ISSUE THREAD

**Issue by RichardFevrier** [flathub/website#1968]
Hello everyone 👋 sorry if this issue does not seem relevant because I do not know how all of this works under the hood but as my title says previews (or zoom is broken) are definitely too small either on the website and in software centers (like gnome for ex).

Is this a requierement by flathub itself or previews could be higher resolutions but because it is not enforced no one does it?
Anyway to me previews are curently useless.

Thanks for your amazing work ❤️

Edit: I did forget to mention that in most of current hardware surveys (Steam, PassMark, ...) primary monitors displays have a 1920 x 1080 resolution, so to my point of view this should be the minimum requierement for previews.

**Comment by razzeee** [comment]
Hey, this is unfortunatly known and being tracked in https://github.com/flathub/website/issues/37 so I'll close this for now. Feel free to still comment here or in that issue.
