### ISSUE TITLE
Filesystem permissions home and host mixed up

### ISSUE THREAD

**Issue by mihnea-radulescu** [flathub/website#1974]
### Issue
The Flathub website mixes up the flatpak permissions **home** and **host** when displaying them in the app permissions UI.

### Example of error:

The [Avidemux](https://flathub.org/apps/org.avidemux.Avidemux) app has the permission finish-args **--filesystem:host** in its repository file, but the permission is incorrectly displayed in the website permission UI as _Home folder read/write access_.

Conversely, the [ImageFan Reloaded](https://flathub.org/apps/io.github.mihnea_radulescu.imagefanreloaded) app has the permission finish-args **---filesystem=home:ro** in its repository file, but the permission is incorrectly displayed in the website permission UI as _Full file system read access_.

### Fix
The faulty logic is in the file **/frontend/src/safety.ts**, between the lines 300 and 340.

**Comment by razzeee** [comment]
Good catch, thanks for finding this.

**Comment by mihnea-radulescu** [comment]
Thank you for the quick fix, @razzeee!

Unfortunately, the issue is still not completely fixed.

There are 2 **access type** categories (read-only and read-write), and 2 **access point** categories (host and home). Since these category groups are orthogonal, this results in 2 x 2 = 4 permission categories (as appearing in the file **/frontend/src/safety.ts**):
- access point **host**, access type **read-write** : correctly covered between the lines 301 and 316
- access point **home**, access type **read-write**: correctly covered between the lines 318 and 339
- access point **host**, access type **read-only**: incorrectly covered between the lines 342 and 360
- access point **home**, access type **read-only**: incorrectly covered between the lines 342 and 360

Essentially the access type **read-only** code between the lines 342 and 360 should be split into 2 categories of permissions, similar to how it was done for access type **read-write**.

**Comment by razzeee** [comment]
Your right, I did not have time to check the whole file. And won't be home for some hours, can hopefully fix in like 4h,feel free to beat me to it.

**Comment by mihnea-radulescu** [comment]
Sure thing, @razzeee, I am happy to help!

Here is the [related PR](https://github.com/flathub/website/pull/1976).
