### ISSUE TITLE
fallback-x11 without wayland is reported as safe

### ISSUE THREAD

**Issue by ColinKinloch** [flathub/website#1998]
`--socket=flatpak-x11` without `--socket=wayland` doesn't trigger a "legacy-windowing-system" rating.

I created the wxEDID flatpak, There was an issue with wayland so I removed `--socket=wayland` at the last moment without changing from `x11` to `feedback-x11`.

As a result it's reported safe:
https://flathub.org/apps/net.sourceforge.wxEDID
![Screenshot 2023-09-20 at 17-18-53 wxEDID Flathub](https://github.com/flathub/website/assets/334272/c0791893-64bb-41ee-b486-1f8f06b810be)

I thought this code would fix it both fallback-x11 and  x11 is also present in `summary.metadata.permissions.sockets`.
```typescript
  // uses legacy windowing system
  if (
    summary.metadata.permissions.sockets?.some(
      (x) => x.toLowerCase() === "x11",
    ) ||
    summary.metadata.permissions.sockets?.some(
      (x) => x.toLowerCase() === "fallback-x11",
    ) &&
    !summary.metadata.permissions.sockets?.some(
      (x) => x.toLowerCase() === "wayland",
    )
  ) {
    appSafetyRating.push({
      safetyRating: SafetyRating.potentially_unsafe,
      title: "legacy-windowing-system",
      description: "legacy-windowing-system-description",
      icon: HiOutlineComputerDesktop,
      showOnSummaryOrDetails: "both",
    })
  }
```

**Comment by razzeee** [comment]
That part should be reported in https://github.com/flathub/flatpak-builder-lint

Otherwise, this seems consistent with g-s, so if we want to change that, we should probably talk them and see what they think https://gitlab.gnome.org/GNOME/gnome-software

**Comment by razzeee** [comment]
Created https://gitlab.gnome.org/GNOME/gnome-software/-/issues/2347 to discuss this
