### ISSUE TITLE
Application Developer Settings Fails to Load

### ISSUE THREAD

**Issue by heliguy4599** [flathub/website#2035]
When heading to my app's developer settings page, it loads for a brief moment and then crashes. It happens in both Firefox and Chromium.

https://github.com/flathub/website/assets/95997226/5e55b69f-6ab3-4133-9f74-7948c58e33c3

**Comment by kymckay** [comment]
Interesting, something is triggering the fallback error boundary specified at the root application level

https://github.com/flathub/website/blob/8183f9f49c7415daa4133c25d15bf8e07d4fd167/frontend/pages/_app.tsx#L99-L101

When reproducing this, can you open the browser dev tools and share any errors in the console or network tab? I'm unable to reproduce with the developer settings page I have access to, so likely related to a failing network request or something not applicable to the demo app I'm listed on.

**Comment by quyykk** [comment]
@kymckay Not OP but I'm having the same problem. There is one error in the console:

![image](https://github.com/flathub/website/assets/85879619/d17562f1-0b14-4d5a-b20a-534835d02c6a)

**Comment by razzeee** [comment]
Can you also screenshot the `Network` tab when this happens?

**Comment by quyykk** [comment]
Not sure if I'm leaking any secrets but yolo

![image](https://github.com/flathub/website/assets/85879619/dd76f902-cd7c-4476-a0f3-1c41481e0d9d)

**Comment by razzeee** [comment]
Unfortunatly there is no error in that log.

**Comment by razzeee** [comment]
I think I can see it in the logs. So you probably don't have a github account linked?

**Comment by quyykk** [comment]
I do have a GitHub account linked, that's how I am logged in the website. Unless you mean something else.

**Comment by razzeee** [comment]
Hrm, can you check what https://github.com/settings/connections/applications/559030f984ca6f09dfe3 says does the org have access?

**Comment by quyykk** [comment]
I think so yes

![image](https://github.com/flathub/website/assets/85879619/0ac4a361-2a43-42a6-9982-02d24c29f662)

**Comment by razzeee** [comment]
What does this link show, if you clicked it when logged in? https://flathub.org/api/v2/verification/request-organization-access/github

**Comment by quyykk** [comment]
![image](https://github.com/flathub/website/assets/85879619/0df993b7-afb5-42aa-813b-c0c45269d90f)

**Comment by heliguy4599** [comment]
Very sorry that I opened this issue and then went unresponsive. I'm here now if there is any more questions or clarification needed

**Comment by razzeee** [comment]
I've pushed a change, but currently deploys are on hold, so we need to wait for that to be fixed, to see if my change helped.

**Comment by razzeee** [comment]
Deploy is still on hold until further notice

**Comment by heliguy4599** [comment]
The issue has been resolved and I am able to open the Developer Settings. Thanks!
