### ISSUE TITLE
Use codegen for frontend API consumption

### ISSUE THREAD

**Issue by kymckay** [flathub/website#2083]
We can use code generation to produce correct types and API functions by consuming the OpenAPI specification FastAPI exposes. This means the backend Pydantic models become the single source of truth for request and response data typing, which brings a few benefits:
- Increased chance of catching errors during development caused by bad/missing data and typing
- Reduced maintenance burden when changing or adding endpoints used by the frontend
- More consistency in the frontend type definitions and API usage functions
- Convenience for frontend development, no longer need to manage these types manually

Can migrate use of the old types over case-by-case and eventually remove them instead of a big-bang approach. I recently implemented this for a personal project using [openapi-typescript-codegen](https://github.com/ferdikoomen/openapi-typescript-codegen) and would be happy to create a PR here if you think this is desirable @razzeee ?

**Comment by razzeee** [comment]
I don't think our openapi definitions are good enough, I might be wrong. At least zap couldn't handle all endpoints (might be better after the latest changes)

**Comment by kymckay** [comment]
Ah you're right, a lot of endpoints are currently missing adequate type information to fully take advantage of codegen.

I did a quick test of this and we'd probably need to rework the way we handle request errors in the frontend too - which might not be such a bad thing.

The only other thing I don't love is [having to override the OpenAPI config clientside](https://github.com/ferdikoomen/openapi-typescript-codegen/issues/552) for development, but that's a small ugliness.

**Comment by razzeee** [comment]
This might at least help separating the files a little bit, unfortunately it's not generating stuff automatically :/

https://dev.to/macke/using-trpc-with-rest-5hf4

**Comment by kymckay** [comment]
Oh nice, I was recently looking at the T3 stack and tRPC which brought this issue to mind. Dismissed it initially due to the tRPC backend required for the full magic.

**Comment by kymckay** [comment]
I think https://openapi-generator.tech/ might actually be the most robust codegen option for this, I wrote it off before because when I try it in this repo i get `code: 'ERR_REQUIRE_ESM'` (and the FastAPI docs recommend the `openapi-typescript-codegen` library as an alternative).

However, I've just discovered it works perfectly fine (although so does the other library) when I try it on my own project which has an almost identical stack - so presumably should be able to work here too with a little investigation. The multiple module-systems is one of my least favourite things to debug in JS.

For reference:
```json
"openapi-codegen": "openapi-generator-cli generate -i http://localhost:8000/openapi.json -o src/api -g typescript-axios --additional-properties=supportsES6=true"
```

**Comment by razzeee** [comment]
Can you compare your `tsconfig.json` with the one in the repo? are you targeting es6 maybe in your project?

**Comment by kymckay** [comment]
Ah to clarify: I get that error when running the codegen, not during TS compilation. So presumably tsconfig should have no effect and the complaints are coming from the node environment which is running `openapi-codegen`?

For completeness: I am targeting `es2020` in tsconfig.

**Comment by kymckay** [comment]
I wonder if some difference in the `openapi.json` is causing codegen to take a different path which is loading a commonJS module here :thinking:

**Comment by kymckay** [comment]
Good find, it works for me that way too. So something about installing it as a dev dependency in this repo causes the issue.

This weekend I'll revisit my closed PR using this package instead and verify that it's suitable for our needs.
