### ISSUE TITLE
Warn about outdated PureOS remote?

### ISSUE THREAD

**Issue by firefoxlover** [flathub/website#2089]
https://flathub.org/de/setup/PureOS

On this website all you say is "Flatpak is preinstalled, install Flathub and everything works"

This is not the case poorly, as in GUI stores for some reason the PureOS remote got to first place (Discover) and I installed two apps that both simply crashed.

The remote doesnt seem well maintained really, and it has outdated or otherwise broken apps. Tuba and Decoder in my case.

I would advise to deactivate the PureOS remote, as otherwise people may install Apps from the wrong source.

**Comment by razzeee** [comment]
Hey, please suggest/change that over at https://github.com/flatpak/flatpak.github.io
