### ISSUE TITLE
Distro page: Improve search styling

### ISSUE THREAD

**Issue by bertob** [flathub/website#2092]
The search bar here is a bit odd, both because it's so wide and because it's styled like a card. I think reusing the style from the app search bar in the headerbar would work better here.

![image](https://github.com/flathub/website/assets/1908896/f940eca4-9f2b-4cf2-8fd8-7b785eb3d94a)

**Comment by razzeee** [comment]
I think the only one we could use form that is the rounding.

**Comment by bertob** [comment]
I didn't mean literally reusing the style class, just the design pattern/visuals.
