### ISSUE TITLE
More prominent install action on item pages

### ISSUE THREAD

**Issue by nedrichards** [flathub/website#21]
![Screenshot from 2022-01-31 20-53-10](https://user-images.githubusercontent.com/302677/151871407-8fb95b5c-2538-4523-8765-5c46b41d0457.png)

Our primary goal is to convert web browsers into performing a positive action on an item page (eg. install, donate, contribution). We have a *lot* of space in the header with quite small action areas. Even for long app titles like "PulseAudio Volume Control" there's plenty of space.

We should move the donate and install buttons to side by side rather than on top of each other and double the size.

**Comment by razzeee** [comment]
> We should move the donate and install buttons to side by side rather than on top of each other and double the size.

Had a designer friend of mine also suggest this. Still not sure why, but I will probably experiment with it at least, if I find the time.

**Comment by razzeee** [comment]
They are side by side now, but there are also potentially up to four buttons there. See https://github.com/flathub/website/issues/536

**Comment by RacerBG** [comment]
Looks fine on the website, this issue should be closed in my opinion.
