### ISSUE TITLE
[Frontend][Bug] Header buttons require clicking exactly on text

### ISSUE THREAD

**Issue by q30a** [flathub/website#211]
https://beta.flathub.org/
**Current behavior:**
When one tries to navigate 'Publish', 'Forum', 'About', 'Login' buttons, it turns out that not entire button is clickable. Action takes place only if the text is clicked.
**Expected behavior:**
Action (navigate) should take place when the button is clicked (entire button, not only text)

https://user-images.githubusercontent.com/105132988/167274692-9d1d1b57-c55d-4673-b97a-0fb8abd0b37e.mov

.

**Comment by razzeee** [comment]
I don't think your right about the `About` button, but otherwise great work finding this.
