### ISSUE TITLE
If account name is long, UI is broken.

### ISSUE THREAD

**Issue by oyajun** [flathub/website#212]
![image](https://user-images.githubusercontent.com/81346541/167284359-ae98b4ce-da4b-4640-8e4c-9a43f088df54.png)

I want to move the seach bar to left.
![image](https://user-images.githubusercontent.com/81346541/167284379-885969ba-d36c-42a4-bd57-2c407b058548.png)

**Comment by ajr0d** [comment]
#251 addresses and fixes this. Closed.
