### ISSUE TITLE
Support for OpenSearch protocol

### ISSUE THREAD

**Issue by eightfiftytwo** [flathub/website#213]
With how often I look up applications on Flathub, I'd like to be able to right-click the URL bar on Firefox and add Flathub as a search engine. Flathub could do this by supporting the [OpenSearch protocol](https://developer.mozilla.org/en-US/docs/Web/OpenSearch). Thank you for your hard work!

**Comment by razzeee** [comment]
I've looked at this from time to time, first failing to understand how to handle it and now it seems like the protocol is pretty much on it's way out.

So I'll close this, as it's probably not worth allocating any more time.
