### ISSUE TITLE
Weblate plurals handling

### ISSUE THREAD

**Issue by mkljczk** [flathub/website#2197]
As I can see on Weblate, it doesn't seem to handle plurals in Polish language correctly. According to Weblate, it should work properly, when format is set to i18next JSON v4 in Weblate configuration. Is it set correctly for Flathub websiite?

**Comment by razzeee** [comment]
We still seem to be on v3 and not v4. I'm not sure if we can change that without breakage.

**Comment by razzeee** [comment]
Changed to v4

**Comment by mkljczk** [comment]
Thanks, it is working correctly now.

![Screenshot_20231109-235537.png](https://github.com/flathub/website/assets/21127288/50dce567-9862-4d08-b628-11768d8809c0)
