### ISSUE TITLE
[Frontend][Bug] Downloads over time graph drops almost to 0

### ISSUE THREAD

**Issue by q30a** [flathub/website#221]
'Downloads over time' graph drops almost to 0 for prior day.
Screenshot taken 2022-05-09, value for 2022-05-08 is almost 0.
<img width="1426" alt="Downloads over time 2022-05-09 at 11 01 19" src="https://user-images.githubusercontent.com/105132988/167377252-fa38b0c2-985f-4e44-b959-454992f72b7c.png">

**Comment by razzeee** [comment]
That should correct itself with the next run. We usually hide the last day due to that, but seems like this endpoint slipped through.

**Comment by razzeee** [comment]
I think @barthalion patched this recently
