### ISSUE TITLE
Improve wording for architecture list

### ISSUE THREAD

**Issue by nedrichards** [flathub/website#23]
We should consider new copy for the architecture list on an app page. e.g. " 'aarch64, arm, i386, x86_64'" on a page like this https://flathub.vercel.app/apps/details/org.gnome.Connections

Something like aarch64 is quite arcane to even technically inclined users. I can't immediately think of better copy but will continue to think.

We should also think about how to highlight if an app is available on the architecture of the device you're browsing from, or perhaps more importantly not available in the context of aarch64 devices.

**Comment by razzeee** [comment]
This feels, like it will be an issue, that we won't be able to close, unless somebody comes up with some wording.

**Comment by razzeee** [comment]
Feel free to reopen, when anybody has come up with something actionable with a wording.
