### ISSUE TITLE
Add publication submission agreement

### ISSUE THREAD

**Issue by neilmcgovern** [flathub/website#230]
As we start getting more submissions, we need an agreement for those submitting apps

**Comment by neilmcgovern** [comment]
Initial draft below:

Flathub
Publisher Submission Agreement
This publisher submission agreement (“Agreement”) governs your submission of content for publication via the Flathub service. As a condition to receiving publication services, and for other good consideration, the receipt of which is hereby acknowledged, you accept and agree to the following terms and conditions for your present and future publisher submissions to Flathub.  
1.	Definitions.
“You” (or “Your”) shall mean the copyright owner or legal entity authorized by the copyright owner that is making this Agreement with The Gnome Foundation. For legal entities, the entity making a Submission and all other entities that control, are controlled by, or are under common control with that entity are considered to be a single Publisher. For the purposes of this definition, “control” means (i) the power, direct or indirect, to cause the direction or management of such entity, whether by contract or otherwise, or (ii) ownership of fifty percent (50%) or more of the outstanding shares, or (iii) beneficial ownership of such entity.
“Submission” shall mean any original work of authorship or invention, including any modifications or additions to an existing work, that is intentionally submitted by You to Flathub for building, packaging, and publication via Flathub. 
2.	Grant of Copyright License. Subject to the terms and conditions of this Agreement, You hereby grant to Flathub and to recipients of software distributed by Flathub a perpetual, worldwide, sublicensable, transferable, non-exclusive, no-charge, royalty-free, irrevocable copyright license to utilize your Submission to build an executable version of your Submission and reproduce, publicly display, publicly perform, and distribute Your Submissions in original and executable form, as well as the right to sublicense and have sublicensed all of the foregoing rights.    
3.	Grant of Patent License. Subject to the terms and conditions of this Agreement, You hereby grant to Flathub and to recipients of software distributed by Flathub a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable (except as stated in this section) patent license to make, have made, use, offer to sell, sell, import, and otherwise transfer the Submission in original and executable form, where such license applies only to those patent claims licensable by You that are necessarily infringed by Your Submission(s) alone. 
4.	You represent that you are legally entitled to grant the licenses set forth in this Agreement.  You represent that each of Your Submissions:
a) is Your original creation or that you otherwise own or have obtained sufficient rights to grant the licenses set forth in this Agreement; 
b) includes complete details of any third-party license or other restriction (including, but not limited to, related patents and trademarks) of which you are personally aware and which are associated with any part of Your Submissions;
c) does not, to your knowledge, infringe the intellectual property rights of any third party;
d) does not, to your knowledge, violate any applicable laws or regulations.
6.	So long as you fully comply with the terms of this Agreement (including granting the unhindered license rights in this Agreement to all recipients of your Submission who obtain your Submission via Flathub), you may, if you choose, place additional contractual restrictions on your Submission via a license file, which will be distributed with your Submission via Flathub.  
7.	You are not expected to provide support for Your Submissions, except to the extent You desire to provide support. You may provide support for free, for a fee, or not at all. Unless required by applicable law or agreed to in writing, You provide Your Submissions on an “AS IS” BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied, including, without limitation, any warranties or conditions of title, non-infringement, merchantability, or fitness for a particular purpose.
8.	You agree to notify Flathub of any facts or circumstances of which you become aware that would make these representations inaccurate in any respect.

**Comment by nedrichards** [comment]
> The Gnome Foundation

Really? GNOME surely. Other than this lgtm

**Comment by razzeee** [comment]
So this will be on the website too? Just another page in the footer or what's the intend?

**Comment by neilmcgovern** [comment]
> > The Gnome Foundation
> 
> Really? GNOME surely. Other than this lgtm

s/Gnome Foundation/Flathub/ :)

**Comment by neilmcgovern** [comment]
> So this will be on the website too? Just another page in the footer or what's the intend?

I think this will need to be a "you have to agree to this before you can submit apps" type thing.

**Comment by nedrichards** [comment]
More specification on what 'via a Licence file' means might be helpful - but in terms of an agreement this covers the key bases.

**Comment by razzeee** [comment]
> I think this will need to be a "you have to agree to this before you can submit apps" type thing.

Which means, it's not on the website, but somewhere else?

**Comment by razzeee** [comment]
Ping

**Comment by razzeee** [comment]
Closing, as this has been added
