### ISSUE TITLE
400 on log in attempt if the flow is interrupted

### ISSUE THREAD

**Issue by q30a** [flathub/website#241]
**Steps to reproduce** (use private mode to start with a clean slate):
1. Go to https://beta.flathub.org/login
2. Click one of available options (e.g. GitHub)
3. You will be redirected to selected auth provider.
4. Go back one page and land on https://beta.flathub.org/login again.
5. Try to click other auth providers.

**Current behavior:**
400 on every attempt for providers other than in step 2.
`{
    "state": "error",
    "error": "User is mid-login-flow elsewhere"
}`
**Expected behavior:**
User can select auth providers freely.

**Comment by q30a** [comment]
`{"state":"error","error":"User is mid-login-flow elsewhere"}`

**Comment by kymckay** [comment]
Daniel and I discussed the ideal solution to this in a sync call one week. Believe we landed on the backend clearing out the in-progress flow and initiating the new flow (which requires some wrangling of the way the flow tokens are managed).

**Comment by razzeee** [comment]
Possibly fixed by https://github.com/flathub/website/pull/981

**Comment by rokejulianlockhart** [comment]
Indeed, @razzeee, it has been remediated for me.
