### ISSUE TITLE
Two languages set in the URL

### ISSUE THREAD

**Issue by q30a** [flathub/website#248]
Reproduction steps:
1. Go to beta.flathub.org
2. Scroll down to footers and click 'Switch Language'
3. Click Português - now the URL is https://beta.flathub.org/pt_BR
4. Scroll down to footers and click 'Alterar idioma'
5. Click English - now the URL is https://beta.flathub.org/pt_BR/en
6. Go back one page, go forward one page - now the URL is again https://beta.flathub.org/pt_BR/en
7. Scroll down - footers are in Portuguese but English was chosen last

https://user-images.githubusercontent.com/105132988/168155239-2019e67e-a9d8-44e5-91b5-e741dba4c930.mov

**Comment by q30a** [comment]
#75 might be relevant here.

**Comment by razzeee** [comment]
Thank you, great catch!
