### ISSUE TITLE
Statistics map labels do not fit in boxes for RTL languages

### ISSUE THREAD

**Issue by q30a** [flathub/website#262]
Go to https://beta.flathub.org/ar/statistics and hover over countries.
Labels do not fit in boxes.
<img width="1904" alt="Screenshot 2022-05-15 at 14 04 20" src="https://user-images.githubusercontent.com/105132988/168471919-715868eb-22e3-45c1-bc65-258b5626d228.png">

**Comment by razzeee** [comment]
Can you file that with https://github.com/yanivam/react-svg-worldmap I'm pretty sure it's on their side

**Comment by q30a** [comment]
Done yanivam/react-svg-worldmap#125

**Comment by q30a** [comment]
@razzeee https://github.com/yanivam/react-svg-worldmap/issues/125#issuecomment-1127010679

**Comment by razzeee** [comment]
I would suggest to wait till they fix it
