### ISSUE TITLE
Frontend CI is a flaky test

### ISSUE THREAD

**Issue by kymckay** [flathub/website#268]
Frontend CI can sometimes fail when there's no problem in the repository (see https://github.com/flathub/website/runs/6448849956?check_suite_focus=true).

It looks like this is when no appstream data is found and static generation fails. The following kind of error can also be seen in the log:

```
FetchError: invalid json response body at https://flathub.org/api/v2/appstream/org.tabos.roger reason: Unexpected token < in JSON at position 0
```

Which looks like XML is being returned instead of JSON.

**Comment by razzeee** [comment]
I'm not sure we're still seeing that. Now CI is failing due to different things.

https://github.com/flathub/website/pull/554 might help
