### ISSUE TITLE
Check if we're GDPR compliant

### ISSUE THREAD

**Issue by razzeee** [flathub/website#28]

**Comment by Miepee** [comment]
Had a few questions regarding the GDPR section of the current privacy policy, was told to redirect them here:

1. 
    > You have the right to request copies of your personal data. We may charge you a small fee for this service.

    The way this is phrased, makes it look like to me, that the fee charge is a regular occurrence, while AFAIK its only allowed for excessive requests. Could this be clarified on whether that's the case? (Also would be neat to know what the fee would be, but I suppose one gets that answer when one actually asks for a data copy?)

2. The right to erasure, processing restriction, and portability are all under "certain conditions". What are those conditions?

**Comment by razzeee** [comment]
https://matomo.org/blog/2018/04/how-to-not-process-any-personal-data-with-matomo-and-what-it-means-for-you/

Miepee ***@***.***> schrieb am Fr., 3. März 2023, 08:50:
