### ISSUE TITLE
Verification for GitHub organizations

### ISSUE THREAD

**Issue by jameswestman** [flathub/website#280]
Currently, GitHub verification does not work for apps owned by an organization (e.g. com.github.HypatiaProject.hypatia). In this case, we need to check whether the logged in user is an admin of the organization named in the app ID.

**Comment by razzeee** [comment]
Is this still a todo or have we forgotten to track this?

**Comment by razzeee** [comment]
I would also think, that the current design of `appverification` is problematic for this, as a user is needed for the primary/foreign key

**Comment by jameswestman** [comment]
The current design is that a specific user is always responsible for verification, and for org verification that user must be an admin of the GitHub organization.
