### ISSUE TITLE
Bug in version release date

### ISSUE THREAD

**Issue by petre2dor** [flathub/website#282]
I randomly stumbled upon [this app](https://beta.flathub.org/apps/details/io.bit3.WhatsAppQT) that shows last version as released `over 52 years ago`

![image](https://user-images.githubusercontent.com/676869/169357762-ebba5964-8627-4bae-b91b-0f9251acc475.png)

PS: thanks for all your work +1

**Comment by razzeee** [comment]
I fear, that this happens outside of the websites code, will have to follow up with @barthalion on this one

**Comment by barthalion** [comment]
The appdata file should use `date` instead of `timestamp`.

```
    <releases>
        <release version="1.0.3" timestamp="2021-11-15"/>
        <release version="1.0.2" timestamp="2021-06-06"/>
        <release version="1.0.1" timestamp="2020-08-09"/>
        <release version="1.0.0" timestamp="2020-08-09"/>
    </releases>
```

I guess we should either this on the backend end somehow, given we just copy attributes right now:

```
        if releases is not None:
            app["releases"] = []
            for rel in releases:
                attrs = {}
                for attr in rel.attrib:
                    attrs[attr] = rel.attrib[attr]
```

…and avoid displaying the date at all if that attribute is missing.

**Comment by JakobDev** [comment]
The [Appstream of this program](https://gitlab.com/bit3/whatsappqt/-/blob/master/desktop/share/metainfo/io.bit3.WhatsAppQT.metainfo.xml) contains a Misstake. The uses timestamp instead of Date. Timestamp is the number of seconds since 1970. I already [filled a Bug on libappstream](https://github.com/ximion/appstream/issues/402), so this can be blocked after the switch to libappstream.

**Comment by JakobDev** [comment]
> …and avoid displaying the date at all if that attribute is missing.

The date tag gets converted to a Timestamp, so I guess it would be better to check if Timestamp is somewhere in the 70s.

**Comment by razzeee** [comment]
Now the app is gone from the website? Both the old and new one?
