### ISSUE TITLE
Define a Strong Visual Identity

### ISSUE THREAD

**Issue by jimmac** [flathub/website#301]
Flathub is the center of the application ecosystem on Linux, and not a collection of technologies for app distribution. It needs a strong, user facing visual identity. 

## Audience

Flathub is a place **people** go to install apps. Flathub is a place where **app developers** present their hard work. Flathub *is* Apps.

## Similar Products

* [iOS App store](https://www.apple.com/app-store/)
* [Microsoft Store](https://apps.microsoft.com/store/)
* [Samsung Galaxy Store](https://galaxystore.samsung.com/games)

## Brand  Character
Unifying, central, application

## Brand Tools
grid, tile, colorful gradients

## Deliverables
  * Website itself
    - [x] [Font](https://github.com/flathub/website/issues/512)
    - [x] Metadata/Favicon/Sharing banners
    - [x] [Color scheme](https://github.com/flathub/website/issues/501)
    - [ ] Layout/Illustration
  * [x] 'Get on Flathub' Button
  * [x] Social sites (twitter mainly).

**Comment by jimmac** [comment]
Initial concept.

[concept.pdf](https://github.com/flathub/website/files/8778173/concept.pdf)

**Comment by jimmac** [comment]
Alternative concept made during the Berlin hackfest. 

[flathub-logo.pdf](https://github.com/flathub/website/files/9166719/flathub-logo.pdf)

**Comment by ramcq** [comment]
@jimmac Something to ponder - how would you vary the logo if we wanted to make something different for Flathub's Beta repo? Per https://discourse.flathub.org/t/a-different-icon-for-flathub-beta/2753 so it shows up more clearly if Software/Discover needs to show a source drop down?

**Comment by razzeee** [comment]
Anything  concrete that's not touching the brand/logo you want changed? We're slowly trying to launch this.

**Comment by jimmac** [comment]
> @jimmac Something to ponder - how would you vary the logo if we wanted to make something different for Flathub's Beta repo? Per https://discourse.flathub.org/t/a-different-icon-for-flathub-beta/2753 so it shows up more clearly if Software/Discover needs to show a source drop down?

I wouldn't overthink it. Just append ' Beta' to the name.

**Comment by razzeee** [comment]
@jimmac would you be able to provide the 2nd Logo in a usable format?

**Comment by jimmac** [comment]
I plan on working on the identity next week. Here's the WIP asset I have from Berlin hackfest:

![flathub-logo](https://user-images.githubusercontent.com/14821/219881153-bbb337b6-94a9-481a-8051-b9da49798368.svg)

**Comment by jimmac** [comment]
Brand Guidelines: 
[brand-guide.pdf](https://github.com/flathub/website/files/10793093/brand-guide.pdf)

Presskit: [flathub-branding.zip](https://github.com/flathub/website/files/10793097/flathub-branding.zip)

Download buttons (SVG): [download-button.zip](https://github.com/flathub/website/files/10793101/download-button.zip)

**Comment by razzeee** [comment]
Landed a first iteration with this

**Comment by jimmac** [comment]
[flathub-rebrand.webm](https://user-images.githubusercontent.com/14821/220758681-cfcadb11-4785-467a-bb96-885826a532a4.webm)

**Comment by NikSays** [comment]
Hello!
Will there be a place (and time) for feedback regarding the branding changes? Something like a discourse.flathub.org topic, to gauge community reaction

**Comment by DartDeaDia** [comment]
How about using "FlatHub", with an uppercase "H"?
Thus, it is much easier and faster for people to read FlatHub than Flathub.

Also, if we look at the names of similar products, their second word has uppercase letter: App Store, Google Play, Microsoft Store.

It is also important, people can take away the confusion with **Flatpak** and **Flathub**, the two related names with "Flat" are easily confused.
**Flatpak** and **FlatHub** it's already much easier to see the difference.

![1](https://user-images.githubusercontent.com/122628420/220876748-b2324d4b-1686-4680-9ee8-3bf364dd330b.png)

**Comment by koffiato** [comment]
I'm not in favor of going capitals in the middle of the word. In fact, I think going all lowercase makes more sense as it conveys being flat. Also, the new site lacks color. I get that we're letting the apps take the spotlight, but I think Material You-like pastel coloring per-app basis would fit the site fairly well. Here's a quick prototype of no capital logo: 
![flathub-proposal](https://user-images.githubusercontent.com/43079520/220943404-263af08e-c4cd-46ea-95b1-2f90344f3ecc.png)

**Comment by barthalion** [comment]
I've locked the issue as it's being shared across social media and attracting unwanted attention. We're happy to discuss constructive feedback over at https://matrix.to/#/#flathub:matrix.org.

**Comment by razzeee** [comment]
@jimmac I need to edit some of your files every time, as they have very big padding, which makes placement hard, just FYI.

Adding the gray fallback favicon would also be cool

**Comment by jimmac** [comment]
> @jimmac I need to edit some of your files every time, as they have very big padding, which makes placement hard, just FYI.
> 
> Adding the gray fallback favicon would also be cool

I'll look into rolling out website specific assets and address the favicon pixel snapping and fallback variants.
