### ISSUE TITLE
Incorrect 'Last updated' timestamp on transaction summary

### ISSUE THREAD

**Issue by q30a** [flathub/website#306]
1. Go to https://beta.flathub.org/donate
2. Enter desired amount and press 'Make Donation' - note time - e.g. 12:00:00
3. Whoops! Error: Failed to load Stripe.js - happens for every attempt so I guess it's expected
4. Press 'Go to User Wallet'
5. Press 'Cancel Transaction' next to the generous donation - note time - e.g. 12:00:30
6. Press 'View'

Current behavior:
'Date created' and 'Last updated' timestamps are the same

Expected behavior:
'Date created' is 12:00:00 in this case
'Last updated' is 12:00:30 in this case

**Comment by kymckay** [comment]
It looks like this is a backend issue as frontend component is using the updated date: https://github.com/flathub/website/blob/4b9a3540613853ccaa7a2caa835ce4625951e005/frontend/src/components/payment/transactions/TransactionListRow.tsx#L24

**Comment by razzeee** [comment]
This seems to be gone with the csp issue resolved
