### ISSUE TITLE
Add robust validation to donation amount input

### ISSUE THREAD

**Issue by kymckay** [flathub/website#308]
Splitting this out from #305 to track.

Things to address:

- [ ] At the moment an arbitrary $5 minimum is in place, however if the user enters a lower value and submits the form it will automatically revert to $5 and proceed which may be unintuitive. Simple solution is probably just to block submission and provide some visual feedback to highlight the input.
- [ ] Set some sane upper limit to prevent errors caused by large numbers. Due to the way the controlled component casts from string to number I'm curious to ensure this doesn't cause client-side errors if a value greater than `Number.MAX_VALUE` is entered.

**Comment by razzeee** [comment]
As we insert it into a transaction table, it can't be bigger then integer https://www.postgresql.org/docs/current/datatype-numeric.html

**Comment by razzeee** [comment]
I think this has been taken care of, feel free to reopen, if you disagree.
