### ISSUE TITLE
Is the stats API safe for public use?

### ISSUE THREAD

**Issue by JakobDev** [flathub/website#32]
I think most of you know about [Shields.io](https://shields.io). For those who are not: It's a Site who provide Bages, that you can e.g. include in a Readme. These Badges show information about the Software e.g the download count or if the build has passing. A lot of people using them.

A Badge which shows the Flathub Downloads was requested by a lot of People around the Internet. I would also like to has one. This became more important the more Flathub grows in popularity. So I decided to [make a PR](https://github.com/badges/shields/pull/7724) which added a Downloads Badge. It uses the Stats API ([https://flathub.org/api/v2/stats/{appid}](https://flathub.org/api/v2/stats/{appid}). In the [correspondending Issue](https://github.com/badges/shields/issues/5506) came the Question, if this API is safe to use.

I don't know the Answer, so I asked it here. If it not safe to use, you should add a API for public use.

**Comment by nedrichards** [comment]
Yeah, we currently document that people should use the bare files https://github.com/flathub/flathub/wiki/App-Maintenance#download-statistics which doesn't seem ideal, we should update that wiki page when we have a better story here as well!

**Comment by razzeee** [comment]
I think docs should probably mention both

**Comment by razzeee** [comment]
Closing as this has been shipped
