### ISSUE TITLE
Make release note date tooltips non-US-specific

### ISSUE THREAD

**Issue by wjt** [flathub/website#329]
On, eg, https://beta.flathub.org/apps/details/org.freedesktop.Bustle, release notes' timestamps are rendered like this, with the exact date in the tooltip:

```
<div title="7/31/2020">almost 2 years ago</div>
```

7/31/2020 is the US-specific M/D/Y format. In this particular case it is unambiguous, but in general this format is ambiguous to a global audience.

My browser sent the following header with my request:

```
accept-language: en-GB,en;q=0.9,fr-FR;q=0.8,fr;q=0.7
```

so the site could adjust to my regional taste for a more logical date format. But failing that / in the absence of l10n in general on the site, a better format might be "31st July 2020".

**Comment by razzeee** [comment]
https://github.com/flathub/website/pull/330
Fixes the part, when a language is selected

**Comment by razzeee** [comment]
Your obviously right. But the used variable will only ever return these https://github.com/flathub/website/blob/main/frontend/next-i18next.config.js#L6 for better or for worse.

It could defiantly be nicer. I've tried using the fallback option of toLocaleString (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString#using_locales) but that also errors. Catching the exception works, but feels a bit weird to me, still, we might not have a better option.

Still, you won't get an english (uk) date that way. For that we probably need to have a whole new locale.

**Comment by wjt** [comment]
Forgive me what is probably a stupid question, but what is wrong with:

```js
new Date(...).toLocaleString(navigator.language)
```

I don't know anything about nextjs but presumably it selects the locale based on the user's `accept-language` header, which I believe is what gets exposed as `navigator.language`.

This property seems to have been supported forever. https://developer.mozilla.org/en-US/docs/Web/API/Navigator/language

**Comment by razzeee** [comment]
That doesn't exist in nextjs, at least not at render time. So a problem unless we don't want to do a static render/make no js people happy.

```
ReferenceError: navigator is not defined
  55 |                     latestRelease.timestamp &&
  56 |                     new Date(latestRelease.timestamp * 1000).toLocaleDateString(
> 57 |                       navigator.language,
     |                      ^
  58 |                     )
  59 |                   }
  60 |                 >
```

**Comment by wjt** [comment]
I see.

**Comment by wjt** [comment]
How about:

```
>>> new Date().toLocaleDateString("en", {dateStyle: 'long'})
'June 6, 2022'
```

This style is unambigious in all English dialects. (The `en-GB` version would be `6 June 2022`.)

**Comment by razzeee** [comment]
I think this is the only sane way? https://github.com/flathub/website/pull/345

Also "fixes" the switch language page to have english but only one flag :)

**Comment by razzeee** [comment]
So, do you end up on the correct local on the beta page now?

**Comment by wjt** [comment]
I'm not sure how I can check the locale directly, but date tooltips in release notes are still in the US MM/DD/YYYY format.

I checked and the browser is sending:

```
accept-language: en-GB,en;q=0.9,fr-FR;q=0.8,fr;q=0.7
```

How can I help to investigate further?

**Comment by razzeee** [comment]
So if you go to https://beta.flathub.org/ you don't end up on https://beta.flathub.org/en_GB ?

**Comment by wjt** [comment]
No, I stay at https://beta.flathub.org/

– Will

**Comment by razzeee** [comment]
Really sounds like a bug. I couldn't also get it to work, but I thought I tested it, when we started with it.

https://nextjs.org/docs/advanced-features/i18n-routing#automatic-locale-detection

**Comment by razzeee** [comment]
Hrm, it does seem to work in dev mode on my system, so this might be caused by the ISR https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration

**Comment by razzeee** [comment]
Please have another go, when this deployed. Also keep an eye out for other stuff that might have broken.
