### ISSUE TITLE
Login provider icons broken (beta site)

### ISSUE THREAD

**Issue by wjt** [flathub/website#34]
On https://beta.flathub.org/userpage I see:

![Capture d’écran de 2022-03-07 16-24-19](https://user-images.githubusercontent.com/86760/157075220-66d326be-a9f5-429d-90d6-d3b5b3230f6c.png)

This is because the img src is `http://meh`:

```html
<button class="ProviderLink_provider__muLZ7"><img src="http://meh" width="60" height="60" alt="Login with Google">Login with Google</button>
```

**Comment by razzeee** [comment]
I think this was solved, as we host these images on our own now
