### ISSUE TITLE
Bad transaction status when trying to cancel a donation

### ISSUE THREAD

**Issue by q30a** [flathub/website#343]
1. https://beta.flathub.org/
2. Donate to Flathub
3. Make Donation
4. Tap Cancel Transaction on every attempt
```
{"status":"error","error":"bad transaction status"}
```

Cannot reproduce this error now so feel free to reject if it's deemed not relevant.

**Comment by kymckay** [comment]
I was unable to reproduce this today. It may be that we've prevented the state from being reached or that this is some rare edge case.

Let's close for now and if we run into it again hopefully we can figure out what's going on (might just want to make the backend ignore the error and perform the cancellation regardless).
