### ISSUE TITLE
User deletion failure in staging

### ISSUE THREAD

**Issue by kymckay** [flathub/website#35]
Just happened to try this while checking issue notifications this weekend. Currently in [staging](beta.flathub.org) when trying to delete my account the request returns status 500 and I see

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://flathub.org/api/v2/auth/deleteuser. (Reason: CORS header 'Access-Control-Allow-Origin' missing).

This was working fine in development so perhaps that's a misleading message and there's some edge case error happening server-side.

**Comment by ajr0d** [comment]
https://github.com/flathub/backend/pull/150 addressed this, and it works fine for me now.
