### ISSUE TITLE
popularity has a stronger influence on search results

### ISSUE THREAD

**Issue by nedrichards** [flathub/website#43]
I'm filing this here since the results are not the same between this and the current site - feel free to close if there's no ordering done in this codebase and we'll refile it in the correct place.

We should include a higher rating for popularity in search e.g. newsflash has about 10x more downloads than hackup on https://flathub.vercel.app/apps/search/news but is much lower down. We want to ensure that users get high quality apps by default.

**Comment by razzeee** [comment]
This should be solved by https://github.com/flathub/website/pull/64

Downloads have an impact there, but it's not the highest rated, which I think is fine.

**Comment by razzeee** [comment]
This should be solved by https://github.com/flathub/website/pull/64

Downloads have an impact there, but it's not the highest rated, which I think is fine.

**Comment by razzeee** [comment]
This should now be the case with the new serach engine.

**Comment by nedrichards** [comment]
Confirmed fixed.
