### ISSUE TITLE
Clean up frontend component internals

### ISSUE THREAD

**Issue by kymckay** [flathub/website#437]
This is really just a suggested refactoring task - purely for development quality of life.

In terms of the frontend components, some of them are a bit messy internally as they do too many things. For maintainability, I'd suggest we look to refactor them to use barrelling and break those responsibilities into sub-components (while keeping them grouped and self contained). I think this pattern would also help to make imports more manageable across the frontend as the number of components increases.

_Originally posted by @kymckay in https://github.com/flathub/website/issues/353#issuecomment-1176055072_

**Comment by kymckay** [comment]
Use of both higher order components and wrapper components are also both ways to cut down on repetition and overly-responsible components.

**Comment by razzeee** [comment]
I don't think this is concrete enough to to act upon.
