### ISSUE TITLE
Verifying first-party apps

### ISSUE THREAD

**Issue by jameswestman** [flathub/website#44]
## Background

Flathub allows third parties to upload apps which are not their own, similar to traditional distro packagers. However, for several reasons, we want to be able to mark apps which *are* uploaded by their developers. For example, donation integration should only be available if it's the upstream developer packaging the app.

Of course, we also want to do this in a way that doesn't require a huge amount of work for the admins. Some amount of human moderation will always be required, but we can try to minimize it.

## Proposal: Verify based on RDNN app ID

App IDs already contain information about the upstream developer: usually either a website or a GitHub/GitLab user or organization. We should extract that information from the app ID and verify it.

- Websites (e.g. org.gnome.Maps): Developers need to place a .well-known file on their domain (or possibly a DNS record?)
- GitHub (e.g. com.github.flxzt.rnote): The developer with that username or an owner of that organization needs to log in with GitHub and confirm.

Flathub admins will need to ensure that apps are submitted with the correct ID. They will be able to manually verify apps or block them from being verified.

**Comment by nikodunk** [comment]
How is work on this progressing? Are there any outstanding tasks that you need help with/I could help with?

**Comment by ifeeltiredboss** [comment]
@nikodunk the progress can be tracked on matrix channel #flathub-contract:matrix.org

**Comment by nikodunk** [comment]
Ah nvm I see it's being done on https://github.com/flathub/website/pull/734

**Comment by eikenb** [comment]
It is called out in #734 that it is about front end only.
Is there a separate issue/PR for the backend part of this feature yet?

**Comment by TheEvilSkeleton** [comment]
I found a bug that prevents me from verifying my app. On GitLab at least, it's case sensitive, where it wants me to login to `@theevilskeleton`, and not `@TheEvilSkeleton`.

![image](https://user-images.githubusercontent.com/50847364/217115574-8f5b28ec-b78d-4099-bde4-9e7ec5e0124f.png)

**Comment by jameswestman** [comment]
@TheEvilSkeleton GitHub usernames appear to be case insensitive, so we should probably allow that.

**Comment by hadess** [comment]
Is there documentation on how to use the verification feature? I could not find any in the wiki, in linked issues or on the beta website.

**Comment by razzeee** [comment]
There is a part on https://beta.flathub.org/about otherwise it should hopefully be self explanatory for now.

We're planning to relaunch flathub specific documentation soonish.

**Comment by hadess** [comment]
I expected the workflow to start [from the user page](https://user-images.githubusercontent.com/769861/220081537-074eedb5-45dd-4d0f-8447-15d33ab27a71.png), including offering to link accounts as needed.

I also now realise that the "Authored apps" doesn't exist if GitHub isn't a linked account, and that it wants me 
to [create a file on gnome.org](https://user-images.githubusercontent.com/769861/220082255-6837d3a4-be45-47e1-9e16-640a3398fce5.png), which I cannot do.

**Comment by hadess** [comment]
Happy to file issue about the above, if that's preferred.

**Comment by razzeee** [comment]
Do the apps you want to verify have repos on github.com/flathub/org.gnome.gitlab.xxx and you have commit access?

**Comment by hadess** [comment]
> Do the apps you want to verify have repos on github.com/flathub/org.gnome.gitlab.xxx and you have commit access?

No, the app-id of that app predates gitlab.gnome.org, and were among the first imported in Flathub under different rules.

**Comment by hadess** [comment]
> No, the app-id of that app predates gitlab.gnome.org, and were among the first imported in Flathub under different rules.

Seems only some apps use org.gnome.gitlab:
https://github.com/orgs/flathub/repositories?language=&q=org.gnome.&sort=&type=all

**Comment by razzeee** [comment]
Yeah, that would have been the happy path, the details for the gnome gitlab are still up for discussions and would be tracked here https://github.com/flathub/website/issues/1065

**Comment by hadess** [comment]
Great, thanks. Let me know if the comments about the visibility of the functionality still warrants new issues being filed.

**Comment by barthalion** [comment]
I'm going to close this one as we track GNOME/KDE verification flow in different issues.
