### ISSUE TITLE
Errorpage has no styling

### ISSUE THREAD

**Issue by razzeee** [flathub/website#446]
Seems like somehow our error page lost it's style

https://beta.flathub.org/uaoeuaeua for e.g.

**Comment by kymckay** [comment]
I'm noticing a couple of oddities with staging. Some changes seem to not be reflected while others are. Also the userpage is sending infinite requests to `/userinfo` currently (not happening in dev).

**Comment by razzeee** [comment]
This seems to be due to the `nosniff` rule.

![image](https://user-images.githubusercontent.com/5943908/178613193-2bd09253-f9e1-4160-a99e-eb9a68c212d0.png)

**Comment by kymckay** [comment]
Believe this was due to issues with deployment and can now be closed
