### ISSUE TITLE
Break out the games category into more defined sections

### ISSUE THREAD

**Issue by castrojo** [flathub/website#484]
Right now "Games" is 13 pages of launchers, games, utilities, and all sorts of stuff. I think it might be useful to break this out for a few reasons:

From observing Youtubers covering linux gaming and steamdeck stuff there's a lot of "ok search for this, then install, then search for this, then install, then search for this, then install." I'd like to propose splitting "Games" into something more granular. Something like this, I'm sure everyone will have an opinion on naming so I'll just go with large buckets:

"Games" - Actual games
"Emulators" - and their associated utilities
"Gaming Tools" - everything gaming related that is not a game or emulator, launchers, etc.

and then lastly, I think having a "Core Gaming" thing would be useful, basically so when someone is getting into linux gaming people can just say "you'll probably need all of these, just install everything in this category" So a small curated list, here's a first stab: 

```
com.valvesoftware.Steam
com.valvesoftware.Steam.Utility.gamescope
org.freedesktop.Platform.VulkanLayer.MangoHud
com.heroicgameslauncher.hgl
org.openrgb.OpenRGB
com.usebottles.bottles
com.github.Matoking.protontricks
```

I am unsure if categories can be nested or if they'd all be top level, so filing this for discussion. When we have a rough consensus I'd be happy to whip up a PR if someone could outline how new categories are made.

**Comment by razzeee** [comment]
Ideally this should be made possible in appstream, so you would need to talk to the freedesktop people.

**Comment by JakobDev** [comment]
> Ideally this should be made possible in appstream, so you would need to talk to the freedesktop people.

I'm pinging @ximion. 

Currently the Flathub Website and some Software centers e.g. Gnome Software. has it's own curated categories. e.g. Editors Choice Apps on the Flathub Website. It might be a good idea, if a Repository can add some featured Apps to it's AppStream. e.g.
```xml
<components version="0.8" origin="flatpak">
  <featured>
    <name>Recommend Apps</name>
    <name xml:lang="de">Empfohlene Apps</name>
    <apps>
      <id>org.mozilla.firefox</id>
      <id>org.gimp.GIMP</id>
    </apps>
  </featured>
  <featured>
    <name>Get ready for Linux Gaming</name>
    <apps>
      <id>com.valvesoftware.Steam</id>
      <id>com.heroicgameslauncher.hgl</id>
    </apps>
  </featured>
  <component type="desktop">
  <!-- Normal Stuff-->
</components>
```
With this Flathub and other Flatpak Repos could feature Apps across the Website and all Software Centers.

**Comment by razzeee** [comment]
Hrm, I thought of this more on the line of modernizing the categories. I'm not sure how much we want what you propose/if that problem exists/if it would be used by gnome software etc.

**Comment by JakobDev** [comment]
The above Example was more for the Core gaming sugeestion. having this would be pretty nice. Most people who have it's first contact with Linux use the Sotware Centers to explore Apps and not the Flathub Website. So featuring some important Apps like e.g. heroic Games Laucnher for Gaming would be a good thing.

Modernising the categories is absolutely needed. The Question is here, if AppStream should do this in Sync with the normal Freedesktop categories which are also used in other Places are if AppStream should add it's own categories.

**Comment by ximion** [comment]
AppStream uses the XDG categories - so, to update those, the corresponding specification needs to be changed (which is definitely possible, but will need some back and forth between the individual desktop environments).

To suggest good apps, AppStream has a heuritic recommendation system that software centers could make use of: https://www.freedesktop.org/software/appstream/docs/chap-CollectionData.html#tag-ct-suggests However in general I think a feature like this is so specific to the software center and the platform the user is on, that generalizing it does not make much sense (KDE will want different suggestions than GNOME, etc.).

**Comment by razzeee** [comment]
Working on this mostly highlighted, how bad the data quality in this regard is, especially in the utliities section, which is the 2nd biggest one.

Also there are some odd categories, as mentioned above, but with my current approach, we can at least pick only the ones we want to show.
