### ISSUE TITLE
Top bar search style

### ISSUE THREAD

**Issue by bertob** [flathub/website#487]
The search in the top bar looks a bit lost off on the left side, and visually too prominent. I'd center it and simplify the background to be 0.15 opacity text color, like so:

![image](https://user-images.githubusercontent.com/1908896/180652507-11725a68-b9ee-448d-b8af-f4cced022d76.png)

**Comment by razzeee** [comment]
I don't remember the exact reason I moved it left, but I think it had something to do with problems during resizing the window to smaller sizes. So it can certainly be improved/fixed.

**Comment by bertob** [comment]
At the medium breakpoints it might make sense to have it left aligned indeed, but the ones to optimize for are very narrow phone sizes (around 400) and relatively wide desktop widths (i.e. maximized on 1300+). I'd just make sure it's centered for the latter.

**Comment by razzeee** [comment]
My Research earlier suggested that too. Still, we seem to be a bit odd with our Navigation on the right.

**Comment by bertob** [comment]
> we seem to be a bit odd with our Navigation on the right.

I mean that's only a problem at the narrow desktop widths though, at like 1920 it's totally fine to have search centered, there's enough whitespace around it even with the navigation on the right being a lot wider than the log on the left.

**Comment by razzeee** [comment]
yes, that was more about navigation being on the right, then about the search

**Comment by q30a** [comment]
#212 might be reintroduced.
