### ISSUE TITLE
Recently Added title formatting

### ISSUE THREAD

**Issue by bertob** [flathub/website#488]
The Recently Added page has weirdly formatted title (lowercase with dash), I guess it should be "Recently Added".

![image](https://user-images.githubusercontent.com/1908896/180652584-d815c6dc-9100-4123-9bd7-f5ea78eeb1dc.png)

**Comment by razzeee** [comment]
That happens when the translation doesn't exist in any language. I think that should have been fixed by https://github.com/flathub/website/pull/480/files and we probably did not have a successfull deploy since then :/

**Comment by kymckay** [comment]
Staging appears to have been failing deployment for a while. Shall we repurpose this issue to track that?

I have a hunch #446 may be a symptom of it too.

**Comment by kymckay** [comment]
Believe this was due to issues with deployment and can now be closed
