### ISSUE TITLE
Page counter styling

### ISSUE THREAD

**Issue by bertob** [flathub/website#500]
The page counter doesn't look great, I'd do something simpler with flat inactive items and circular active items.

![image](https://user-images.githubusercontent.com/1908896/180652775-b6ef1879-e026-467f-925c-1c57d6eb965f.png)

Here's a quick mockup:

![image](https://user-images.githubusercontent.com/1908896/180892354-4be5f9d5-c418-46e0-bfb3-b25f6e8aa115.png)

**Comment by razzeee** [comment]
Yes, been unhappy with that for a long time. Will look into it.
