### ISSUE TITLE
Standardize blue

### ISSUE THREAD

**Issue by bertob** [flathub/website#501]
Currently there are two blue accent colors, which clash quite a bit visually.

Most elements are using this blue:

![image](https://user-images.githubusercontent.com/1908896/180892679-c1819f8f-5939-4ce4-bbe2-1968ce7963b2.png)
![image](https://user-images.githubusercontent.com/1908896/180892613-4e63e4b0-7e99-424a-8b0d-bbc9e54103be.png)

But some things are using turquoise:

![image](https://user-images.githubusercontent.com/1908896/180892573-02137ffe-50da-492f-b2a2-9cb8e0475877.png) ![image](https://user-images.githubusercontent.com/1908896/180892782-2197a685-3bd4-4ed2-84f2-62120433b803.png) ![image](https://user-images.githubusercontent.com/1908896/180892809-3ef80ce8-3fe5-4ba8-a95c-ea4dd1b34405.png) ![image](https://user-images.githubusercontent.com/1908896/180892825-8be829f5-43c2-41a2-84e0-cd6148a734f5.png)

In general the outline button style should be replaced with simple gray background colors, but it'd be good to get rid of all occurrences of the secondary blue regardless.

**Comment by razzeee** [comment]
So gray background and black /white Text depending on the dark/light theme?

**Comment by bertob** [comment]
Yeah, basically just transparent text color for the background.
