### ISSUE TITLE
Font: Inter is not loading

### ISSUE THREAD

**Issue by bertob** [flathub/website#507]
Currently I'm getting a fallback font instead of Inter on beta.flathub.org:

![image](https://user-images.githubusercontent.com/1908896/181266970-cb34f7c8-622d-43ef-987f-c38100ce881b.png)

**Comment by razzeee** [comment]
I can get this to happen very sporadically in firefox and chromium. It seems to happen often in gnome web, so it might be something gnome web is not doing similar to those browsers?

**Comment by bilelmoussaoui** [comment]
I have to refresh everytime i visit the page so the font is properly loaded using firefox

**Comment by razzeee** [comment]
@bilelmoussaoui any errors in your console? Does that also happen, if you disable all plugins?

It's consistently happening for me in firefox in a private tab (no addons) and if I refresh with Control + F5
Otherwise it seems fine usual.

I seem to get `downloadable font: font-display timeout, webfont not used (font-family: "Inter" style:normal weight:400 stretch:100 src index:0) source: https://dl.flathub.org/repo/assets/Inter-3.19/Inter-Regular.woff2`

**Comment by bertob** [comment]
On the latest non-Flatpak Firefox on Fedora it's never worked for me, I always get the fallback. How are the fonts loaded?

**Comment by razzeee** [comment]
Are you seeing this request in the dev tools? 
![image](https://user-images.githubusercontent.com/5943908/181482875-a54b65af-2829-422f-ad2a-839c11c4e5f2.png)

**Comment by bertob** [comment]
Seems so:

![image](https://user-images.githubusercontent.com/1908896/181513100-dfbadd63-8e4b-4fd3-be3f-081f0c650f89.png)

**Comment by bertob** [comment]
Actually, I just had the font show up on reload once now, but it's not reproducible in general. It seems to happen sometimes, but no idea why exactly.

**Comment by bilelmoussaoui** [comment]
I get this in the logs the first visit of the website
```
downloadable font: font-display timeout, webfont not used (font-family: "Inter" style:normal weight:400 stretch:100 src index:0) source: https://dl.flathub.org/repo/assets/Inter-3.19/Inter-Regular.woff2
downloadable font: font-display timeout, webfont not used (font-family: "Inter" style:normal weight:400 stretch:100 src index:0) source: https://dl.flathub.org/repo/assets/Inter-3.19/Inter-Regular.woff2 
```

**Comment by razzeee** [comment]
Is this still happening for you? We recently changed, how fonts are loaded.

**Comment by bertob** [comment]
Looks fixed, thanks!
