### ISSUE TITLE
Links are not highlighted on some pages

### ISSUE THREAD

**Issue by q30a** [flathub/website#514]
1. Go to https://beta.flathub.org/languages
2. Notice that some links are not highlighted, for example:
All these translations have been contributed by the community. If you want to help translate Flathub, please [join the Flathub translation team](https://hosted.weblate.org/engage/flathub/).

**Comment by razzeee** [comment]
I guess you mean how it displays in the light theme? It's very subtle, I agree.

**Comment by q30a** [comment]
This is how it look on Firefox 102
<img width="668" alt="Screenshot 2022-07-29 at 15 19 28" src="https://user-images.githubusercontent.com/105132988/181769112-da29b426-abea-43b9-9070-9f57a11225d8.png">

**Comment by razzeee** [comment]
Whoops, at least the dark variant is now broken too :D
