### ISSUE TITLE
support non-desktop components

### ISSUE THREAD

**Issue by bilelmoussaoui** [flathub/website#53]
Currently, the api endpoints are desktop-app specific. We should expose at least cli, extensions & sdk's. This also would be a step forward to support displaying extensions of an application.

**Comment by razzeee** [comment]
@bilelmoussaoui was this about the API explicitly? because if so, this should be fixed.

**Comment by razzeee** [comment]
Okay, so we can only close this after we show `console` apps in some way :)

**Comment by razzeee** [comment]
This might still need a tag or info on the detail page, but let's see how confused users are without.
