### ISSUE TITLE
Support changing of App ID

### ISSUE THREAD

**Issue by JakobDev** [flathub/website#542]
The current way of changing the App ID (e.g. when you moved your Homepage) is to create a new App with the new ID and put a flathub.json with a `end-of-life` and `end-of-life-rebase` in the old Repo. But this is currently not supported by the Website.

Let's take a look at CherryTree for example. Old ID was `com.giuspen.cherrytre`, new ID is `net.giuspen.cherrytree`. If we take a look at the [old Repo](https://github.com/flathub/com.giuspen.cherrytree), we can find this `flathub.json`:
```json
{
  "end-of-life": "The application has been renamed to net.giuspen.cherrytree",
  "end-of-life-rebase": "net.giuspen.cherrytree"
}
```
It clearly says that the App has changed it's ID to `net.giuspen.cherrytree`.

Now let's try to access https://beta.flathub.org/de/apps/details/com.giuspen.cherrytree. It will give you a 404. So it will break all existing Links, which is a bad user experience. Instead of doing that, this Page should redirect to https://beta.flathub.org/de/apps/details/net.giuspen.cherrytree.

It should also move all Data to the new ID. Currently these are only the Download stats, but there will maybe more in the future.

**Comment by bilelmoussaoui** [comment]
Relevant issue #51

**Comment by razzeee** [comment]
Closing, as the main thing has been achived.

Migrating downloads is being discussed here: https://github.com/flathub/website/pull/833
