### ISSUE TITLE
Top bar active state has no contrast

### ISSUE THREAD

**Issue by bertob** [flathub/website#553]
When clicking elements in the top bar they turn white, which is not great since the text is also white. I'd make this active state white with e.g. 30% opacity to retain contrast.

![image](https://user-images.githubusercontent.com/1908896/183416270-9724c0f7-06e6-4ae5-87e6-b37159707a11.png)

![image](https://user-images.githubusercontent.com/1908896/183416194-e36fdf3e-72b0-43bd-a2cf-1aa6c49f502c.png)

**Comment by razzeee** [comment]
I would actually like to redo the whole header.

**Comment by bertob** [comment]
Is there anything you need for that from the design side?

**Comment by razzeee** [comment]
I'll send some Screenshots of what I would base it on in the next days.

I would assume that we want most things to like now?

One difference will be, that the mobile nav will take the whole screen. Which I prefer.

**Comment by razzeee** [comment]
I've landed the new header, I'm sure there are some papercuts in there for now, but I think I'm happier then with the old one for now.

So let me know what to improve.

**Comment by bertob** [comment]
Ok, had a quick look. Looks good for the most part, except for search bar size/alignment:
- [ ] At phone widths it looks good, but above that (about 600-1000px) it's awkward to have such a wide search bar. I'd have it centered on the page and with a max width or about 400px.
- [ ] At sizes above 1000px or so where the desktop nav items are visible the search bar should also always be centered on the whole page, and have a max width of about 400px.
- [ ] The hover and active state on the mobile primary menu should not be inverted, but just the same as on all the other nav items
- [ ] If the menu is full-screen I'd center the items horizontally and make them a bit larger. Alternatively not havig the menu cover the whole screen vertically could also work.

![image](https://user-images.githubusercontent.com/1908896/184369647-25a0a209-c75d-4a08-bad1-b03ed4c4ea61.png)

**Comment by razzeee** [comment]
I'm torn on the last one. That change would make the logged in display of your username a bit weird I think/feel?

I like the idea and we actually do something like that for the footer on mobile sizes 

![image](https://user-images.githubusercontent.com/5943908/184432614-537e2129-a13d-46fd-92ec-4415d9127f9e.png)

**Comment by bertob** [comment]
>  That change would make the logged in display of your username a bit weird I think/feel?

Maybe, but not necessarily. If the styling was a bit different from the other items below (smaller text size, bold, smaller avatar), I think it could maybe work. In general this is probably the least important point on the list above though.

**Comment by bertob** [comment]
Some other papercuts:

- [ ] The menu items have a weird, almost invisible shadow
![image](https://user-images.githubusercontent.com/1908896/184460043-4418413f-adc3-4248-8972-75fc6c3c2be6.png)

- [ ] When the menu is open it has an unnecessary blue border, which sticks around after closing the menu
![image](https://user-images.githubusercontent.com/1908896/184460074-854848d7-78ba-4499-8905-1643ae598359.png) ![image](https://user-images.githubusercontent.com/1908896/184460085-6eac9cd3-f7ec-4d7a-81fa-be6b71a37ff1.png)

**Comment by razzeee** [comment]
Should be better after https://github.com/flathub/website/pull/591

**Comment by razzeee** [comment]
I guess we can close this?

**Comment by RacerBG** [comment]
LGTM

**Comment by bertob** [comment]
Indeed, it's fixed in prodcution!
