### ISSUE TITLE
No padding for some pages

### ISSUE THREAD

**Issue by q30a** [flathub/website#561]
Some pages have layout without any padding on the left / right side.
Example:
<img width="1904" alt="Screenshot 2022-08-10 at 17 05 05" src="https://user-images.githubusercontent.com/105132988/183939217-32d5bde4-3e64-45ca-b5f1-20641b147482.png">

Pages:
1. /apps/category/* - https://beta.flathub.org/apps/category/AudioVideo
2. /apps/collection/project-group/* - https://beta.flathub.org/apps/collection/project-group/KDE
3. /apps/collection/<categories> - https://beta.flathub.org/apps/collection/recently-updated

**Comment by q30a** [comment]
@razzeee 1 fixed, 2 and 3 unfixed?

**Comment by razzeee** [comment]
I fixed 1 earlier today. I think 2 and 3 did not make it through the build yet - or maybe our deployment has problems.
