### ISSUE TITLE
Fix a flag

### ISSUE THREAD

**Issue by akhiga** [flathub/website#593]
Please fix below language flag

https://beta.flathub.org/languages
Language: සිංහල / Sinhala / si / සිං

Current flag: see https://beta.flathub.org/languages[1]
Correct flag: 🇱🇰 https://emojipedia.org/flag-sri-lanka/

[1]Also, do you remember the source? then we can fix it too.

**Comment by razzeee** [comment]
I'm sorry, I think that was proposed by github copilot and I did not catch it.

**Comment by RacerBG** [comment]
@razzeee Sorry for the interruption but why Catalan doesn't use it's own flag as well?

```
case "ca":
      return ""
```

For reference, here is the flag of Catalonia:
https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Catalonia.svg/1280px-Flag_of_Catalonia.svg.png

**Comment by razzeee** [comment]
I don't think it exists in the emoji standard right now

**Comment by q30a** [comment]
@razzeee @RacerBG 
> I don't think it exists in the emoji standard right now
I don't think it will be introduced anytime soon and it kinda looks out of place for now so maybe we need to come up with some other design to unify the look for all languages?
source: https://qz.com/2148267/the-reason-why-unicode-wont-add-new-flag-emoji/

Alternatively: switch to some other emoji source like OpenMoji: https://openmoji.org/library/emoji-1F3F4-E0065-E0073-E0063-E0074-E007F/
