### ISSUE TITLE
Suggestion: Add translation descriptions to weblate

### ISSUE THREAD

**Issue by kbdharun** [flathub/website#611]
I would love to have translation descriptions added to certain keywords (Like *manifest*, etc) to weblate so that it will create more ease for translators to know about the context of the term we are translating as there can be different words we could use for a specific translation and we can determine the best one only when we know the context,  we currently need to navigate the website to find the use case of certain keywords when translating to regional languages adding descriptions/instructions to weblate directly would help us write better translations in a faster and efficient manner.

**Comment by razzeee** [comment]
We can upload screenshots to weblate, but I don't know how to do this. Did you find something in their docs while seaching?

We might also be limited by the translation format we're using right now.

**Comment by kbdharun** [comment]
Sorry for the late reply.

> We can upload screenshots to weblate, but I don't know how to do this. Did you find something in their docs while seaching?
> 
> We might also be limited by the translation format we're using right now.

I found this in [docs](https://docs.weblate.org/en/latest/formats.html), seems like we are indeed limited by the `.json` format. The only option to provide contexts is to provide screenshots here like the ones [metadata-cleaner](https://gitlab.com/rmnvgr/metadata-cleaner/-/) use. You can add the screenshots directly from weblate under **String Information** see this guide for more information on adding screenshots and context https://docs.weblate.org/en/latest/admin/translating.html .

**Comment by ovari** [comment]
1. Can the name of applications be shown in Hungarian if they have been translated?

For example, the names of both "Video Downloader" and "Video Trimmer" have been translated into Hungarian.

![image](https://user-images.githubusercontent.com/17465872/202866885-736d5feb-9efe-49a6-9221-7bc4de6dba88.png)

2. If a user searches for "Video Downloader" using the translated name, it doesn't show. For example https://beta.flathub.org/hu/apps/search/vag%C3%B3

Can the search also ignore diacritics? i.e. `e` will also search for `é`? and  `é` will also search for `e`?

4. Can the descriptions show in the language if they are available.

For example, Octave is translated into Hungarian in the manifest file, yet it shows in English on the https://beta.flathub.org/hu/apps/details/org.octave.Octave webpage.

![image](https://user-images.githubusercontent.com/17465872/202866820-8f22c6ce-37df-4fe7-ba90-5034e8406906.png)

What do you think?

Thank you

**Comment by razzeee** [comment]
We curretly don't use translated app data, read up on https://github.com/flathub/website/pull/88 for the bigger picture.

3. I would think that diacritics should be ignored, but if that's not the case, it might be a bug in meilisearch https://github.com/meilisearch/meilisearch or they need help with Hungarian handling

**Comment by ovari** [comment]
> it might be a bug in meilisearch https://github.com/meilisearch/meilisearch or they need help with Hungarian handling

1. Thank you, created an issue.
2. Could you please advise which `Meilisearch version: [e.g. v0.20.0]` Flathub Beta uses?
3. Should the `Meilisearch version` be displayed on the https://beta.flathub.org/ website? Perhaps at https://beta.flathub.org/about

Thank you

**Comment by razzeee** [comment]
As far as I know, we're on 0.28.1

**Comment by razzeee** [comment]
Closing, as there is no concrete thing to do / way to success with this.

Feel free to still discuss in here.
