### ISSUE TITLE
Empty 'Installs over time' chart for new apps

### ISSUE THREAD

**Issue by ifeeltiredboss** [flathub/website#612]
This happens when the app has more than 0 installs and the app is new:
https://beta.flathub.org/apps/details/org.kde.filelight
<img width="1792" alt="Screenshot 2022-08-27 at 20 35 14" src="https://user-images.githubusercontent.com/111905360/187043755-ef3b8805-8d4c-46c4-aa71-628b4d560186.png">

This is an edge case to #610.

**Comment by razzeee** [comment]
Should be gone when https://github.com/flathub/website/pull/610 reaches deployment
