### ISSUE TITLE
Firefox manifest links to non-existent GitHub page

### ISSUE THREAD

**Issue by ifeeltiredboss** [flathub/website#626]
1. Go to https://beta.flathub.org/pl/apps/details/org.mozilla.firefox
2. Click Manifest: https://github.com/flathub/org.mozilla.firefox
3. 404

**Comment by kenryuS** [comment]
I guess the Manifest URL should be changed to https://github.com/flathub/org.mozilla.firefox.BaseApp

**Comment by kenryuS** [comment]
> I guess the Manifest URL should be changed to https://github.com/flathub/org.mozilla.firefox.BaseApp

Never mind, that was probably the wrong one.

**Comment by razzeee** [comment]
So this s happening, as apps like obs and firefox are build on their infrastructure and thus, we don't have the source.

We've implemented a handling for this in the site already, via some metadata under the `Flathub::manifest` key, but haven't communicated that to all parties, so this is expected for now.

**Comment by razzeee** [comment]
Has been solved, but will need documentation.
https://github.com/flathub/flathub-docs-docusaurus/issues/11
