### ISSUE TITLE
Make the tables responsive 

### ISSUE THREAD

**Issue by razzeee** [flathub/website#642]
We either need another Design for this or make it scroll able on mobile.

![Screenshot_20220904-220233_Firefox Nightly.png](https://user-images.githubusercontent.com/5943908/188331476-4d88da82-e694-4d2b-91df-b0afe8a33483.png)

**Comment by kymckay** [comment]
I was thinking we could use disclosures here, similar to how I did the app tokens list. Then the full information can only be shown when expanded

**Comment by razzeee** [comment]
How would you manage that with a disclosure?

**Comment by kymckay** [comment]
It'd be entirely replacing the table with a list of disclosures, like I did here:

https://github.com/flathub/website/blob/main/frontend/src/components/application/AppVendingControls/OwnershipTokens/TokenList.tsx

https://github.com/flathub/website/blob/main/frontend/src/components/application/AppVendingControls/OwnershipTokens/TokenListItem.tsx

When collapsed, items can only show the most relevant/distinguishing information which removes the need to cram so much into limited horizontal space. Then when expanded the further details and interactions are available.

Essentially just a way to move to a more vertical layout for easy scrolling and responsive design for narrower screens, while retaining the condensed sequence of transactions.
