### ISSUE TITLE
Aarch64 architecture not shown on beta.flathub.org

### ISSUE THREAD

**Issue by Jacalz** [flathub/website#694]
My project Rymdport on beta.flathub.org (see https://beta.flathub.org/apps/details/io.github.jacalz.rymdport) only shows x86-64 as available architectures even through the Manifiest compiles for aarch64 as well.

Look at the actions on https://github.com/flathub/io.github.jacalz.rymdport/commit/f768c207d4b6f3eb7f44e917894d6c5446c181a8 and see that it builds for both architectures without any issues.

This problem is not entirety satisfactory given that my project should work well on arm64 as well.

**Comment by razzeee** [comment]
Might be https://github.com/flathub/website/pull/636 not working

**Comment by razzeee** [comment]
It seems to be there now for me

**Comment by Jacalz** [comment]
Still only showing x86_64 for me: 
![image](https://user-images.githubusercontent.com/25466657/192220383-ce452f64-817b-4dcb-93cb-52f11893ce77.jpeg)

**Comment by razzeee** [comment]
Force refresh the page Control + F5

**Comment by Jacalz** [comment]
You're right. It seems fine now. Thanks :)
