### ISSUE TITLE
Show localized content from manifests

### ISSUE THREAD

**Issue by Miepee** [flathub/website#708]
Currently, it doesn't seem like localized content from program's manifests are shown.

To repro:
1. Use spanish language
2. Visit Steam 
(https://beta.flathub.org/es/apps/details/com.valvesoftware.Steam)

Since the manifest has [spanish translations for those](https://github.com/flathub/com.valvesoftware.Steam/blob/beta/com.valvesoftware.Steam.metainfo.xml#L10), I expected to see them on the site instead of the english text
![grafik](https://user-images.githubusercontent.com/38186597/192833239-041690a2-3f47-43b4-9205-4de46fe2d3b0.png)

**Comment by razzeee** [comment]
See https://github.com/flathub/website/pull/88 and https://github.com/flathub/website/issues/466
