### ISSUE TITLE
Clicking on preview image should enlargen it

### ISSUE THREAD

**Issue by Miepee** [flathub/website#709]
From behaviour of other sites, I've raised the expectation, that clicking preview images automatically enlargens them.
The site currently does not do that.

To repro:
1. Open any app (like https://beta.flathub.org/de/apps/details/org.mozilla.firefox)
2. Click on the preview image

The preview image should enlargen (as if you clicked the magnifying glass next to it)

I am not sure if this is covered by #662 , but thought it'd raise an issue for it.

**Comment by razzeee** [comment]
There's a drag interaction on the image already, I'm not sure if that would work fine with a click also being on it. 

And right now the provided resolution of "zoom" images is not very good anyway.

**Comment by razzeee** [comment]
I don't think we should do this, as it collides with the drag and while we could try to figure out if the user has a mouse etc, that's a slippery slope for very little gain.
