### ISSUE TITLE
Improve "popular" page

### ISSUE THREAD

**Issue by Miepee** [flathub/website#715]
1. Currently it's not clear what the range for the popular applications is. Is it the most popular applications this week? This month? All Time?

2. There currently is no way to change the range of popular applications. I personally like seeing which applications are the most popular for a certain week.

**Comment by razzeee** [comment]
1.It's this month, but I don't think users should know or care.

2. I don't think there's enough value in that, we might do something like that for app authors at some point, but probably focused on their app.

**Comment by Miepee** [comment]
> but I don't think users should know or care.

Might just be me, but I do think it should be stated somewhere.
I was under the impression that those were all-time popular apps, which made following the recent discussion in the flatpak matrix room a bit confusing, as the top apps that were talked about there, did not match to what I saw.

But again, could very well be that the way i'm using app stores deviates from the norm.

**Comment by razzeee** [comment]
Thanks for this issue, I'll close this for now, but it will be a good data point in case we find more people that open up similar issues.
