### ISSUE TITLE
Remove language from URL

### ISSUE THREAD

**Issue by JakobDev** [flathub/website#75]
The URL has currently the Language. e.g.https://beta.flathub.org/de/apps/details/org.mozilla.firefox. This is really bad if people want to share Links. Most people will just copy the URL and don't remove the Language part, so users will be land on a Site in a Language they don't speak, which is a really bad user experience. I would suggest the following instead:

If the User visits https://beta.flathub.org/languages and change the Language this is saved in a Cookie.

If a Site is loaded check if the cookie exists:
  - If yes:
     - Use the Language from the Cookie
  - If no:
      -Check if Flathub has the Browserlanguage
      - If yes:
          - Use the Browerlanguage
      - If no:
          - Use Englisch

**Comment by razzeee** [comment]
I don't think this is a good idea from a SEO POV. Probably something to research.

**Comment by JakobDev** [comment]
Have search engines really problems with that in the Year 2022? What would be a other solution to this Problem?

**Comment by razzeee** [comment]
I think this is a won't fix with the current framework we're using. I'll close this for now.
