### ISSUE TITLE
Add a warning on beta.flathub.org`s payment page

### ISSUE THREAD

**Issue by calvinweb** [flathub/website#752]
please add a warming like this 
> Dont depend on the require payment function. there are many way to bypass it,

**Comment by barthalion** [comment]
Sorry, but what this issue is supposed to mean? Payments support is in development and `beta.flathub.org` is configured to use testing API keys. **There is no actual payment support.**

**Comment by calvinweb** [comment]
> Sorry, but what this issue is supposed to mean? Payments support is in development and `beta.flathub.org` is configured to use testing API keys. **There is no actual payment support.**

sorry for my English ,bus i means it is necessary to warm developers that dont depend on it when the payment is ready
