### ISSUE TITLE
[Feature request] Allow searching by app id

### ISSUE THREAD

**Issue by RDKRACZ** [flathub/website#764]
This https://flathub.org/apps/search/fr.handbrake.ghb
should give the exact app, unlike just showing a few apps like here https://flathub.org/apps/search/handbrake

**Comment by RDKRACZ** [comment]
Also, the search is kinda borked in beta
https://beta.flathub.org/apps/search/fr.handbrake.ghb

**Comment by razzeee** [comment]
I'm not convinced this is a usecase the search should support or encourage. But it would be easily fixed, still not sure what the point would be.

**Comment by ifeeltiredboss** [comment]
> I'm not convinced this is a usecase the search should support or encourage. But it would be easily fixed, still not sure what the point would be.

I think it makes sense. It does not need to be encouraged but it should return correct app or nothing. Now even if you know the ID of the app, you are getting wrong results like here https://beta.flathub.org/apps/search/fr.handbrake.ghb in @RDKRACZ example.
