### ISSUE TITLE
flathub.org seems to be down.

### ISSUE THREAD

**Issue by peotr26** [flathub/website#789]
The website for Flathub, flathub.org, seems to be down. I have tried it on Firefox and Chromium.
I'm located in France, if it could have any effects on the issue.
Furthermore, I get the same issue when trying beta.flathub.org, and I get the same result.

Screenshot for Firefox:
![image](https://user-images.githubusercontent.com/67782057/201160610-a40e783b-41a3-424f-9784-d8f4f48efa7c.png)

Screenshot for Chromium:
![image](https://user-images.githubusercontent.com/67782057/201160815-eeb52dd3-3c6f-4ff7-96d1-c679f43d06f2.png)

**Comment by razzeee** [comment]
Check status.flathub.org
