### ISSUE TITLE
Navigating on a app from beta.flathub.org freezes the tab

### ISSUE THREAD

**Issue by nikodunk** [flathub/website#802]
1. Go to https://beta.flathub.org/
2. Press on any app tile, and the browser tab will freeze (Firefox 106 & Chrome latest on Fedora 37, Safari on iPhone X)

It was not like this yesterday. Hope it's helpful to report here.

**Comment by razzeee** [comment]
I can't repro this locally, so it might be the deployment somehow.

**Comment by JetpackDuba** [comment]
I've got the same issue. Also, if I access a URL directly of any app, the URL automatically changes to https://beta.flathub.org/apps/details/[object%20Object]

**Comment by JakobDev** [comment]
> Also, if I access a URL directly of any app, the URL automatically changes to [https://beta.flathub.org/apps/details/[object%20Object]](https://beta.flathub.org/apps/details/%5Bobject%20Object%5D)

I thing I know what happens here. #644 was merged yesterday which added a redirect for EOL Apps. To know if a App is EOL, it makes a API call to eol/rebase/<appid>. If it returns a string, it redirects the User to the new Page, If it returns none, the App is not EOL and everything and no redirect happens. But it looks like new Backend is not deployed. https://flathub.org/api/v2/eol/rebase/<appid> currently returns a not found. So it looks like the Version of the Website is newer than the Version of the Backend and calls a API, that currently does not exists in the Backend. Updating the Backend should fix the Problem.
