### ISSUE TITLE
Please show Hungarian translation at http://beta.flathub.org/hu instead of `Client Error`

### ISSUE THREAD

**Issue by ovari** [flathub/website#807]
Weblate hu (Hungarian - magyar) translation is at 100%.
https://hosted.weblate.org/projects/flathub/frontend/hu/

Could you please show Hungarian translation at http://beta.flathub.org/hu ?

Thank you

**Comment by razzeee** [comment]
Thanks for the effort, this is huge. :1st_place_medal:

**Comment by ovari** [comment]
Thank you for merging.

Are translations automated so if some Hungarian strings are improved they will show automatically on the website or is there a merge of translations every week, say on Tuesdays?

Thank you once again.

**Comment by razzeee** [comment]
1. There will be an automatic PR created here, I usually just merge them from time to time. Mostly depending on how much changes happened. Not sure if we should have a fixed schedule (or could even manage that)

2. Not really, the idea right now is to find trimmed down feature sets and start releasing this in a trimmed down form.
