### ISSUE TITLE
No Catalan and Esperanto flag emojis

### ISSUE THREAD

**Issue by ifeeltiredboss** [flathub/website#818]
@razzeee Sorry for the interruption but why Catalan doesn't use it's own flag as well?

```
case "ca":
      return ""
```

For reference, here is the flag of Catalonia:
https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Catalonia.svg/1280px-Flag_of_Catalonia.svg.png

_Originally posted by @RacerBG in https://github.com/flathub/website/issues/593#issuecomment-1221527202_

**Comment by razzeee** [comment]
https://github.com/flathub/website/issues/593#issuecomment-1221527202

**Comment by ifeeltiredboss** [comment]
@razzeee why is it labeled invalid? The Catalan flag won't be included in Unicode's emojis. So with current design it is doomed to look odd.

https://unicode.org/emoji/proposals.html#Flags

**Comment by razzeee** [comment]
Sorry, we're not starting to accept copy and paste issues. Without any infos etc.

I don't think we can act on these.

**Comment by ifeeltiredboss** [comment]
It was copy pasted because the original one was left unanswered I feel. Thanks for clarifying.

**Comment by ifeeltiredboss** [comment]
Actually it was not copy pasted, I used the Github option - create new issue out of a comment because the original one was left unanswered I feel. Thanks for clarifying.

**Comment by razzeee** [comment]
The only thing we can do is remove all flags, which doesn't help the usability of the page much.
