### ISSUE TITLE
Feature flag support for preliminary release

### ISSUE THREAD

**Issue by danielsilverstone-ct** [flathub/website#839]
The following features are *NOT* flagged because we want to release with them

- Validation Capability
- Validation UI
- Backend capability for subsets
- Flat-manager capability for subsets

The following features need to be flagged so that we can disable them if necessary in the first release of the website

- [x] Payments in general (ie wallet, stripe onboarding etc) in UI
- [ ] Wallet API on the backend
- [ ] Vending API on the backend
- [x] Application ownership tokens UI
- [ ] Application ownership tokens API

Out of scope for initial release:

- flatpak-authenticator

**Comment by razzeee** [comment]
I've tagged some issues with this milestone https://github.com/flathub/website/milestone/4

**Comment by razzeee** [comment]
Frontend implementation hiding the controls in https://github.com/flathub/website/pull/903

Pretty much untested, as we have no prod env setup yet.
