### ISSUE TITLE
"About" button isn't a proper link

### ISSUE THREAD

**Issue by traverseda** [flathub/website#849]
Javascript buttons like that can cause accessibility issues. Please make it a proper link and then over-ride its behavior with javascript instead.

If you can't middle click a link it's likely to cause accessibility issues (and also might cause SEO issues if you care about that).

**Comment by razzeee** [comment]
This is referencing the old page, so I'm going to close this, as it works fine in the new one.

**Comment by traverseda** [comment]
So it is, sorry I didn't realize this was the beta.flathub.org repo.

**Comment by razzeee** [comment]
No problem, that's easy to get wrong right now. Hopefully not for too long.
