### ISSUE TITLE
SSL certificate problem: EE certificate key too weak

### ISSUE THREAD

**Issue by XSpielinbox** [flathub/website#858]
When trying to update applications from flathub (running `sudo flatpak update` with flathub repo configured) with the [FUTURE crypto-policy](https://fedoraproject.org/wiki/Changes/StrongCryptoSettings3) enabled in Fedora Linux 37 oder RHEL 9 errors like the following occur:
```
Error: While pulling runtime/org.gnome.Platform.Locale/x86_64/43 from remote flathub: While fetching https://dl.flathub.org/repo/objects/97/990ad73edc13fa80b052028838e3f227c580a192b871a86253d48cbd7ad4ca.commitmeta: [60] SSL peer certificate or SSH remote key was not OK
Updates complete.
error: There were one or more errors
```

This error is very likely due to the fact that dl.flathub.org serves a 2048 bit RSA TLS Cert, but modern cryptography standards require 3072 bit or more when using RSA.

**Comment by razzeee** [comment]
Please report this over on https://github.com/flathub/flathub/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc I have no right to transfer this issue.
