### ISSUE TITLE
Generate .flatpakref

### ISSUE THREAD

**Issue by darkdragon-001** [flathub/website#859]
It would be great if one could access/download the `.flatpakref` directly.

Some possible URLs:
- `https://flathub.org/apps/details/app.id/flatpakref`
- `https://flathub.org/apps/details/app.id.flatpakref`
- `https://flathub.org/apps/details/app.id?type=flatpakref`

**Comment by razzeee** [comment]
Not sure what you mean, you can access it directly? Here's an example:

https://dl.flathub.org/repo/appstream/io.github.brunoherbelin.Vimix.flatpakref

**Comment by darkdragon-001** [comment]
Oh this is awesome!

Then it would be even easier to just add a redirect from one of my suggested URLs. The reason why I think those URLs are superior is because they can easier be generated automatically by just _appending_ something instead of regex parsing the app id and then generating a completely different URL from this.

**Comment by razzeee** [comment]
It would be helpful to have the actual usecase documented here and not just do it for the sake of doing it.

**Comment by darkdragon-001** [comment]
> It would be helpful to have the actual usecase documented here and not just do it for the sake of doing it.

I have a database of Linux mobile applications at https://framagit.org/linmobapps/linmobapps.frama.io/-/blob/master/apps.csv based on which data a website is generated automatically. I would like to easily add an install command to copy for the user. The easiest way would be to just append something to the saved value instead of more thorough parsing.

This is common practice (e.g. Mastodon RSS feeds append `.rss` to the profile URL, Github/Gitlab append `.diff`/`.patch` to a PR/MR URL, ...), so it would be nice if Flathub supports appending `.flatpakref` to the app URL as wel.
