### ISSUE TITLE
License detection needs to match libappstream

### ISSUE THREAD

**Issue by ramcq** [flathub/website#863]
There has been some controversy recently around GNOME Software misidentifying unknown/obscure licenses as proprietary - https://gitlab.gnome.org/GNOME/gnome-software/-/issues/2004

So the "source of truth" in terms of whether something is free or not is v. important - I think the only way we as a community can get this right and improve over time is to ensure we share the list(s).

Flathub must use either the same code or the same list and logic as libappstream so we can focus our efforts into one place. (https://github.com/ximion/appstream/blob/master/src/as-spdx.c#L741 + https://github.com/ximion/appstream/blob/master/data/spdx-free-license-ids.txt)

**Comment by barthalion** [comment]
This has been implemented.
