### ISSUE TITLE
installing apps fails, need to update instructions

### ISSUE THREAD

**Issue by sgehrman** [flathub/website#864]
just got a new pop os machine.

I followed the instructions and went to flathub to install apps but cilcking the install button just downloads a flatpakref

After some googling I found I had to run this:  $ sudo apt install gnome-software-plugin-flatpak

Why isn't this in your instructions???  A new user can't even install apps!!

**Comment by razzeee** [comment]
You probably mean, https://flatpak.org/setup/Pop!_OS as these are the only pop os instructions "we" have.
The correct repo would be https://github.com/flatpak/flatpak.github.io/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
