### ISSUE TITLE
Provide appstream links

### ISSUE THREAD

**Issue by gregorni** [flathub/website#870]
Apps' pages on [apps.kde.org](https://apps.kde.org) provide an Appstream link that opens the app directly in your system's app store. I would enjoy such a feature on Flathub, since I often browse apps there and the decide to install them from my app store. An Appstream button would get rid of the extra step of searching for the application and determining which one is the Flathub version.

**Comment by razzeee** [comment]
I don't think it would work like that. We in fact had this with the `.flatpakref` aka `Install` button, but most browsers seem to just download that file now.

Providing an appstream link, will only open up your software center and the app, there is no gurantee, it's the flatpak. It might be, as our id's are a bit more unique, but you can probably install other package managers, with similar ids.

**Comment by gregorni** [comment]
Oh, too bad. It would have been a nice feature, but I can see the problem. In that case, the issue is closed on my side.
