### ISSUE TITLE
Move all data from redis into postgres

### ISSUE THREAD

**Issue by razzeee** [flathub/website#874]
We should probably move all data from redis into postgres - best would probably be a separate DB, as we can then keep application data away from user data.

We can then simplify the infrastructure and dependencies quiet a bit and it shouldn't really make a difference for any api consumers.

**Comment by barthalion** [comment]
I'd generally stick to redis for any data that is easily reproducible, so at least appstream and the summary file. Anything that is stateful data should go to postgres.

**Comment by razzeee** [comment]
Yeah, then there's no point in doing this.

**Comment by razzeee** [comment]
Still, I think it would be way easier to handle stuff, especially when we need to link up vending with app data. Like actually showing the app name of whatever you bought. Which would now have to be another redis call or worse might provide an old ID.
