### ISSUE TITLE
Yuzu is broken

### ISSUE THREAD

**Issue by razzeee** [flathub/website#904]
For some reason https://beta.flathub.org/apps/details/org.yuzu_emu.yuzu is not working

**Comment by razzeee** [comment]
Caused by yuzu not having any releases

**Comment by razzeee** [comment]
Seems like https://github.com/flathub/org.yuzu_emu.yuzu/blob/master/org.yuzu_emu.yuzu.metainfo.xml#L51 not using semver causes it to not be included in the appstream.xml

**Comment by razzeee** [comment]
https://github.com/flathub/website/pull/905 fixes us not showing apps without releases, but the underlying problem should still be addressed.

**Comment by JakobDev** [comment]
This should also be fixed with flatpak/flatpak-builder#418

**Comment by razzeee** [comment]
Closing, as libappstream is here now
