### ISSUE TITLE
[Feature Request] Separate "media consumption" from "media production" apps in the categories

### ISSUE THREAD

**Issue by hyuri** [flathub/website#906]
Hi!

Any way to separate the "media consumption" apps from the "media production" ones? (Audio & Video)

I'm trying to look through the media production apps available (and I usually check again from time to time) and it's really hard to distinguish because there are so many media players and other media consumption apps mixed together with the production apps into a long multi-pages list.

**Comment by razzeee** [comment]
Nothing we have right now, but there are additional categories in the spec. Not sure they would be helpful for your usecase https://specifications.freedesktop.org/menu-spec/latest/apas02.html
