### ISSUE TITLE
Improve account deletion UX

### ISSUE THREAD

**Issue by kymckay** [flathub/website#94]
This has been on my backlog for a bit while prioritising donation checkout flow. Opening an issue so it's not forgotten.

Currently the account deletion button is situated at the top of the user page alongside logout and (in development) the wallet link. I have a few thoughts on how to improve it:

- [ ] I think a destructive action that will only be ever used once doesn't belong here where there's no convenience in it being at the top of the page. I'd probably opt to move it to the bottom of the page where it's still easy to access, but out of the way.
- [ ]  An additional benefit to moving the button is that the confirmation dialog could then easily be made inline on the page which would look nicer than the current fixed positioning (used to avoid spending time re-working or squeezing it into the top grid layout).
- [x] Another idea is to introduce a new styling for buttons associated with destructive actions (of which more will exist, e.g. saved payment card deletion). This would help to differentiate them from the much more common actions used throughout the site.

**Comment by razzeee** [comment]
https://github.com/flathub/website/issues/309 might help with parts of this too
