### ISSUE TITLE
Application new icon not detected

### ISSUE THREAD

**Issue by sixpounder** [flathub/website#940]
An application (com.github.sixpounder.GameOfLife) defines a new icon since two versions ago, but it seems not to be detected by the website.

The icon is placed in `/app/share/icons/hicolor/scalable/apps/` as per freedesktop specs, and has the application id as file name.

Am I missing something?

**Comment by razzeee** [comment]
Does look like https://github.com/sixpounder/game-of-life/blob/main/data/icons/hicolor/scalable/apps/com.github.sixpounder.GameOfLife.svg for me on both the beta website and the current one.

Did you drop your cache via F5 + Ctrl?

**Comment by sixpounder** [comment]
God, I feel stupid right now

Thank you for the quick reply

**Comment by razzeee** [comment]
Don't feel stupid, we've all been there
