### ISSUE TITLE
All methods of authentication are broken.

### ISSUE THREAD

**Issue by rokejulianlockhart** [flathub/website#957]
- [ ] https://github.com/flathub/website/issues/817
- [ ] https://github.com/flathub/website/issues/958
- [ ] https://github.com/flathub/website/issues/959
- [ ] https://github.com/flathub/website/issues/960

GitHub, GNOME, and Google all merely return 404.
![...Which this demonstrates.](https://user-images.githubusercontent.com/42837531/214453385-aefc1da7-4e24-4922-803e-85a942899dd2.png)

**Comment by razzeee** [comment]
This is tracked in https://github.com/flathub/website/issues/241

You can login via GitHub normally, the others are still missing environment setup. See https://github.com/flathub/website/issues/817 for e.g.
