### ISSUE TITLE
Restyle buttons with borders

### ISSUE THREAD

**Issue by bertob** [flathub/website#982]
The button style with borders still looks weird, I'd remove the border and replace it and only have semi-transparent text color (and slightly less transparent on hover/active):

![image](https://user-images.githubusercontent.com/1908896/216833495-256f6201-48f4-42e4-9b08-a96561e7aaa8.png)

**Comment by bertob** [comment]
Thanks, it's fixed on the home page now!

What I meant though was that this style should change everywhere, e.g. also on the screenshot carousel (and any other places it's used).

![image](https://user-images.githubusercontent.com/1908896/217294941-c552fb93-52bd-45a4-8408-e7d95f72af07.png)

**Comment by bertob** [comment]
Ah, also: The buttons look good on dark, but on light they're too transparent:

![image](https://user-images.githubusercontent.com/1908896/217295969-e004c5a7-0996-44b6-85ff-880e0467c810.png)

I'd maybe just steal the opacity values from the Adwaita CSS, a lot of work went into making sure the contrast is fine in all cases on those.

**Comment by razzeee** [comment]
Should hopefully be better

**Comment by bertob** [comment]
Not quite, in light mode the buttons are now even lighter, rather than darker :D

![image](https://user-images.githubusercontent.com/1908896/217682321-7dba8f92-a4ba-490d-916b-19b37621373b.png)

**Comment by razzeee** [comment]
Yes, I inverted that, basically to match the card style, as the dark one does.

**Comment by bertob** [comment]
That doesn't make sense here, dark and light are different in that respect. Buttons are transparent text color, but cards are always lighter than the background, including in dark mode, because they have shadows.

As mentioned elsewhere, we can really just copy what Adwaita does here, a lot of care went into calibrating contrast for all of these things there.

**Comment by razzeee** [comment]
The idea was, to explicitly avoid trying to steal from adwaita.

Let's see how it's after https://github.com/flathub/website/pull/1024
There will sure be some more low hanging fruits.

**Comment by bertob** [comment]
The new version is a bit better, but it reduces opacity on hover rather than increasing it, which is the wrong way around:

![image](https://user-images.githubusercontent.com/1908896/218059134-85be285d-7046-4ae5-9302-c4a87648e1c2.png)

On active it somehow drops the background entirely and turns the foreground blue:

![image](https://user-images.githubusercontent.com/1908896/218059299-25a409c3-2cb8-46bc-a072-6d9539747cf2.png)

> The idea was, to explicitly avoid trying to steal from adwaita.

I'm not saying everything should look like Adwaita, but taking the button transparency values for hover, active, dark, etc. just makes sense instead of reinventing the wheel. It's just transparent text-color as the background with increasing opacity from normal -> hover -> active, with reasonable values for contrast.
