### ISSUE TITLE
Verification is case sensitive

### ISSUE THREAD

**Issue by JakobDev** [flathub/website#995]
While playing around with the verification, I found this:
![grafik](https://user-images.githubusercontent.com/15185051/217197631-a4e78de3-f1c5-44b1-921d-68f28500d5d5.png)
The Usernames on GitLab and GitHub (and I believe other login providers too) are case insensitive, so the Verification should also be case insensitive.

**Comment by razzeee** [comment]
See https://github.com/flathub/website/issues/44#issuecomment-1419975561 and https://github.com/flathub/website/pull/992

**Comment by razzeee** [comment]
Should be working now
