### ISSUE TITLE
App page: Top section layout papercuts

### ISSUE THREAD

**Issue by bertob** [flathub/website#998]
On desktop:
- [x] Too much horizontal spacing between icon and title/author
- [x] Too much vertical spacing between title and author (I'd reduce it by about half)
- [x] Too much horizontal spacing between title and verified check (I'd reduce it by about 40%) 
- [x] Buttons on the right are not centered vertically on the content on the left

![image](https://user-images.githubusercontent.com/1908896/217299769-46346df7-95b7-4c3d-bfd4-2bff9820f4f3.png)

On mobile:
- [x] The app icon should be 128px
- [x] Either center the title/author name too, or left-align the icon like we do in Software
- [x] Buttons should be left-aligned or centered (matching the icon and title), rather than stretched

![image](https://user-images.githubusercontent.com/1908896/217300042-38c2e8db-5f9a-446c-9aa7-33da45375396.png)

**Comment by razzeee** [comment]
I don't think I get the last two points.

But let's first land the rest of the improvements.

**Comment by bertob** [comment]
> I don't think I get the last two points.

Basically, we have two choices here: The layou can either be left aligned or centered.

If we go with left-aligned (like e.g. GNOME Software) we need to left-align everything, including the buttons (rather than having them fill the fill width).

![image](https://user-images.githubusercontent.com/1908896/217401088-8879ae22-c872-4fa9-9f90-77d36adfdf65.png)

If we go with a centered layout (like e.g. the application Settings panels) we need to center everything, including the buttons.

![image](https://user-images.githubusercontent.com/1908896/217401675-e314b412-f4d2-4eae-a3de-f2204b75652e.png)

I think overall left-aligned makes more sense, but centered could maybe be made to work as well.

**Comment by razzeee** [comment]
I might be testing lower resolutions, so I'm not sure we can get away with the left aligned one, even the centered one might run into ugliness, when the app name is long and/or verified

![image](https://user-images.githubusercontent.com/5943908/217603907-45cef93f-d719-49d0-b052-6582f22af2c5.png)

Still, we might get away, with putting two buttons into a row, I can see that.

**Comment by razzeee** [comment]
centered stuff for now, I think it should be okay like that

**Comment by bertob** [comment]
This works, but the buttons get a bit too wider on the larger end of the mobile breakpoint. I'd add a max width of about 200px and center them.

![image](https://user-images.githubusercontent.com/1908896/217681874-c843c13f-93c0-408a-a312-b5d23030f110.png

**Comment by razzeee** [comment]
200 would clip the strings in some languages

e.g. 


![image](https://user-images.githubusercontent.com/5943908/217764130-93af62ac-1d56-4d6b-b4f7-4036c646a4c9.png)
this is at a bigger size, 250 to 300 might work.

**Comment by bertob** [comment]
Hmmm, are you sure that's not a problem with the locale? Generally coming up with reasonable strings is up to l10n teams.

**Comment by razzeee** [comment]
I don't know, looking over the strings of these the sweet spot seems to be around 11 chars, so this is clearly the worst case. But then again, I'm not speaking that language, so I probably can't judge :)

**Comment by razzeee** [comment]
Let's see how it feels after https://github.com/flathub/website/pull/1023

**Comment by RacerBG** [comment]
The smallest screen I have is a 5" Samsung Galaxy J3 2016 and it doesn't look promising. The buttons should be vertically aligned as it seems. Also, something seems off for the "Privacy Policy" text. See the screenshots below:

![Screenshot_2023-02-10-09-11-24](https://user-images.githubusercontent.com/68707872/218027617-924692c2-78d2-46a5-b93b-5045904df5a2.png)
![Screenshot_2023-02-10-09-11-12](https://user-images.githubusercontent.com/68707872/218027626-62310b74-083e-4d9a-b13d-90b9360188bb.png)

**Comment by razzeee** [comment]
Okay, the last one is weird, does that phone have a modern browser?

**Comment by RacerBG** [comment]
> Okay, the last one is weird, does that phone have a modern browser?

Nope. The updates stopped long ago. 😸

**Comment by bertob** [comment]
Definitely an improvement, but I'd scale both buttons down evenly rather than just the first one, this looks a bit weird:

![image](https://user-images.githubusercontent.com/1908896/218058027-a1a46c96-439e-4d46-9b6f-5853a82b0d54.png)

**Comment by razzeee** [comment]
Should be better with https://github.com/flathub/website/pull/1029

Turns out, firefox doesn't scale that low, should have used the mobile emulator for that.

**Comment by RacerBG** [comment]
> Should be better with #1029
> 
> Turns out, firefox doesn't scale that low, should have used the mobile emulator for that.

The Install and Donate buttons were fixed indeed. The other issues still remain the same.

**Comment by bertob** [comment]
LGTM at phone sizes now! One thing I'd maybe tweak is the breakpoint where it switches from horizontal to vertical layout, 768 seems unnecessarily high to switch to the mobile layout. Maybe 600 or so?

**Comment by razzeee** [comment]
We can do 640px see https://tailwindcss.com/docs/responsive-design

**Comment by bertob** [comment]
640 would be better :+1:

**Comment by razzeee** [comment]
To be clear, we can do custom ones, but so far sticking to the out of the box ones always was enough for my projects.

**Comment by bertob** [comment]
Let's try that for now, can always adjust later.

**Comment by razzeee** [comment]
has been done btw

**Comment by bertob** [comment]
Cool, then I think we can close this.
